// saflash — Phrases seed data (500+ real-world English phrases)
// Format: [phrase_en, phrase_es, category, context, difficulty]

const PHRASE_DATA = [
  // ── greetings (40) ──────────────────────
  ['Hello!', '¡Hola!', 'greetings', 'When greeting someone', 'A1'],
  ['Hi!', '¡Hola!', 'greetings', 'Informal greeting', 'A1'],
  ['Good morning!', '¡Buenos días!', 'greetings', 'Morning greeting', 'A1'],
  ['Good afternoon!', '¡Buenas tardes!', 'greetings', 'Afternoon greeting', 'A1'],
  ['Good evening!', '¡Buenas noches!', 'greetings', 'Evening greeting (on arrival)', 'A1'],
  ['Good night!', '¡Buenas noches!', 'greetings', 'When saying goodbye at night', 'A1'],
  ['How are you?', '¿Cómo estás?', 'greetings', 'When greeting someone you know', 'A1'],
  ["How's it going?", '¿Cómo va todo?', 'greetings', 'Informal greeting between friends', 'A1'],
  ['How are you doing?', '¿Cómo te va?', 'greetings', 'Casual greeting', 'A1'],
  ["What's up?", '¿Qué tal?', 'greetings', 'Very informal greeting', 'A2'],
  ['Nice to meet you!', '¡Mucho gusto!', 'greetings', 'When meeting someone', 'A1'],
  ['Pleased to meet you!', '¡Encantado de conocerte!', 'greetings', 'When meeting someone formally', 'A2'],
  ['Long time no see!', '¡Cuánto tiempo sin verte!', 'greetings', 'When reuniting with someone', 'B1'],
  ["It's been a while!", '¡Ha pasado un tiempo!', 'greetings', 'When reuniting', 'B1'],
  ['See you later!', '¡Nos vemos luego!', 'greetings', 'When saying goodbye', 'A1'],
  ['See you soon!', '¡Nos vemos pronto!', 'greetings', 'When saying goodbye expecting to meet again', 'A1'],
  ['See you tomorrow!', '¡Nos vemos mañana!', 'greetings', 'When saying goodbye', 'A1'],
  ['Take care!', '¡Cuídate!', 'greetings', 'When saying goodbye to someone close', 'A2'],
  ['Have a nice day!', '¡Que tengas un buen día!', 'greetings', 'When saying goodbye', 'A1'],
  ['Have a good weekend!', '¡Buen fin de semana!', 'greetings', 'Friday farewell', 'A1'],
  ['Welcome!', '¡Bienvenido!', 'greetings', 'When welcoming someone', 'A1'],
  ['Welcome back!', '¡Bienvenido de vuelta!', 'greetings', 'When someone returns', 'A2'],
  ["How have you been?", '¿Cómo has estado?', 'greetings', 'When reuniting after a long time', 'A2'],
  ["What's new?", '¿Qué hay de nuevo?', 'greetings', 'To start a conversation', 'A2'],
  ["Good to see you!", '¡Qué bueno verte!', 'greetings', 'When running into someone', 'A2'],
  ['Hey there!', '¡Eh, hola!', 'greetings', 'Very casual greeting', 'A2'],
  ['Morning!', '¡Buen día!', 'greetings', 'Short morning greeting', 'A1'],
  ['Afternoon!', '¡Buenas tardes!', 'greetings', 'Short afternoon greeting', 'A1'],
  ['Evening!', '¡Buenas noches!', 'greetings', 'Short evening greeting', 'A1'],
  ["How's your day going?", '¿Cómo va tu día?', 'greetings', "To ask about someone's day", 'A2'],
  ['Goodbye!', '¡Adiós!', 'greetings', 'Formal farewell', 'A1'],
  ['Bye!', '¡Chau! / ¡Adiós!', 'greetings', 'Informal farewell', 'A1'],
  ['Bye bye!', '¡Adiós adiós!', 'greetings', 'Affectionate farewell', 'A1'],
  ['Farewell!', '¡Hasta siempre!', 'greetings', 'Formal or final farewell', 'B2'],
  ['Until next time!', '¡Hasta la próxima!', 'greetings', 'Farewell expecting to meet again', 'B1'],
  ['Catch you later!', '¡Te veo después!', 'greetings', 'Very informal farewell', 'B1'],
  ['Have a safe trip!', '¡Buen viaje!', 'greetings', "When seeing off someone who's traveling", 'A2'],
  ['Talk to you soon!', '¡Hablamos pronto!', 'greetings', 'When saying goodbye on the phone', 'A2'],
  ['Lovely to meet you!', '¡Un placer conocerte!', 'greetings', 'When meeting someone enthusiastically', 'B1'],
  ['Greetings!', '¡Saludos!', 'greetings', 'Formal or written greeting', 'B1'],

  // ── courtesy (30) ────────────────────────
  ['Please', 'Por favor', 'courtesy', 'When asking for something', 'A1'],
  ['Thank you', 'Gracias', 'courtesy', 'When thanking someone', 'A1'],
  ['Thanks', 'Gracias', 'courtesy', 'Informal thanks', 'A1'],
  ['Thank you very much', 'Muchas gracias', 'courtesy', 'Emphatic thanks', 'A1'],
  ['Thanks a lot!', '¡Muchísimas gracias!', 'courtesy', 'Very emphatic thanks', 'A2'],
  ["You're welcome", 'De nada', 'courtesy', 'When responding to thanks', 'A1'],
  ['No problem', 'No hay problema', 'courtesy', 'Casual response to thanks', 'A2'],
  ["Don't mention it", 'Ni lo menciones', 'courtesy', 'Response to thanks', 'B1'],
  ['My pleasure', 'Es un placer', 'courtesy', 'Formal response to thanks', 'B1'],
  ['Excuse me', 'Disculpe / Permiso', 'courtesy', 'When interrupting or asking to pass', 'A1'],
  ["I'm sorry", 'Lo siento', 'courtesy', 'When apologizing', 'A1'],
  ['Sorry', 'Perdón', 'courtesy', 'Informal apology', 'A1'],
  ['I apologize', 'Me disculpo', 'courtesy', 'Formal apology', 'B1'],
  ['Forgive me', 'Perdóname', 'courtesy', 'When asking for forgiveness', 'B1'],
  ['Pardon me', 'Perdón / Disculpe', 'courtesy', 'When interrupting politely', 'B1'],
  ['May I?', '¿Puedo?', 'courtesy', 'When asking for permission', 'A2'],
  ['After you', 'Después de usted', 'courtesy', 'When letting someone go first', 'A2'],
  ['Go ahead', 'Adelante', 'courtesy', 'When giving way or permission', 'A2'],
  ['Bless you', 'Salud', 'courtesy', 'When someone sneezes', 'A2'],
  ['Cheers!', '¡Salud!', 'courtesy', 'When making a toast', 'A2'],
  ['Congratulations!', '¡Felicitaciones!', 'courtesy', 'When congratulating an achievement', 'A2'],
  ['Well done!', '¡Bien hecho!', 'courtesy', "When congratulating someone's work", 'A2'],
  ['Good luck!', '¡Buena suerte!', 'courtesy', 'When wishing someone success', 'A1'],
  ['All the best!', '¡Todo lo mejor!', 'courtesy', 'When saying goodbye with good wishes', 'B1'],
  ['Best wishes!', '¡Mis mejores deseos!', 'courtesy', 'When congratulating or saying goodbye in writing', 'B1'],
  ['Happy birthday!', '¡Feliz cumpleaños!', 'courtesy', 'When congratulating someone on their birthday', 'A1'],
  ['Merry Christmas!', '¡Feliz Navidad!', 'courtesy', 'Christmas greeting', 'A1'],
  ['Happy New Year!', '¡Feliz Año Nuevo!', 'courtesy', "New Year's greeting", 'A1'],
  ['Get well soon!', '¡Que te mejores pronto!', 'courtesy', "To someone who's sick", 'A2'],
  ['My apologies', 'Mis disculpas', 'courtesy', 'Formal apology', 'B1'],

  // ── questions (35) ───────────────────────
  ['What time is it?', '¿Qué hora es?', 'questions', 'When asking the time', 'A1'],
  ['Where is the bathroom?', '¿Dónde está el baño?', 'questions', 'When looking for the bathroom', 'A1'],
  ['How much does it cost?', '¿Cuánto cuesta?', 'questions', 'When asking a price', 'A1'],
  ['What is your name?', '¿Cómo te llamás?', 'questions', "When asking someone's name", 'A1'],
  ['Where are you from?', '¿De dónde sos?', 'questions', "When asking where someone's from", 'A1'],
  ['How old are you?', '¿Cuántos años tenés?', 'questions', "When asking someone's age", 'A1'],
  ['What do you do?', '¿A qué te dedicás?', 'questions', "When asking about someone's job", 'A2'],
  ['Do you speak English?', '¿Hablas inglés?', 'questions', 'When asking about languages', 'A1'],
  ['Can you help me?', '¿Me podés ayudar?', 'questions', 'When asking for help', 'A1'],
  ['Where do you live?', '¿Dónde vivís?', 'questions', 'When asking where someone lives', 'A1'],
  ['What is this?', '¿Qué es esto?', 'questions', 'When asking about an object', 'A1'],
  ['What does that mean?', '¿Qué significa eso?', 'questions', 'When asking for meaning', 'A2'],
  ['How do you say... in English?', '¿Cómo se dice... en inglés?', 'questions', 'When learning vocabulary', 'A2'],
  ['Could you repeat that?', '¿Podrías repetir eso?', 'questions', 'When not understanding something', 'A2'],
  ['Can you speak more slowly?', '¿Podés hablar más despacio?', 'questions', 'When asking for clarity', 'A2'],
  ['What happened?', '¿Qué pasó?', 'questions', 'When asking about an event', 'A2'],
  ["What's wrong?", '¿Qué pasa? / ¿Qué anda mal?', 'questions', 'When noticing someone is unwell', 'A2'],
  ['Are you okay?', '¿Estás bien?', 'questions', 'When worrying about someone', 'A2'],
  ['How was your day?', '¿Cómo estuvo tu día?', 'questions', "When asking about someone's day", 'A2'],
  ["What's the weather like?", '¿Cómo está el clima?', 'questions', 'When asking about the weather', 'A2'],
  ['Where can I find...?', '¿Dónde puedo encontrar...?', 'questions', 'When looking for something specific', 'A2'],
  ['How long does it take?', '¿Cuánto tiempo toma?', 'questions', 'When asking about duration', 'A2'],
  ['Is it far from here?', '¿Está lejos de aquí?', 'questions', 'When asking about distance', 'A2'],
  ['What do you recommend?', '¿Qué recomiendas?', 'questions', 'When asking for advice', 'A2'],
  ['Do you have...?', '¿Tenés...?', 'questions', 'When asking about availability', 'A1'],
  ['Would you like something to drink?', '¿Te gustaría algo para tomar?', 'questions', 'When offering a drink', 'A2'],
  ['Are you free tonight?', '¿Estás libre esta noche?', 'questions', 'When inviting someone', 'A2'],
  ['What do you think?', '¿Qué pensás?', 'questions', 'When asking for an opinion', 'A2'],
  ['How do you feel?', '¿Cómo te sentís?', 'questions', "When asking about someone's mood", 'A2'],
  ['Where did you go?', '¿A dónde fuiste?', 'questions', 'When asking about a trip', 'A2'],
  ['When does it start?', '¿Cuándo empieza?', 'questions', 'When asking about a schedule', 'A2'],
  ['Who is that?', '¿Quién es?', 'questions', 'When asking about a person', 'A1'],
  ['Why is that?', '¿Por qué es eso?', 'questions', 'When asking for a reason', 'A2'],
  ['Which one is yours?', '¿Cuál es el tuyo?', 'questions', 'When identifying ownership', 'A2'],
  ['How many people are coming?', '¿Cuántas personas vienen?', 'questions', 'When organizing an event', 'B1'],

  // ── introductions (30) ──────────────────
  ['My name is John', 'Me llamo John', 'introductions', 'When introducing yourself', 'A1'],
  ["I'm from Spain", 'Soy de España', 'introductions', "When saying where you're from", 'A1'],
  ['I live in Madrid', 'Vivo en Madrid', 'introductions', 'When saying where you live', 'A2'],
  ['I am a student', 'Soy estudiante', 'introductions', 'When talking about your occupation', 'A1'],
  ['I work in a hospital', 'Trabajo en un hospital', 'introductions', 'When talking about your job', 'A2'],
  ['I am a teacher', 'Soy profesor/a', 'introductions', 'When saying your profession', 'A1'],
  ['I study English', 'Estudio inglés', 'introductions', 'When talking about your studies', 'A1'],
  ["I'm learning Spanish", 'Estoy aprendiendo español', 'introductions', "When talking about the language you're learning", 'A2'],
  ['I have two children', 'Tengo dos hijos', 'introductions', 'When talking about your family', 'A2'],
  ["I'm married", 'Estoy casado/a', 'introductions', 'When talking about marital status', 'A2'],
  ['I like reading', 'Me gusta leer', 'introductions', 'When talking about hobbies', 'A2'],
  ['I enjoy cooking', 'Disfruto cocinar', 'introductions', 'When talking about pastimes', 'A2'],
  ['I play the guitar', 'Toco la guitarra', 'introductions', 'When talking about skills', 'A2'],
  ['I love traveling', 'Me encanta viajar', 'introductions', 'When talking about interests', 'A2'],
  ['I was born in 1990', 'Nací en 1990', 'introductions', 'When saying your birth year', 'A2'],
  ['I have a dog', 'Tengo un perro', 'introductions', 'When talking about pets', 'A1'],
  ['I moved here last year', 'Me mudé aquí el año pasado', 'introductions', 'When explaining your arrival', 'B1'],
  ["I'm an engineer", 'Soy ingeniero/a', 'introductions', 'When saying your profession', 'B1'],
  ['I work from home', 'Trabajo desde casa', 'introductions', 'When talking about a work arrangement', 'B1'],
  ["I'm here on vacation", 'Estoy aquí de vacaciones', 'introductions', 'When explaining the reason for your visit', 'A2'],
  ["I'm visiting family", 'Estoy visitando a mi familia', 'introductions', 'When explaining a visit', 'A2'],
  ['I come here often', 'Vengo aquí seguido', 'introductions', 'When talking about frequency', 'A2'],
  ['Let me introduce myself', 'Permitime presentarme', 'introductions', 'When starting a formal introduction', 'B1'],
  ['This is my friend Maria', 'Esta es mi amiga Maria', 'introductions', 'When introducing someone', 'A2'],
  ['I would like you to meet...', 'Me gustaría presentarte a...', 'introductions', 'When introducing formally', 'B1'],
  ['We work together', 'Trabajamos juntos', 'introductions', 'When explaining a work relationship', 'A2'],
  ["I've heard a lot about you", 'He escuchado mucho sobre vos', 'introductions', 'When meeting someone famous', 'B1'],
  ['Nice to finally meet you', 'Qué bueno conocerte por fin', 'introductions', 'When meeting someone in person', 'B1'],
  ["I don't think we've met", 'Creo que no nos conocemos', 'introductions', 'When approaching someone new', 'B1'],
  ['Tell me about yourself', 'Contame sobre vos', 'introductions', 'When asking someone to introduce themselves', 'A2'],

  // ── shopping (35) ────────────────────────
  ['How much is this?', '¿Cuánto cuesta esto?', 'shopping', 'When asking the price in a store', 'A1'],
  ['Do you have this in my size?', '¿Tenés esto en mi talle?', 'shopping', 'When looking for clothes', 'A2'],
  ['I would like to pay by card', 'Quisiera pagar con tarjeta', 'shopping', 'When paying', 'A2'],
  ['Can I try this on?', '¿Me puedo probar esto?', 'shopping', 'When trying on clothes', 'A2'],
  ['Where is the fitting room?', '¿Dónde está el probador?', 'shopping', 'When looking for where to try on clothes', 'A2'],
  ["I'm just looking, thanks", 'Solo estoy mirando, gracias', 'shopping', "When declining a salesperson's help", 'A2'],
  ['Do you have a smaller size?', '¿Tenés un talle más chico?', 'shopping', 'When asking for another size', 'A2'],
  ['Do you have this in another color?', '¿Tenés esto en otro color?', 'shopping', 'When looking for variety', 'A2'],
  ['Where can I pay?', '¿Dónde puedo pagar?', 'shopping', 'When looking for the checkout', 'A2'],
  ['Can I get a receipt?', '¿Me podés dar un recibo?', 'shopping', 'When asking for a receipt', 'B1'],
  ['Is there a discount?', '¿Hay descuento?', 'shopping', 'When asking about deals', 'A2'],
  ['How much is the total?', '¿Cuánto es el total?', 'shopping', 'When finding out the final price', 'A2'],
  ["I'll take it", 'Me lo llevo', 'shopping', 'When deciding to buy', 'A2'],
  ["It's too expensive", 'Es demasiado caro', 'shopping', 'When considering something expensive', 'A2'],
  ['Do you accept credit cards?', '¿Aceptan tarjetas de crédito?', 'shopping', 'When asking about payment method', 'B1'],
  ['Can I return this?', '¿Puedo devolver esto?', 'shopping', 'When wanting to return a product', 'B1'],
  ['Is this on sale?', '¿Está en oferta?', 'shopping', "When asking if there's a discount", 'A2'],
  ['Where is the shoe section?', '¿Dónde está la sección de zapatos?', 'shopping', 'When looking for a specific section', 'A2'],
  ['What time do you close?', '¿A qué hora cierran?', 'shopping', 'When asking about a schedule', 'A2'],
  ['Do you have a bag?', '¿Tenés una bolsa?', 'shopping', 'When needing a bag', 'A2'],
  ["I'm looking for a gift", 'Estoy buscando un regalo', 'shopping', 'When looking for a gift', 'B1'],
  ['Can you gift wrap it?', '¿Lo pueden envolver para regalo?', 'shopping', 'When asking for wrapping', 'B1'],
  ['Is this the final price?', '¿Este es el precio final?', 'shopping', 'When confirming a price', 'B1'],
  ['Can I have a refund?', '¿Me pueden hacer un reembolso?', 'shopping', 'When asking for a refund', 'B1'],
  ["It doesn't fit me", 'No me queda bien', 'shopping', "When trying on clothes that don't fit", 'A2'],
  ['Where are the fitting rooms?', '¿Dónde están los probadores?', 'shopping', 'When looking for fitting rooms', 'A2'],
  ['I need a larger size', 'Necesito un talle más grande', 'shopping', 'When asking for a bigger size', 'A2'],
  ['This is broken', 'Esto está roto', 'shopping', 'When finding a damaged product', 'A2'],
  ['Can I exchange this?', '¿Puedo cambiar esto?', 'shopping', 'When wanting to exchange a product', 'B1'],
  ['How long is the warranty?', '¿Cuánto dura la garantía?', 'shopping', 'When asking about a warranty', 'B1'],
  ['I paid in cash', 'Pagué en efectivo', 'shopping', 'When saying how you paid', 'A2'],
  ['Keep the change', 'Quedate con el cambio', 'shopping', 'When leaving a tip or change', 'A2'],
  ['Are you open on Sundays?', '¿Abren los domingos?', 'shopping', 'When asking about hours', 'A2'],
  ['Where can I find...?', '¿Dónde puedo encontrar...?', 'shopping', 'When looking for a specific product', 'A2'],
  ['Do you sell...?', '¿Venden...?', 'shopping', 'When asking if something is sold', 'A2'],

  // ── restaurant (40) ─────────────────────
  ['I would like a table for two', 'Quisiera una mesa para dos', 'restaurant', 'When arriving at a restaurant', 'A2'],
  ['What do you recommend?', '¿Qué recomiendas?', 'restaurant', 'When asking the waiter for a suggestion', 'A2'],
  ['The check, please', 'La cuenta, por favor', 'restaurant', 'When asking for the check', 'A2'],
  ['Can I see the menu?', '¿Me podés mostrar el menú?', 'restaurant', 'When asking for the menu', 'A2'],
  ["I'm ready to order", 'Estoy listo para pedir', 'restaurant', 'When ordering', 'A2'],
  ['What are today\'s specials?', '¿Cuáles son los especiales del día?', 'restaurant', 'When asking about the daily specials', 'B1'],
  ['I have a reservation', 'Tengo una reserva', 'restaurant', 'When arriving with a reservation', 'B1'],
  ['Do you have vegetarian options?', '¿Tienen opciones vegetarianas?', 'restaurant', 'When asking about vegetarian food', 'B1'],
  ['Can I have some water please?', '¿Me podés dar agua por favor?', 'restaurant', 'When asking for water', 'A2'],
  ["I'll have the same", 'Voy a pedir lo mismo', 'restaurant', 'When ordering the same as someone else', 'A2'],
  ['Is the tip included?', '¿La propina está incluida?', 'restaurant', 'When asking about the service charge', 'B1'],
  ['This is delicious!', '¡Está delicioso!', 'restaurant', 'When enjoying the food', 'A2'],
  ['I am allergic to nuts', 'Soy alérgico a las nueces', 'restaurant', 'When reporting an allergy', 'B1'],
  ['Can we sit by the window?', '¿Podemos sentarnos junto a la ventana?', 'restaurant', 'When choosing a location', 'B1'],
  ['Could I have a fork please?', '¿Me podrías dar un tenedor por favor?', 'restaurant', 'When asking for cutlery', 'A2'],
  ['What do you have for dessert?', '¿Qué tienen de postre?', 'restaurant', 'When asking about desserts', 'A2'],
  ['Can I get a refill?', '¿Me pueden servir más?', 'restaurant', 'When asking for a drink refill', 'B1'],
  ['The food is cold', 'La comida está fría', 'restaurant', 'When complaining about the temperature', 'A2'],
  ['Can you make it spicy?', '¿Lo pueden hacer picante?', 'restaurant', 'When asking for spicy food', 'B1'],
  ['Is this dish gluten-free?', '¿Este plato es sin gluten?', 'restaurant', 'When asking about dietary restrictions', 'B1'],
  ['I would like to make a reservation', 'Quisiera hacer una reserva', 'restaurant', 'When booking by phone', 'B1'],
  ['How long is the wait?', '¿Cuánto hay que esperar?', 'restaurant', 'When asking about wait time', 'B1'],
  ['Can we have separate checks?', '¿Podemos tener cuentas separadas?', 'restaurant', 'When asking to split the bill', 'B2'],
  ['Do you serve breakfast all day?', '¿Sirven desayuno todo el día?', 'restaurant', 'When asking about hours', 'B1'],
  ['Could I have a napkin?', '¿Me podrías dar una servilleta?', 'restaurant', 'When asking for a napkin', 'A2'],
  ['What kind of dressing do you have?', '¿Qué tipo de aderezo tienen?', 'restaurant', 'When asking about dressings', 'B1'],
  ['Can I have it to go?', '¿Me lo pueden dar para llevar?', 'restaurant', 'When asking for food to go', 'A2'],
  ['Is there a kids\' menu?', '¿Hay menú infantil?', 'restaurant', "When asking about a kids' menu", 'B1'],
  ['A table for four, please', 'Una mesa para cuatro, por favor', 'restaurant', 'When asking for a table', 'A2'],
  ['Can I have some bread?', '¿Me pueden dar pan?', 'restaurant', 'When asking for bread', 'A2'],
  ['Are you still serving?', '¿Todavía están sirviendo?', 'restaurant', 'When arriving close to closing time', 'B1'],
  ['Well done, please', 'Bien cocido, por favor', 'restaurant', "When asking for the meat's doneness", 'B1'],
  ['Medium rare, please', 'Término medio, por favor', 'restaurant', 'When asking how well-done the meat should be', 'B1'],
  ['Just water for me', 'Solo agua para mí', 'restaurant', 'When asking for just water', 'A2'],
  ['Can I have some salt?', '¿Me podés dar sal?', 'restaurant', 'When asking for salt', 'A2'],
  ['Could we have more napkins?', '¿Podrían traernos más servilletas?', 'restaurant', 'When asking for more napkins', 'A2'],
  ['Do you have any specials tonight?', '¿Tienen especiales esta noche?', 'restaurant', 'When asking about specials', 'B1'],
  ['That was excellent, thank you!', 'Estuvo excelente, ¡gracias!', 'restaurant', 'When finishing the meal', 'A2'],
  ['Can I have the bill please?', '¿Me puede dar la cuenta por favor?', 'restaurant', 'When asking for the check', 'A2'],
  ['We would like to order now', 'Quisiéramos ordenar ahora', 'restaurant', 'When calling the waiter', 'B1'],

  // ── travel (40) ──────────────────────────
  ['Where is the nearest hotel?', '¿Dónde está el hotel más cercano?', 'travel', 'When looking for lodging', 'A2'],
  ['I need a taxi', 'Necesito un taxi', 'travel', 'When asking for transportation', 'A2'],
  ['My flight is at 8am', 'Mi vuelo es a las 8 de la mañana', 'travel', 'When talking about a flight schedule', 'A2'],
  ['I lost my passport', 'Perdí mi pasaporte', 'travel', 'In a travel emergency', 'B1'],
  ['Where is the bus station?', '¿Dónde está la estación de buses?', 'travel', 'When looking for transportation', 'A2'],
  ['How do I get to the airport?', '¿Cómo llego al aeropuerto?', 'travel', 'When asking for directions', 'A2'],
  ['Can I have a map?', '¿Me podés dar un mapa?', 'travel', 'When asking for directions', 'A2'],
  ['I have a reservation', 'Tengo una reserva', 'travel', 'When arriving at the hotel', 'B1'],
  ['What time is checkout?', '¿A qué hora es la salida?', 'travel', 'When asking at the hotel', 'B1'],
  ['Is breakfast included?', '¿El desayuno está incluido?', 'travel', 'When asking at the hotel', 'A2'],
  ['Can you call a taxi for me?', '¿Me podés llamar un taxi?', 'travel', 'When asking for help at the hotel', 'A2'],
  ['I would like a round-trip ticket', 'Quisiera un boleto de ida y vuelta', 'travel', 'When buying tickets', 'B1'],
  ['How long is the flight?', '¿Cuánto dura el vuelo?', 'travel', 'When asking about duration', 'A2'],
  ['Is there a direct flight?', '¿Hay vuelo directo?', 'travel', 'When looking for flights', 'B1'],
  ['Where is the train station?', '¿Dónde está la estación de tren?', 'travel', 'When looking for a station', 'A2'],
  ['How much is a ticket to London?', '¿Cuánto cuesta un boleto a Londres?', 'travel', 'When buying a ticket', 'A2'],
  ['Is this seat taken?', '¿Está ocupado este asiento?', 'travel', 'When looking for a seat', 'A2'],
  ['I missed my flight', 'Perdí mi vuelo', 'travel', 'In a travel emergency', 'B1'],
  ['Can I change my reservation?', '¿Puedo cambiar mi reserva?', 'travel', 'When changing plans', 'B1'],
  ['Where can I exchange money?', '¿Dónde puedo cambiar dinero?', 'travel', 'When looking to exchange currency', 'B1'],
  ['Do you have a single room?', '¿Tenés una habitación individual?', 'travel', 'When booking a hotel', 'A2'],
  ['Can I see the room?', '¿Puedo ver la habitación?', 'travel', 'When evaluating lodging', 'B1'],
  ['The air conditioning doesn\'t work', 'El aire acondicionado no funciona', 'travel', 'When complaining at the hotel', 'B1'],
  ['Can I have an extra towel?', '¿Me podés dar una toalla extra?', 'travel', 'When asking for something at the hotel', 'A2'],
  ['I need a wake-up call', 'Necesito una llamada de despertador', 'travel', 'When requesting hotel service', 'B1'],
  ['Where is the nearest bus stop?', '¿Dónde está la parada de bus más cercana?', 'travel', 'When looking for public transportation', 'A2'],
  ['What terminal is my flight?', '¿En qué terminal sale mi vuelo?', 'travel', 'When getting oriented at the airport', 'B1'],
  ['Has my flight been delayed?', '¿Mi vuelo fue demorado?', 'travel', 'When checking status', 'B1'],
  ['I need to check in', 'Necesito hacer el check-in', 'travel', 'When arriving at the hotel or airport', 'A2'],
  ['Can I have a window seat?', '¿Puedo tener un asiento en ventanilla?', 'travel', 'When choosing a seat', 'B1'],
  ['My luggage is missing', 'Perdieron mi equipaje', 'travel', 'When reporting lost luggage', 'B1'],
  ['How far is the hotel from the airport?', '¿Qué tan lejos está el hotel del aeropuerto?', 'travel', 'When planning a transfer', 'B1'],
  ['I would like to book a tour', 'Quisiera reservar un tour', 'travel', 'When booking an excursion', 'B1'],
  ['Is there free Wi-Fi?', '¿Hay Wi-Fi gratis?', 'travel', 'When asking at the hotel', 'A2'],
  ['How do I get to the city center?', '¿Cómo llego al centro?', 'travel', 'When getting oriented in a city', 'A2'],
  ['Can you help me with my bags?', '¿Me podés ayudar con las valijas?', 'travel', 'When asking for help with luggage', 'A2'],
  ['Do I need a visa?', '¿Necesito visa?', 'travel', 'When planning international travel', 'B1'],
  ['What is the local currency?', '¿Cuál es la moneda local?', 'travel', 'When learning about a destination', 'B1'],
  ['Is it safe to walk at night?', '¿Es seguro caminar de noche?', 'travel', 'When asking about safety', 'B1'],
  ['Where can I buy a SIM card?', '¿Dónde puedo comprar un chip de teléfono?', 'travel', 'When needing a phone', 'B1'],

  // ── work (35) ────────────────────────────
  ['I have a meeting at 3pm', 'Tengo una reunión a las 3 de la tarde', 'work', 'When talking about a schedule', 'A2'],
  ['Can you send me the report?', '¿Me podés enviar el informe?', 'work', 'When asking for a document', 'A2'],
  ["I'm on vacation next week", 'Estoy de vacaciones la semana que viene', 'work', 'When reporting an absence', 'A2'],
  ['What time does the meeting start?', '¿A qué hora empieza la reunión?', 'work', 'When asking about a schedule', 'A2'],
  ['I need to finish this by Friday', 'Necesito terminar esto para el viernes', 'work', 'When talking about deadlines', 'B1'],
  ['Could you help me with this?', '¿Me podrías ayudar con esto?', 'work', 'When asking for help', 'A2'],
  ['Let me check my calendar', 'Dejame revisar mi calendario', 'work', 'When checking availability', 'B1'],
  ["I'll get back to you", 'Te respondo después', 'work', 'When postponing a response', 'B1'],
  ['Can we reschedule?', '¿Podemos reprogramar?', 'work', 'When changing an appointment', 'B1'],
  ['Please send me the details', 'Por favor enviame los detalles', 'work', 'When asking for information', 'B1'],
  ['The deadline is Monday', 'La fecha límite es el lunes', 'work', 'When reminding about a deadline', 'B1'],
  ["I'm working from home today", 'Hoy trabajo desde casa', 'work', 'When reporting a work arrangement', 'B1'],
  ['Can I have a day off?', '¿Me puedo tomar un día libre?', 'work', 'When asking for permission', 'B1'],
  ['We need to discuss this', 'Tenemos que hablar de esto', 'work', 'When starting a serious conversation', 'B1'],
  ['Great job on the presentation!', '¡Buen trabajo en la presentación!', 'work', 'When congratulating a coworker', 'B1'],
  ['I have a deadline coming up', 'Se me viene una fecha límite', 'work', 'When talking about work pressure', 'B1'],
  ["Let's schedule a call", 'Coordinemos una llamada', 'work', 'When proposing a virtual meeting', 'B1'],
  ['Can you cover for me?', '¿Me podés cubrir?', 'work', 'When asking for a replacement', 'B1'],
  ["I'll be in a meeting all afternoon", 'Voy a estar en reunión toda la tarde', 'work', 'When reporting availability', 'B1'],
  ['Please review this document', 'Por favor revisá este documento', 'work', 'When asking for a review', 'B1'],
  ['I need an extension on this', 'Necesito una extensión para esto', 'work', 'When asking for more time', 'B1'],
  ['The client is waiting for our response', 'El cliente está esperando nuestra respuesta', 'work', 'When prioritizing a task', 'B1'],
  ['Could you clarify what you mean?', '¿Podrías aclarar a qué te referís?', 'work', 'When asking for clarity', 'B1'],
  ["Let's touch base tomorrow", 'Charlemos mañana para ver cómo va', 'work', 'When proposing a follow-up', 'B2'],
  ['I need to run this by my manager', 'Tengo que consultarlo con mi jefe', 'work', 'When needing approval', 'B2'],
  ['Do you have a moment to talk?', '¿Tenés un momento para hablar?', 'work', 'When asking for a brief meeting', 'A2'],
  ["I'm on a tight schedule", 'Tengo una agenda ajustada', 'work', 'When explaining a time constraint', 'B1'],
  ['Can we move the meeting to 2pm?', '¿Podemos mover la reunión a las 2?', 'work', 'When changing a schedule', 'B1'],
  ['Please CC me on that email', 'Por favor poneme en copia en ese correo', 'work', 'When asking to be included in communications', 'B1'],
  ["I'll take care of it", 'Yo me encargo', 'work', 'When taking responsibility', 'B1'],
  ['The project is on track', 'El proyecto va bien encaminado', 'work', 'When reporting status', 'B1'],
  ["Let's circle back to that later", 'Volvamos a eso más tarde', 'work', 'When postponing a discussion', 'B2'],
  ['We have a tight deadline', 'Tenemos una fecha límite ajustada', 'work', 'When talking about pressure', 'B1'],
  ["I'll send you the minutes", 'Te envío las notas de la reunión', 'work', 'When promising to send a summary', 'B1'],
  ['I need to prepare for the presentation', 'Necesito preparar la presentación', 'work', 'When planning work', 'B1'],

  // ── health (30) ─────────────────────────
  ["I don't feel well", 'No me siento bien', 'health', 'When feeling unwell', 'A2'],
  ['I have a headache', 'Tengo dolor de cabeza', 'health', 'When describing a symptom', 'A2'],
  ['I need to see a doctor', 'Necesito ver a un médico', 'health', 'When seeking medical care', 'A2'],
  ['Where is the nearest hospital?', '¿Dónde está el hospital más cercano?', 'health', 'In an emergency', 'A2'],
  ['I have a stomachache', 'Me duele el estómago', 'health', 'When describing pain', 'A2'],
  ['I feel dizzy', 'Me siento mareado', 'health', 'When describing a symptom', 'B1'],
  ['I twisted my ankle', 'Me torcí el tobillo', 'health', 'When describing an injury', 'B1'],
  ['Can you call an ambulance?', '¿Podés llamar a una ambulancia?', 'health', 'In a serious emergency', 'B1'],
  ['I need a prescription', 'Necesito una receta', 'health', 'When asking for medication', 'B1'],
  ['Are you allergic to any medication?', '¿Sos alérgico a algún medicamento?', 'health', 'Medical question', 'B1'],
  ['I have a fever', 'Tengo fiebre', 'health', 'When describing a symptom', 'A2'],
  ['My throat hurts', 'Me duele la garganta', 'health', 'When describing pain', 'A2'],
  ['I have a runny nose', 'Tengo la nariz que me gotea', 'health', 'When describing a cold symptom', 'B1'],
  ['I feel nauseous', 'Siento náuseas', 'health', 'When describing discomfort', 'B1'],
  ['How long have you had these symptoms?', '¿Hace cuánto tenés estos síntomas?', 'health', 'Medical question', 'B1'],
  ['I need to make an appointment', 'Necesito hacer una cita', 'health', "When asking for a doctor's appointment", 'B1'],
  ['Do you have insurance?', '¿Tenés seguro médico?', 'health', 'Administrative question', 'B1'],
  ['Take this medicine twice a day', 'Tomá esta medicina dos veces al día', 'health', 'Medical instruction', 'B1'],
  ['I have a sore throat', 'Tengo dolor de garganta', 'health', 'When describing a symptom', 'A2'],
  ['I need some painkillers', 'Necesito analgésicos', 'health', 'When asking for medicine', 'B1'],
  ['My back hurts', 'Me duele la espalda', 'health', 'When describing pain', 'A2'],
  ['I feel much better now', 'Me siento mucho mejor ahora', 'health', 'When reporting improvement', 'A2'],
  ['You should get some rest', 'Deberías descansar', 'health', 'When giving advice', 'A2'],
  ['I have a toothache', 'Tengo dolor de muelas', 'health', 'When describing dental pain', 'B1'],
  ['I need to see a dentist', 'Necesito ver a un dentista', 'health', 'When seeking dental care', 'B1'],
  ['Stay hydrated', 'Mantenete hidratado', 'health', 'Medical advice', 'B1'],
  ['I have a cough', 'Tengo tos', 'health', 'When describing a symptom', 'A2'],
  ['Do I need stitches?', '¿Necesito puntos?', 'health', 'When assessing a wound', 'B2'],
  ['Get some fresh air', 'Tomá un poco de aire fresco', 'health', 'Advice for feeling better', 'B1'],
  ['I have a cold', 'Estoy resfriado', 'health', 'When describing an illness', 'A2'],

  // ── directions (30) ─────────────────────
  ['Turn left', 'Girá a la izquierda', 'directions', 'When giving directions', 'A2'],
  ['Go straight', 'Seguí derecho', 'directions', 'When giving directions', 'A2'],
  ['It\'s on the right', 'Está a la derecha', 'directions', 'When locating something', 'A2'],
  ['How far is it?', '¿Qué tan lejos está?', 'directions', 'When asking about distance', 'A2'],
  ['Turn right at the corner', 'Girá a la derecha en la esquina', 'directions', 'When giving directions', 'A2'],
  ["It's on the left", 'Está a la izquierda', 'directions', 'When locating something', 'A2'],
  ['Go straight ahead', 'Seguí derecho', 'directions', 'When giving directions', 'A2'],
  ['Take the first left', 'Tomá la primera a la izquierda', 'directions', 'When giving directions', 'B1'],
  ['Is it within walking distance?', '¿Se puede ir caminando?', 'directions', 'When asking about distance', 'B1'],
  ['It\'s around the corner', 'Está a la vuelta de la esquina', 'directions', 'When locating something nearby', 'B1'],
  ['Go past the bank', 'Pasá el banco', 'directions', 'When giving directions', 'B1'],
  ['Cross the street', 'Cruzá la calle', 'directions', 'When giving directions', 'A2'],
  ["It's at the end of the street", 'Está al final de la calle', 'directions', 'When locating something', 'B1'],
  ['Take the second right', 'Tomá la segunda a la derecha', 'directions', 'When giving directions', 'B1'],
  ['Go down this street', 'Bajá por esta calle', 'directions', 'When giving directions', 'A2'],
  ['You can\'t miss it', 'No te lo podés perder', 'directions', "When assuring it's easy to find", 'B1'],
  ['It\'s next to the pharmacy', 'Está al lado de la farmacia', 'directions', 'When locating by landmark', 'A2'],
  ['Turn around', 'Date la vuelta', 'directions', 'When indicating a change of direction', 'A2'],
  ["It's across from the park", 'Está enfrente del parque', 'directions', 'When locating by landmark', 'B1'],
  ['I am lost', 'Estoy perdido', 'directions', 'When asking for help', 'A2'],
  ['Can you show me on the map?', '¿Me podés mostrar en el mapa?', 'directions', 'When asking for directions', 'A2'],
  ["It's two blocks away", 'Está a dos cuadras', 'directions', 'When giving a distance', 'A2'],
  ['Go up the stairs', 'Subí las escaleras', 'directions', 'When giving directions inside a building', 'A2'],
  ['Take the elevator', 'Tomá el ascensor', 'directions', 'When giving directions inside a building', 'A2'],
  ["It's on the second floor", 'Está en el segundo piso', 'directions', 'When locating something in a building', 'A2'],
  ['Follow this road', 'Seguí este camino', 'directions', 'When giving directions', 'B1'],
  ['Keep going until you see...', 'Seguí hasta que veas...', 'directions', 'When giving directions', 'B1'],
  ["It's behind the supermarket", 'Está detrás del supermercado', 'directions', 'When locating by landmark', 'B1'],
  ['Head north', 'Andá hacia el norte', 'directions', 'When giving cardinal directions', 'B1'],
  ['Is this the right way?', '¿Voy bien por acá?', 'directions', 'When confirming a direction', 'A2'],

  // ── phone (25) ───────────────────────────
  ['Can I call you later?', '¿Te puedo llamar después?', 'phone', 'When ending a call', 'A2'],
  ['Could you speak more slowly?', '¿Podrías hablar más despacio?', 'phone', 'When asking for clarity', 'A2'],
  ["I'll text you", 'Te mando un mensaje', 'phone', 'When promising to stay in touch in writing', 'A2'],
  ['My phone is about to die', 'Mi teléfono está por apagarse', 'phone', 'When warning about low battery', 'B1'],
  ['I have bad reception here', 'Tengo mala señal acá', 'phone', 'When explaining communication problems', 'B1'],
  ['Can you hear me?', '¿Me escuchás?', 'phone', 'When checking audio', 'A2'],
  ['Let me call you back', 'Dejame que te llamo de vuelta', 'phone', 'When postponing a call', 'B1'],
  ['What is your phone number?', '¿Cuál es tu número de teléfono?', 'phone', 'When asking for contact info', 'A1'],
  ['I missed your call', 'Perdí tu llamada', 'phone', 'When checking calls', 'A2'],
  ['Leave a message after the beep', 'Dejá un mensaje después del tono', 'phone', 'Voicemail', 'B1'],
  ['I need to charge my phone', 'Necesito cargar mi teléfono', 'phone', 'When running out of battery', 'A2'],
  ['Can I use your charger?', '¿Puedo usar tu cargador?', 'phone', 'When asking to borrow something', 'A2'],
  ['The line is busy', 'La línea está ocupada', 'phone', 'When trying to make a call', 'B1'],
  ['I will give you a call', 'Te voy a hacer una llamada', 'phone', 'When promising to call', 'A2'],
  ['Can you send me a text?', '¿Me podés mandar un mensaje?', 'phone', 'When asking for a text message', 'A2'],
  ['I lost your number', 'Perdí tu número', 'phone', 'When losing touch', 'A2'],
  ['Can I have your number?', '¿Me podés dar tu número?', 'phone', 'When asking for contact info', 'A2'],
  ['I need to make a phone call', 'Necesito hacer una llamada', 'phone', 'When looking for a phone', 'A2'],
  ['Hold on, someone is calling me', 'Esperá, me están llamando', 'phone', 'When receiving another call', 'B1'],
  ['My signal keeps dropping', 'Se me corta la señal', 'phone', 'When explaining a bad connection', 'B1'],
  ['Can you put me on speaker?', '¿Me ponés en altavoz?', 'phone', 'When asking for hands-free mode', 'B1'],
  ['Let me check my messages', 'Dejame revisar mis mensajes', 'phone', 'When checking notifications', 'A2'],
  ['Did you get my text?', '¿Recibiste mi mensaje?', 'phone', 'When verifying communication', 'A2'],
  ["I'll send you the address", 'Te mando la dirección', 'phone', 'When promising to send details', 'A2'],
  ['My phone is on silent', 'Tengo el teléfono en silencio', 'phone', "When explaining you can't be heard", 'B1'],

  // ── emotions (30) ────────────────────────
  ["I'm very happy", 'Estoy muy feliz', 'emotions', 'When expressing joy', 'A2'],
  ["I'm a little tired", 'Estoy un poco cansado', 'emotions', 'When expressing tiredness', 'A2'],
  ["That's amazing!", '¡Eso es increíble!', 'emotions', 'When expressing amazement', 'A2'],
  ["I'm not sure", 'No estoy seguro', 'emotions', 'When expressing doubt', 'A2'],
  ["I'm so excited!", '¡Estoy tan emocionado!', 'emotions', 'When expressing enthusiasm', 'A2'],
  ["I'm worried about you", 'Estoy preocupado por vos', 'emotions', 'When expressing worry', 'B1'],
  ["I'm feeling nervous", 'Me siento nervioso', 'emotions', 'When expressing anxiety', 'B1'],
  ["That's so funny!", '¡Qué gracioso!', 'emotions', 'When reacting to something funny', 'A2'],
  ["I'm disappointed", 'Estoy decepcionado', 'emotions', 'When expressing disappointment', 'B1'],
  ["I'm so proud of you!", '¡Estoy tan orgulloso de vos!', 'emotions', 'When expressing pride', 'B1'],
  ["I'm really stressed out", 'Estoy muy estresado', 'emotions', 'When expressing stress', 'B1'],
  ["That's so sweet of you!", '¡Qué dulce de tu parte!', 'emotions', 'When thanking someone for a kind gesture', 'B1'],
  ["I'm confused", 'Estoy confundido', 'emotions', 'When expressing confusion', 'A2'],
  ["I feel lonely", 'Me siento solo', 'emotions', 'When expressing loneliness', 'B1'],
  ["You scared me!", '¡Me asustaste!', 'emotions', 'When reacting to a scare', 'A2'],
  ["I'm grateful for your help", 'Estoy agradecido por tu ayuda', 'emotions', 'When expressing gratitude', 'B1'],
  ["I'm shocked!", '¡Estoy en shock!', 'emotions', 'When expressing shock', 'B1'],
  ["That's so annoying", 'Qué molesto', 'emotions', 'When expressing annoyance', 'B1'],
  ["I'm over the moon!", '¡Estoy en la luna!', 'emotions', 'When expressing extreme happiness', 'B2'],
  ["I'm heartbroken", 'Tengo el corazón roto', 'emotions', 'When expressing deep sadness', 'B2'],
  ["You made my day!", '¡Me alegraste el día!', 'emotions', 'When thanking someone for a gesture', 'B1'],
  ["I'm fed up", 'Estoy harto', 'emotions', 'When expressing frustration', 'B2'],
  ["That's a relief!", '¡Qué alivio!', 'emotions', 'When feeling relief', 'B1'],
  ["I'm jealous", 'Estoy celoso / Tengo envidia', 'emotions', 'When expressing jealousy', 'B1'],
  ["I can't believe it!", '¡No lo puedo creer!', 'emotions', 'When expressing disbelief', 'A2'],
  ["I'm furious!", '¡Estoy furioso!', 'emotions', 'When expressing extreme anger', 'B1'],
  ["Take it easy", 'Tomalo con calma', 'emotions', 'When calming someone down', 'A2'],
  ["Don't worry about it", 'No te preocupes por eso', 'emotions', 'When reassuring someone', 'A2'],
  ["Cheer up!", '¡Animate!', 'emotions', "When cheering up someone who's sad", 'A2'],
  ["Calm down", 'Tranquilizate', 'emotions', "When calming someone who's upset", 'A2'],

  // ── time (35) ────────────────────────────
  ['What time is it?', '¿Qué hora es?', 'time', 'When asking the time', 'A1'],
  ["I'm running late", 'Estoy llegando tarde', 'time', 'When warning about a delay', 'A2'],
  ["Let's meet at noon", 'Encontrémonos al mediodía', 'time', 'When coordinating a meetup', 'A2'],
  ['I will be there at 5pm', 'Voy a estar ahí a las 5 de la tarde', 'time', 'When confirming a schedule', 'A2'],
  ['It takes about an hour', 'Toma más o menos una hora', 'time', 'When estimating duration', 'A2'],
  ['I wake up at 7 every morning', 'Me despierto a las 7 todas las mañanas', 'time', 'When talking about a routine', 'A2'],
  ['The meeting starts at 3', 'La reunión empieza a las 3', 'time', 'When announcing a schedule', 'A2'],
  ['Hurry up!', '¡Apurate!', 'time', 'When asking someone to hurry', 'A2'],
  ['Take your time', 'Tomate tu tiempo', 'time', 'When giving permission to take your time', 'A2'],
  ['I have plenty of time', 'Tengo mucho tiempo', 'time', 'When expressing availability', 'A2'],
  ["We're out of time", 'Se nos acabó el tiempo', 'time', 'When a deadline ends', 'B1'],
  ['It is 3 o\'clock', 'Son las 3 en punto', 'time', 'When telling the time', 'A1'],
  ['It is half past two', 'Son las dos y media', 'time', 'When telling the time', 'A2'],
  ['It is quarter to four', 'Son las cuatro menos cuarto', 'time', 'When telling the time', 'A2'],
  ['I will see you in an hour', 'Te veo en una hora', 'time', 'When coordinating plans', 'A2'],
  ['The movie starts at 7:30', 'La película empieza a las 7:30', 'time', 'When announcing a schedule', 'A2'],
  ['Can we meet earlier?', '¿Podemos juntarnos más temprano?', 'time', 'When changing a schedule', 'B1'],
  ['I was up all night', 'Estuve despierto toda la noche', 'time', 'When explaining a sleepless night', 'B1'],
  ["Time flies!", '¡El tiempo vuela!', 'time', 'When noticing time passed quickly', 'B1'],
  ["I'll be back in five minutes", 'Vuelvo en cinco minutos', 'time', 'When announcing a brief return', 'A2'],
  ['The store closes at 9', 'La tienda cierra a las 9', 'time', 'When announcing a schedule', 'A2'],
  ['What day is it today?', '¿Qué día es hoy?', 'time', 'When asking what day it is', 'A1'],
  ['It is Monday', 'Es lunes', 'time', 'When saying the day', 'A1'],
  ['My birthday is in June', 'Mi cumpleaños es en junio', 'time', 'When talking about a date', 'A2'],
  ['The concert is next Saturday', 'El concierto es el próximo sábado', 'time', 'When talking about a future event', 'A2'],
  ['We have to leave now', 'Tenemos que irnos ahora', 'time', 'When indicating urgency', 'A2'],
  ['I will be done soon', 'Voy a terminar pronto', 'time', 'When announcing completion', 'A2'],
  ['Wait a moment', 'Esperá un momento', 'time', 'When asking for a brief wait', 'A2'],
  ['Just a second', 'Un segundo', 'time', 'When asking for a minimal wait', 'A2'],
  ['I arrived early', 'Llegué temprano', 'time', 'When indicating punctuality', 'A2'],
  ['I was there on time', 'Llegué a tiempo', 'time', 'When indicating punctuality', 'A2'],
  ['She is always late', 'Ella siempre llega tarde', 'time', 'When commenting on a habit', 'A2'],
  ['The bus is delayed', 'El colectivo está demorado', 'time', 'When reporting a delay', 'B1'],
  ['I need more time', 'Necesito más tiempo', 'time', 'When asking for more time', 'A2'],
  ['What time do you open?', '¿A qué hora abren?', 'time', 'When asking about a schedule', 'A2'],

  // ── weather (35) ─────────────────────────
  ["It's very hot today", 'Hace mucho calor hoy', 'weather', 'When commenting on the weather', 'A2'],
  ['It looks like rain', 'Parece que va a llover', 'weather', 'When looking at the sky', 'A2'],
  ["What's the weather forecast?", '¿Cuál es el pronóstico del tiempo?', 'weather', 'When asking about the forecast', 'B1'],
  ['It is sunny today', 'Hoy está soleado', 'weather', 'When describing the weather', 'A1'],
  ['It is raining', 'Está lloviendo', 'weather', 'When describing the weather', 'A1'],
  ['It is snowing', 'Está nevando', 'weather', 'When describing the weather', 'A2'],
  ['The temperature is dropping', 'La temperatura está bajando', 'weather', 'When commenting on a change', 'B1'],
  ["It's a beautiful day!", '¡Es un día hermoso!', 'weather', 'When appreciating nice weather', 'A2'],
  ['It is windy outside', 'Está ventoso afuera', 'weather', 'When describing the weather', 'A2'],
  ['Do I need a jacket?', '¿Necesito una campera?', 'weather', 'When deciding what to wear', 'A2'],
  ["It's freezing out there!", '¡Está helado afuera!', 'weather', 'When expressing extreme cold', 'B1'],
  ['The sun is shining', 'El sol está brillando', 'weather', 'When describing a sunny day', 'A2'],
  ['It is cloudy', 'Está nublado', 'weather', 'When describing the sky', 'A2'],
  ['There is a storm coming', 'Se viene una tormenta', 'weather', 'When warning about the weather', 'B1'],
  ["I hope it doesn't rain", 'Espero que no llueva', 'weather', 'When expressing a wish', 'A2'],
  ['What is the temperature?', '¿Qué temperatura hace?', 'weather', 'When asking about the temperature', 'B1'],
  ["It's going to be hot tomorrow", 'Va a hacer calor mañana', 'weather', 'When anticipating the weather', 'A2'],
  ['We need an umbrella', 'Necesitamos un paraguas', 'weather', 'When preparing for rain', 'A2'],
  ['The weather is perfect', 'El clima está perfecto', 'weather', 'When expressing satisfaction', 'A2'],
  ['Is it cold outside?', '¿Hace frío afuera?', 'weather', 'When asking about the temperature', 'A2'],
  ['It is foggy this morning', 'Está con neblina esta mañana', 'weather', 'When describing visibility', 'B1'],
  ['The roads are icy', 'Las calles están con hielo', 'weather', 'When warning about a condition', 'B2'],
  ['It hailed last night', 'Cayó granizo anoche', 'weather', 'When recounting a weather event', 'B2'],
  ['Dress warmly, it is cold', 'Abrigate, hace frío', 'weather', 'When giving advice', 'A2'],
  ["It's a bit chilly", 'Está un poco fresco', 'weather', 'When describing mild cold', 'B1'],
  ['There is a heat wave', 'Hay una ola de calor', 'weather', 'When commenting on a weather event', 'B1'],
  ['The humidity is really high', 'La humedad está muy alta', 'weather', 'When describing a feeling', 'B1'],
  ["It's pouring outside!", '¡Está lloviendo a cántaros!', 'weather', 'When describing heavy rain', 'B1'],
  ['There might be a thunderstorm', 'Puede haber tormenta eléctrica', 'weather', 'When anticipating severe weather', 'B1'],
  ['It should clear up later', 'Debería despejarse más tarde', 'weather', 'When anticipating improvement', 'B1'],
  ['We had a lot of rain last week', 'Tuvimos mucha lluvia la semana pasada', 'weather', 'When commenting on past weather', 'B1'],
  ['The sky is clear', 'El cielo está despejado', 'weather', 'When describing the sky', 'B1'],
  ['What a gorgeous sunset!', '¡Qué atardecer hermoso!', 'weather', 'When admiring the scenery', 'B1'],
  ['It feels like 40 degrees!', '¡Se siente como 40 grados!', 'weather', 'When commenting on how the temperature feels', 'B1'],
  ["The weather has been crazy lately", 'El clima estuvo loco últimamente', 'weather', 'When commenting on changes in the weather', 'B1'],

  // ── family (30) ──────────────────────────
  ['I have two brothers', 'Tengo dos hermanos', 'family', 'When talking about your family', 'A1'],
  ['My parents live in...', 'Mis padres viven en...', 'family', 'When talking about your parents', 'A2'],
  ['We are a big family', 'Somos una familia grande', 'family', 'When describing your family', 'A2'],
  ['Do you have any siblings?', '¿Tenés hermanos?', 'family', 'When asking about family', 'A2'],
  ['I am the oldest', 'Soy el/la mayor', 'family', 'When talking about birth order', 'A2'],
  ['Family comes first', 'La familia es primero', 'family', 'When expressing a value', 'B1'],
  ['My sister is a doctor', 'Mi hermana es doctora', 'family', "When talking about a family member's profession", 'A2'],
  ['We have dinner together every Sunday', 'Cenamos juntos todos los domingos', 'family', 'When talking about a tradition', 'B1'],
  ['I have three children', 'Tengo tres hijos', 'family', 'When talking about your children', 'A2'],
  ['My grandparents are from Italy', 'Mis abuelos son de Italia', 'family', 'When talking about origin', 'B1'],
  ['She looks just like her mother', 'Es igualita a su mamá', 'family', 'When commenting on a resemblance', 'B1'],
  ['We got married last year', 'Nos casamos el año pasado', 'family', 'When recounting an event', 'A2'],
  ['My cousin lives in New York', 'Mi primo vive en Nueva York', 'family', 'When talking about relatives', 'B1'],
  ['How is your family?', '¿Cómo está tu familia?', 'family', 'When asking about the family', 'A2'],
  ['I miss my family', 'Extraño a mi familia', 'family', 'When expressing nostalgia', 'A2'],
  ['My brother and I are very close', 'Mi hermano y yo somos muy cercanos', 'family', 'When describing a relationship', 'B1'],
  ['She is the youngest in the family', 'Ella es la menor de la familia', 'family', 'When talking about birth order', 'B1'],
  ['My uncle is visiting us', 'Mi tío nos está visitando', 'family', 'When talking about a visit', 'A2'],
  ['We have a family reunion every year', 'Tenemos una reunión familiar cada año', 'family', 'When talking about a tradition', 'B1'],
  ['My daughter just started school', 'Mi hija acaba de empezar la escuela', 'family', 'When sharing news', 'B1'],
  ['He takes after his father', 'Salió al padre', 'family', 'When commenting on a resemblance', 'B1'],
  ['My mother is a great cook', 'Mi mamá es una gran cocinera', 'family', 'When complimenting a family member', 'B1'],
  ['We are expecting a baby', 'Estamos esperando un bebé', 'family', 'When announcing a pregnancy', 'B1'],
  ['I grew up in a small town', 'Crecí en un pueblo chico', 'family', 'When talking about childhood', 'B1'],
  ['My father taught me how to drive', 'Mi papá me enseñó a manejar', 'family', 'When talking about something you learned', 'B1'],
  ['She is a single mother', 'Ella es madre soltera', 'family', 'When describing a situation', 'B1'],
  ['We adopted a child', 'Adoptamos un hijo', 'family', 'When recounting a family event', 'B2'],
  ['My siblings and I get along well', 'Mis hermanos y yo nos llevamos bien', 'family', 'When describing a relationship', 'B1'],
  ['Family is everything to me', 'La familia lo es todo para mí', 'family', 'When expressing a value', 'B1'],
  ['My parents are divorced', 'Mis padres están divorciados', 'family', 'When talking about a situation', 'B1'],
];

const CATEGORY_IMAGES = {
  greetings: 'https://images.unsplash.com/photo-1573166364524-d9dbfd8bbf83?w=400',
  courtesy: 'https://images.unsplash.com/photo-1573166364524-d9dbfd8bbf83?w=400',
  questions: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400',
  introductions: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  shopping: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400',
  restaurant: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
  travel: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400',
  work: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=400',
  health: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
  directions: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400',
  phone: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
  emotions: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  time: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=400',
  weather: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400',
  family: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
};

// Expand compact data into full phrase objects
export const PHRASES_SEED = PHRASE_DATA.map((row, index) => ({
  phrase_en: row[0],
  phrase_es: row[1],
  category: row[2],
  context: row[3],
  difficulty: row[4],
  image_url: CATEGORY_IMAGES[row[2]] || null,
  audio_url: null,
}));
