// saflash — Phrases seed data (500+ real-world English phrases)
// Format: [phrase_en, phrase_es, category, context, difficulty]

const PHRASE_DATA = [
  // ── greetings (40) ──────────────────────
  ['Hello!', '¡Hola!', 'greetings', 'Al saludar a alguien', 'A1'],
  ['Hi!', '¡Hola!', 'greetings', 'Saludo informal', 'A1'],
  ['Good morning!', '¡Buenos días!', 'greetings', 'Saludo por la mañana', 'A1'],
  ['Good afternoon!', '¡Buenas tardes!', 'greetings', 'Saludo por la tarde', 'A1'],
  ['Good evening!', '¡Buenas noches!', 'greetings', 'Saludo por la noche (al llegar)', 'A1'],
  ['Good night!', '¡Buenas noches!', 'greetings', 'Al despedirse de noche', 'A1'],
  ['How are you?', '¿Cómo estás?', 'greetings', 'Al saludar a alguien conocido', 'A1'],
  ["How's it going?", '¿Cómo va todo?', 'greetings', 'Saludo informal entre amigos', 'A1'],
  ['How are you doing?', '¿Cómo te va?', 'greetings', 'Saludo casual', 'A1'],
  ["What's up?", '¿Qué tal?', 'greetings', 'Saludo muy informal', 'A2'],
  ['Nice to meet you!', '¡Mucho gusto!', 'greetings', 'Al conocer a alguien', 'A1'],
  ['Pleased to meet you!', '¡Encantado de conocerte!', 'greetings', 'Al conocer a alguien formalmente', 'A2'],
  ['Long time no see!', '¡Cuánto tiempo sin verte!', 'greetings', 'Al reencontrarse con alguien', 'B1'],
  ["It's been a while!", '¡Ha pasado un tiempo!', 'greetings', 'Al reencontrarse', 'B1'],
  ['See you later!', '¡Nos vemos luego!', 'greetings', 'Al despedirse', 'A1'],
  ['See you soon!', '¡Nos vemos pronto!', 'greetings', 'Al despedirse con expectativa de reencuentro', 'A1'],
  ['See you tomorrow!', '¡Nos vemos mañana!', 'greetings', 'Al despedirse', 'A1'],
  ['Take care!', '¡Cuídate!', 'greetings', 'Al despedirse de alguien cercano', 'A2'],
  ['Have a nice day!', '¡Que tengas un buen día!', 'greetings', 'Al despedirse', 'A1'],
  ['Have a good weekend!', '¡Buen fin de semana!', 'greetings', 'Despedida de viernes', 'A1'],
  ['Welcome!', '¡Bienvenido!', 'greetings', 'Al recibir a alguien', 'A1'],
  ['Welcome back!', '¡Bienvenido de vuelta!', 'greetings', 'Cuando alguien regresa', 'A2'],
  ["How have you been?", '¿Cómo has estado?', 'greetings', 'Al reencontrarse después de tiempo', 'A2'],
  ["What's new?", '¿Qué hay de nuevo?', 'greetings', 'Para iniciar conversación', 'A2'],
  ["Good to see you!", '¡Qué bueno verte!', 'greetings', 'Al encontrar a alguien', 'A2'],
  ['Hey there!', '¡Eh, hola!', 'greetings', 'Saludo muy casual', 'A2'],
  ['Morning!', '¡Buen día!', 'greetings', 'Saludo abreviado de mañana', 'A1'],
  ['Afternoon!', '¡Buenas tardes!', 'greetings', 'Saludo abreviado de tarde', 'A1'],
  ['Evening!', '¡Buenas noches!', 'greetings', 'Saludo abreviado de noche', 'A1'],
  ["How's your day going?", '¿Cómo va tu día?', 'greetings', 'Para preguntar sobre el día', 'A2'],
  ['Goodbye!', '¡Adiós!', 'greetings', 'Despedida formal', 'A1'],
  ['Bye!', '¡Chau! / ¡Adiós!', 'greetings', 'Despedida informal', 'A1'],
  ['Bye bye!', '¡Adiós adiós!', 'greetings', 'Despedida cariñosa', 'A1'],
  ['Farewell!', '¡Hasta siempre!', 'greetings', 'Despedida formal o definitiva', 'B2'],
  ['Until next time!', '¡Hasta la próxima!', 'greetings', 'Despedida con intención de reencuentro', 'B1'],
  ['Catch you later!', '¡Te veo después!', 'greetings', 'Despedida muy informal', 'B1'],
  ['Have a safe trip!', '¡Buen viaje!', 'greetings', 'Al despedir a alguien que viaja', 'A2'],
  ['Talk to you soon!', '¡Hablamos pronto!', 'greetings', 'Al despedirse por teléfono', 'A2'],
  ['Lovely to meet you!', '¡Un placer conocerte!', 'greetings', 'Al conocer a alguien con entusiasmo', 'B1'],
  ['Greetings!', '¡Saludos!', 'greetings', 'Saludo formal o por escrito', 'B1'],

  // ── courtesy (30) ────────────────────────
  ['Please', 'Por favor', 'courtesy', 'Al pedir algo', 'A1'],
  ['Thank you', 'Gracias', 'courtesy', 'Al agradecer', 'A1'],
  ['Thanks', 'Gracias', 'courtesy', 'Agradecimiento informal', 'A1'],
  ['Thank you very much', 'Muchas gracias', 'courtesy', 'Agradecimiento enfático', 'A1'],
  ['Thanks a lot!', '¡Muchísimas gracias!', 'courtesy', 'Agradecimiento muy enfático', 'A2'],
  ["You're welcome", 'De nada', 'courtesy', 'Al responder a un agradecimiento', 'A1'],
  ['No problem', 'No hay problema', 'courtesy', 'Respuesta casual a gracias', 'A2'],
  ["Don't mention it", 'Ni lo menciones', 'courtesy', 'Respuesta a agradecimiento', 'B1'],
  ['My pleasure', 'Es un placer', 'courtesy', 'Respuesta formal a agradecimiento', 'B1'],
  ['Excuse me', 'Disculpe / Permiso', 'courtesy', 'Al interrumpir o pedir paso', 'A1'],
  ["I'm sorry", 'Lo siento', 'courtesy', 'Al disculparse', 'A1'],
  ['Sorry', 'Perdón', 'courtesy', 'Disculpa informal', 'A1'],
  ['I apologize', 'Me disculpo', 'courtesy', 'Disculpa formal', 'B1'],
  ['Forgive me', 'Perdóname', 'courtesy', 'Al pedir perdón', 'B1'],
  ['Pardon me', 'Perdón / Disculpe', 'courtesy', 'Al interrumpir educadamente', 'B1'],
  ['May I?', '¿Puedo?', 'courtesy', 'Al pedir permiso', 'A2'],
  ['After you', 'Después de usted', 'courtesy', 'Al ceder el paso', 'A2'],
  ['Go ahead', 'Adelante', 'courtesy', 'Al dar paso o permiso', 'A2'],
  ['Bless you', 'Salud', 'courtesy', 'Cuando alguien estornuda', 'A2'],
  ['Cheers!', '¡Salud!', 'courtesy', 'Al brindar', 'A2'],
  ['Congratulations!', '¡Felicitaciones!', 'courtesy', 'Al felicitar por un logro', 'A2'],
  ['Well done!', '¡Bien hecho!', 'courtesy', 'Al felicitar por un trabajo', 'A2'],
  ['Good luck!', '¡Buena suerte!', 'courtesy', 'Al desear éxito', 'A1'],
  ['All the best!', '¡Todo lo mejor!', 'courtesy', 'Al despedirse deseando bien', 'B1'],
  ['Best wishes!', '¡Mis mejores deseos!', 'courtesy', 'Al felicitar o despedir por escrito', 'B1'],
  ['Happy birthday!', '¡Feliz cumpleaños!', 'courtesy', 'Al felicitar en un cumpleaños', 'A1'],
  ['Merry Christmas!', '¡Feliz Navidad!', 'courtesy', 'Saludo navideño', 'A1'],
  ['Happy New Year!', '¡Feliz Año Nuevo!', 'courtesy', 'Saludo de año nuevo', 'A1'],
  ['Get well soon!', '¡Que te mejores pronto!', 'courtesy', 'A alguien enfermo', 'A2'],
  ['My apologies', 'Mis disculpas', 'courtesy', 'Disculpa formal', 'B1'],

  // ── questions (35) ───────────────────────
  ['What time is it?', '¿Qué hora es?', 'questions', 'Al preguntar la hora', 'A1'],
  ['Where is the bathroom?', '¿Dónde está el baño?', 'questions', 'Al buscar el baño', 'A1'],
  ['How much does it cost?', '¿Cuánto cuesta?', 'questions', 'Al preguntar un precio', 'A1'],
  ['What is your name?', '¿Cómo te llamás?', 'questions', 'Al preguntar el nombre', 'A1'],
  ['Where are you from?', '¿De dónde sos?', 'questions', 'Al preguntar origen', 'A1'],
  ['How old are you?', '¿Cuántos años tenés?', 'questions', 'Al preguntar la edad', 'A1'],
  ['What do you do?', '¿A qué te dedicás?', 'questions', 'Al preguntar por el trabajo', 'A2'],
  ['Do you speak English?', '¿Hablas inglés?', 'questions', 'Al preguntar por idiomas', 'A1'],
  ['Can you help me?', '¿Me podés ayudar?', 'questions', 'Al pedir ayuda', 'A1'],
  ['Where do you live?', '¿Dónde vivís?', 'questions', 'Al preguntar residencia', 'A1'],
  ['What is this?', '¿Qué es esto?', 'questions', 'Al preguntar por un objeto', 'A1'],
  ['What does that mean?', '¿Qué significa eso?', 'questions', 'Al preguntar significado', 'A2'],
  ['How do you say... in English?', '¿Cómo se dice... en inglés?', 'questions', 'Al aprender vocabulario', 'A2'],
  ['Could you repeat that?', '¿Podrías repetir eso?', 'questions', 'Al no entender algo', 'A2'],
  ['Can you speak more slowly?', '¿Podés hablar más despacio?', 'questions', 'Al pedir claridad', 'A2'],
  ['What happened?', '¿Qué pasó?', 'questions', 'Al preguntar sobre un evento', 'A2'],
  ["What's wrong?", '¿Qué pasa? / ¿Qué anda mal?', 'questions', 'Al notar que alguien está mal', 'A2'],
  ['Are you okay?', '¿Estás bien?', 'questions', 'Al preocuparse por alguien', 'A2'],
  ['How was your day?', '¿Cómo estuvo tu día?', 'questions', 'Al preguntar sobre el día', 'A2'],
  ["What's the weather like?", '¿Cómo está el clima?', 'questions', 'Al preguntar el clima', 'A2'],
  ['Where can I find...?', '¿Dónde puedo encontrar...?', 'questions', 'Al buscar algo específico', 'A2'],
  ['How long does it take?', '¿Cuánto tiempo toma?', 'questions', 'Al preguntar duración', 'A2'],
  ['Is it far from here?', '¿Está lejos de aquí?', 'questions', 'Al preguntar distancia', 'A2'],
  ['What do you recommend?', '¿Qué recomiendas?', 'questions', 'Al pedir consejo', 'A2'],
  ['Do you have...?', '¿Tenés...?', 'questions', 'Al preguntar disponibilidad', 'A1'],
  ['Would you like something to drink?', '¿Te gustaría algo para tomar?', 'questions', 'Al ofrecer bebida', 'A2'],
  ['Are you free tonight?', '¿Estás libre esta noche?', 'questions', 'Al invitar a alguien', 'A2'],
  ['What do you think?', '¿Qué pensás?', 'questions', 'Al pedir opinión', 'A2'],
  ['How do you feel?', '¿Cómo te sentís?', 'questions', 'Al preguntar estado de ánimo', 'A2'],
  ['Where did you go?', '¿A dónde fuiste?', 'questions', 'Al preguntar sobre un viaje', 'A2'],
  ['When does it start?', '¿Cuándo empieza?', 'questions', 'Al preguntar horario', 'A2'],
  ['Who is that?', '¿Quién es?', 'questions', 'Al preguntar por una persona', 'A1'],
  ['Why is that?', '¿Por qué es eso?', 'questions', 'Al preguntar razón', 'A2'],
  ['Which one is yours?', '¿Cuál es el tuyo?', 'questions', 'Al identificar pertenencia', 'A2'],
  ['How many people are coming?', '¿Cuántas personas vienen?', 'questions', 'Al organizar un evento', 'B1'],

  // ── introductions (30) ──────────────────
  ['My name is John', 'Me llamo John', 'introductions', 'Al presentarse', 'A1'],
  ["I'm from Spain", 'Soy de España', 'introductions', 'Al decir tu origen', 'A1'],
  ['I live in Madrid', 'Vivo en Madrid', 'introductions', 'Al decir dónde vivís', 'A2'],
  ['I am a student', 'Soy estudiante', 'introductions', 'Al hablar de tu ocupación', 'A1'],
  ['I work in a hospital', 'Trabajo en un hospital', 'introductions', 'Al hablar de tu trabajo', 'A2'],
  ['I am a teacher', 'Soy profesor/a', 'introductions', 'Al decir tu profesión', 'A1'],
  ['I study English', 'Estudio inglés', 'introductions', 'Al hablar de tus estudios', 'A1'],
  ["I'm learning Spanish", 'Estoy aprendiendo español', 'introductions', 'Al hablar del idioma que aprendés', 'A2'],
  ['I have two children', 'Tengo dos hijos', 'introductions', 'Al hablar de tu familia', 'A2'],
  ["I'm married", 'Estoy casado/a', 'introductions', 'Al hablar de estado civil', 'A2'],
  ['I like reading', 'Me gusta leer', 'introductions', 'Al hablar de hobbies', 'A2'],
  ['I enjoy cooking', 'Disfruto cocinar', 'introductions', 'Al hablar de pasatiempos', 'A2'],
  ['I play the guitar', 'Toco la guitarra', 'introductions', 'Al hablar de habilidades', 'A2'],
  ['I love traveling', 'Me encanta viajar', 'introductions', 'Al hablar de intereses', 'A2'],
  ['I was born in 1990', 'Nací en 1990', 'introductions', 'Al decir tu año de nacimiento', 'A2'],
  ['I have a dog', 'Tengo un perro', 'introductions', 'Al hablar de mascotas', 'A1'],
  ['I moved here last year', 'Me mudé aquí el año pasado', 'introductions', 'Al explicar tu llegada', 'B1'],
  ["I'm an engineer", 'Soy ingeniero/a', 'introductions', 'Al decir tu profesión', 'B1'],
  ['I work from home', 'Trabajo desde casa', 'introductions', 'Al hablar de la modalidad laboral', 'B1'],
  ["I'm here on vacation", 'Estoy aquí de vacaciones', 'introductions', 'Al explicar el motivo de tu visita', 'A2'],
  ["I'm visiting family", 'Estoy visitando a mi familia', 'introductions', 'Al explicar visita', 'A2'],
  ['I come here often', 'Vengo aquí seguido', 'introductions', 'Al hablar de frecuencia', 'A2'],
  ['Let me introduce myself', 'Permitime presentarme', 'introductions', 'Al iniciar una presentación formal', 'B1'],
  ['This is my friend Maria', 'Esta es mi amiga Maria', 'introductions', 'Al presentar a alguien', 'A2'],
  ['I would like you to meet...', 'Me gustaría presentarte a...', 'introductions', 'Al presentar formalmente', 'B1'],
  ['We work together', 'Trabajamos juntos', 'introductions', 'Al explicar relación laboral', 'A2'],
  ["I've heard a lot about you", 'He escuchado mucho sobre vos', 'introductions', 'Al conocer a alguien famoso', 'B1'],
  ['Nice to finally meet you', 'Qué bueno conocerte por fin', 'introductions', 'Al conocer en persona a alguien', 'B1'],
  ["I don't think we've met", 'Creo que no nos conocemos', 'introductions', 'Al acercarte a alguien nuevo', 'B1'],
  ['Tell me about yourself', 'Contame sobre vos', 'introductions', 'Al pedir que alguien se presente', 'A2'],

  // ── shopping (35) ────────────────────────
  ['How much is this?', '¿Cuánto cuesta esto?', 'shopping', 'Al preguntar precio en una tienda', 'A1'],
  ['Do you have this in my size?', '¿Tenés esto en mi talle?', 'shopping', 'Al buscar ropa', 'A2'],
  ['I would like to pay by card', 'Quisiera pagar con tarjeta', 'shopping', 'Al momento de pagar', 'A2'],
  ['Can I try this on?', '¿Me puedo probar esto?', 'shopping', 'Al probar ropa', 'A2'],
  ['Where is the fitting room?', '¿Dónde está el probador?', 'shopping', 'Al buscar dónde probarse ropa', 'A2'],
  ["I'm just looking, thanks", 'Solo estoy mirando, gracias', 'shopping', 'Al rechazar ayuda del vendedor', 'A2'],
  ['Do you have a smaller size?', '¿Tenés un talle más chico?', 'shopping', 'Al pedir otro talle', 'A2'],
  ['Do you have this in another color?', '¿Tenés esto en otro color?', 'shopping', 'Al buscar variedad', 'A2'],
  ['Where can I pay?', '¿Dónde puedo pagar?', 'shopping', 'Al buscar la caja', 'A2'],
  ['Can I get a receipt?', '¿Me podés dar un recibo?', 'shopping', 'Al pedir comprobante', 'B1'],
  ['Is there a discount?', '¿Hay descuento?', 'shopping', 'Al preguntar por ofertas', 'A2'],
  ['How much is the total?', '¿Cuánto es el total?', 'shopping', 'Al saber el precio final', 'A2'],
  ["I'll take it", 'Me lo llevo', 'shopping', 'Al decidir comprar', 'A2'],
  ["It's too expensive", 'Es demasiado caro', 'shopping', 'Al considerar que algo es caro', 'A2'],
  ['Do you accept credit cards?', '¿Aceptan tarjetas de crédito?', 'shopping', 'Al preguntar forma de pago', 'B1'],
  ['Can I return this?', '¿Puedo devolver esto?', 'shopping', 'Al querer devolver un producto', 'B1'],
  ['Is this on sale?', '¿Está en oferta?', 'shopping', 'Al preguntar si hay descuento', 'A2'],
  ['Where is the shoe section?', '¿Dónde está la sección de zapatos?', 'shopping', 'Al buscar sección específica', 'A2'],
  ['What time do you close?', '¿A qué hora cierran?', 'shopping', 'Al preguntar horario', 'A2'],
  ['Do you have a bag?', '¿Tenés una bolsa?', 'shopping', 'Al necesitar bolsa', 'A2'],
  ["I'm looking for a gift", 'Estoy buscando un regalo', 'shopping', 'Al buscar algo para regalar', 'B1'],
  ['Can you gift wrap it?', '¿Lo pueden envolver para regalo?', 'shopping', 'Al pedir envoltura', 'B1'],
  ['Is this the final price?', '¿Este es el precio final?', 'shopping', 'Al confirmar precio', 'B1'],
  ['Can I have a refund?', '¿Me pueden hacer un reembolso?', 'shopping', 'Al pedir devolución de dinero', 'B1'],
  ["It doesn't fit me", 'No me queda bien', 'shopping', 'Al probarse ropa que no es del talle', 'A2'],
  ['Where are the fitting rooms?', '¿Dónde están los probadores?', 'shopping', 'Al buscar probadores', 'A2'],
  ['I need a larger size', 'Necesito un talle más grande', 'shopping', 'Al pedir talle mayor', 'A2'],
  ['This is broken', 'Esto está roto', 'shopping', 'Al encontrar un producto dañado', 'A2'],
  ['Can I exchange this?', '¿Puedo cambiar esto?', 'shopping', 'Al querer cambiar un producto', 'B1'],
  ['How long is the warranty?', '¿Cuánto dura la garantía?', 'shopping', 'Al preguntar garantía', 'B1'],
  ['I paid in cash', 'Pagué en efectivo', 'shopping', 'Al decir cómo pagaste', 'A2'],
  ['Keep the change', 'Quedate con el cambio', 'shopping', 'Al dejar propina o vuelto', 'A2'],
  ['Are you open on Sundays?', '¿Abren los domingos?', 'shopping', 'Al preguntar horarios', 'A2'],
  ['Where can I find...?', '¿Dónde puedo encontrar...?', 'shopping', 'Al buscar producto específico', 'A2'],
  ['Do you sell...?', '¿Venden...?', 'shopping', 'Al preguntar si venden algo', 'A2'],

  // ── restaurant (40) ─────────────────────
  ['I would like a table for two', 'Quisiera una mesa para dos', 'restaurant', 'Al llegar a un restaurante', 'A2'],
  ['What do you recommend?', '¿Qué recomiendas?', 'restaurant', 'Al pedir sugerencia al mozo', 'A2'],
  ['The check, please', 'La cuenta, por favor', 'restaurant', 'Al pedir la cuenta', 'A2'],
  ['Can I see the menu?', '¿Me podés mostrar el menú?', 'restaurant', 'Al pedir el menú', 'A2'],
  ["I'm ready to order", 'Estoy listo para pedir', 'restaurant', 'Al momento de ordenar', 'A2'],
  ['What are today\'s specials?', '¿Cuáles son los especiales del día?', 'restaurant', 'Al preguntar por platos del día', 'B1'],
  ['I have a reservation', 'Tengo una reserva', 'restaurant', 'Al llegar con reserva', 'B1'],
  ['Do you have vegetarian options?', '¿Tienen opciones vegetarianas?', 'restaurant', 'Al preguntar por comida vegetariana', 'B1'],
  ['Can I have some water please?', '¿Me podés dar agua por favor?', 'restaurant', 'Al pedir agua', 'A2'],
  ["I'll have the same", 'Voy a pedir lo mismo', 'restaurant', 'Al pedir igual que otra persona', 'A2'],
  ['Is the tip included?', '¿La propina está incluida?', 'restaurant', 'Al preguntar por el servicio', 'B1'],
  ['This is delicious!', '¡Está delicioso!', 'restaurant', 'Al disfrutar la comida', 'A2'],
  ['I am allergic to nuts', 'Soy alérgico a las nueces', 'restaurant', 'Al informar alergia', 'B1'],
  ['Can we sit by the window?', '¿Podemos sentarnos junto a la ventana?', 'restaurant', 'Al elegir ubicación', 'B1'],
  ['Could I have a fork please?', '¿Me podrías dar un tenedor por favor?', 'restaurant', 'Al pedir cubierto', 'A2'],
  ['What do you have for dessert?', '¿Qué tienen de postre?', 'restaurant', 'Al preguntar por postres', 'A2'],
  ['Can I get a refill?', '¿Me pueden servir más?', 'restaurant', 'Al pedir recarga de bebida', 'B1'],
  ['The food is cold', 'La comida está fría', 'restaurant', 'Al quejarse de la temperatura', 'A2'],
  ['Can you make it spicy?', '¿Lo pueden hacer picante?', 'restaurant', 'Al pedir comida picante', 'B1'],
  ['Is this dish gluten-free?', '¿Este plato es sin gluten?', 'restaurant', 'Al preguntar por restricciones', 'B1'],
  ['I would like to make a reservation', 'Quisiera hacer una reserva', 'restaurant', 'Al reservar por teléfono', 'B1'],
  ['How long is the wait?', '¿Cuánto hay que esperar?', 'restaurant', 'Al preguntar tiempo de espera', 'B1'],
  ['Can we have separate checks?', '¿Podemos tener cuentas separadas?', 'restaurant', 'Al pedir dividir la cuenta', 'B2'],
  ['Do you serve breakfast all day?', '¿Sirven desayuno todo el día?', 'restaurant', 'Al preguntar por horarios', 'B1'],
  ['Could I have a napkin?', '¿Me podrías dar una servilleta?', 'restaurant', 'Al pedir servilleta', 'A2'],
  ['What kind of dressing do you have?', '¿Qué tipo de aderezo tienen?', 'restaurant', 'Al preguntar por aderezos', 'B1'],
  ['Can I have it to go?', '¿Me lo pueden dar para llevar?', 'restaurant', 'Al pedir comida para llevar', 'A2'],
  ['Is there a kids\' menu?', '¿Hay menú infantil?', 'restaurant', 'Al preguntar por menú para niños', 'B1'],
  ['A table for four, please', 'Una mesa para cuatro, por favor', 'restaurant', 'Al pedir mesa', 'A2'],
  ['Can I have some bread?', '¿Me pueden dar pan?', 'restaurant', 'Al pedir pan', 'A2'],
  ['Are you still serving?', '¿Todavía están sirviendo?', 'restaurant', 'Al llegar cerca del cierre', 'B1'],
  ['Well done, please', 'Bien cocido, por favor', 'restaurant', 'Al pedir el término de la carne', 'B1'],
  ['Medium rare, please', 'Término medio, por favor', 'restaurant', 'Al pedir el punto de la carne', 'B1'],
  ['Just water for me', 'Solo agua para mí', 'restaurant', 'Al pedir solo agua', 'A2'],
  ['Can I have some salt?', '¿Me podés dar sal?', 'restaurant', 'Al pedir sal', 'A2'],
  ['Could we have more napkins?', '¿Podrían traernos más servilletas?', 'restaurant', 'Al pedir más servilletas', 'A2'],
  ['Do you have any specials tonight?', '¿Tienen especiales esta noche?', 'restaurant', 'Al preguntar por platos especiales', 'B1'],
  ['That was excellent, thank you!', 'Estuvo excelente, ¡gracias!', 'restaurant', 'Al terminar la comida', 'A2'],
  ['Can I have the bill please?', '¿Me puede dar la cuenta por favor?', 'restaurant', 'Al pedir la cuenta', 'A2'],
  ['We would like to order now', 'Quisiéramos ordenar ahora', 'restaurant', 'Al llamar al mozo', 'B1'],

  // ── travel (40) ──────────────────────────
  ['Where is the nearest hotel?', '¿Dónde está el hotel más cercano?', 'travel', 'Al buscar alojamiento', 'A2'],
  ['I need a taxi', 'Necesito un taxi', 'travel', 'Al pedir transporte', 'A2'],
  ['My flight is at 8am', 'Mi vuelo es a las 8 de la mañana', 'travel', 'Al hablar de horario de vuelo', 'A2'],
  ['I lost my passport', 'Perdí mi pasaporte', 'travel', 'En una emergencia de viaje', 'B1'],
  ['Where is the bus station?', '¿Dónde está la estación de buses?', 'travel', 'Al buscar transporte', 'A2'],
  ['How do I get to the airport?', '¿Cómo llego al aeropuerto?', 'travel', 'Al buscar dirección', 'A2'],
  ['Can I have a map?', '¿Me podés dar un mapa?', 'travel', 'Al pedir orientación', 'A2'],
  ['I have a reservation', 'Tengo una reserva', 'travel', 'Al llegar al hotel', 'B1'],
  ['What time is checkout?', '¿A qué hora es la salida?', 'travel', 'Al preguntar en el hotel', 'B1'],
  ['Is breakfast included?', '¿El desayuno está incluido?', 'travel', 'Al preguntar en el hotel', 'A2'],
  ['Can you call a taxi for me?', '¿Me podés llamar un taxi?', 'travel', 'Al pedir ayuda en el hotel', 'A2'],
  ['I would like a round-trip ticket', 'Quisiera un boleto de ida y vuelta', 'travel', 'Al comprar pasajes', 'B1'],
  ['How long is the flight?', '¿Cuánto dura el vuelo?', 'travel', 'Al preguntar duración', 'A2'],
  ['Is there a direct flight?', '¿Hay vuelo directo?', 'travel', 'Al buscar vuelos', 'B1'],
  ['Where is the train station?', '¿Dónde está la estación de tren?', 'travel', 'Al buscar estación', 'A2'],
  ['How much is a ticket to London?', '¿Cuánto cuesta un boleto a Londres?', 'travel', 'Al comprar pasaje', 'A2'],
  ['Is this seat taken?', '¿Está ocupado este asiento?', 'travel', 'Al buscar asiento', 'A2'],
  ['I missed my flight', 'Perdí mi vuelo', 'travel', 'En una emergencia de viaje', 'B1'],
  ['Can I change my reservation?', '¿Puedo cambiar mi reserva?', 'travel', 'Al modificar planes', 'B1'],
  ['Where can I exchange money?', '¿Dónde puedo cambiar dinero?', 'travel', 'Al buscar cambio de moneda', 'B1'],
  ['Do you have a single room?', '¿Tenés una habitación individual?', 'travel', 'Al reservar hotel', 'A2'],
  ['Can I see the room?', '¿Puedo ver la habitación?', 'travel', 'Al evaluar alojamiento', 'B1'],
  ['The air conditioning doesn\'t work', 'El aire acondicionado no funciona', 'travel', 'Al quejarse en el hotel', 'B1'],
  ['Can I have an extra towel?', '¿Me podés dar una toalla extra?', 'travel', 'Al pedir en el hotel', 'A2'],
  ['I need a wake-up call', 'Necesito una llamada de despertador', 'travel', 'Al pedir servicio en el hotel', 'B1'],
  ['Where is the nearest bus stop?', '¿Dónde está la parada de bus más cercana?', 'travel', 'Al buscar transporte público', 'A2'],
  ['What terminal is my flight?', '¿En qué terminal sale mi vuelo?', 'travel', 'Al orientarse en el aeropuerto', 'B1'],
  ['Has my flight been delayed?', '¿Mi vuelo fue demorado?', 'travel', 'Al verificar estado', 'B1'],
  ['I need to check in', 'Necesito hacer el check-in', 'travel', 'Al llegar al hotel o aeropuerto', 'A2'],
  ['Can I have a window seat?', '¿Puedo tener un asiento en ventanilla?', 'travel', 'Al elegir asiento', 'B1'],
  ['My luggage is missing', 'Perdieron mi equipaje', 'travel', 'Al reportar equipaje perdido', 'B1'],
  ['How far is the hotel from the airport?', '¿Qué tan lejos está el hotel del aeropuerto?', 'travel', 'Al planificar traslado', 'B1'],
  ['I would like to book a tour', 'Quisiera reservar un tour', 'travel', 'Al contratar excursión', 'B1'],
  ['Is there free Wi-Fi?', '¿Hay Wi-Fi gratis?', 'travel', 'Al preguntar en el hotel', 'A2'],
  ['How do I get to the city center?', '¿Cómo llego al centro?', 'travel', 'Al orientarse en una ciudad', 'A2'],
  ['Can you help me with my bags?', '¿Me podés ayudar con las valijas?', 'travel', 'Al pedir ayuda con equipaje', 'A2'],
  ['Do I need a visa?', '¿Necesito visa?', 'travel', 'Al planificar viaje internacional', 'B1'],
  ['What is the local currency?', '¿Cuál es la moneda local?', 'travel', 'Al informarse del destino', 'B1'],
  ['Is it safe to walk at night?', '¿Es seguro caminar de noche?', 'travel', 'Al preguntar por seguridad', 'B1'],
  ['Where can I buy a SIM card?', '¿Dónde puedo comprar un chip de teléfono?', 'travel', 'Al necesitar teléfono', 'B1'],

  // ── work (35) ────────────────────────────
  ['I have a meeting at 3pm', 'Tengo una reunión a las 3 de la tarde', 'work', 'Al hablar de agenda', 'A2'],
  ['Can you send me the report?', '¿Me podés enviar el informe?', 'work', 'Al pedir documento', 'A2'],
  ["I'm on vacation next week", 'Estoy de vacaciones la semana que viene', 'work', 'Al informar ausencia', 'A2'],
  ['What time does the meeting start?', '¿A qué hora empieza la reunión?', 'work', 'Al preguntar horario', 'A2'],
  ['I need to finish this by Friday', 'Necesito terminar esto para el viernes', 'work', 'Al hablar de fechas límite', 'B1'],
  ['Could you help me with this?', '¿Me podrías ayudar con esto?', 'work', 'Al pedir ayuda', 'A2'],
  ['Let me check my calendar', 'Dejame revisar mi calendario', 'work', 'Al verificar disponibilidad', 'B1'],
  ["I'll get back to you", 'Te respondo después', 'work', 'Al posponer respuesta', 'B1'],
  ['Can we reschedule?', '¿Podemos reprogramar?', 'work', 'Al cambiar una cita', 'B1'],
  ['Please send me the details', 'Por favor enviame los detalles', 'work', 'Al pedir información', 'B1'],
  ['The deadline is Monday', 'La fecha límite es el lunes', 'work', 'Al recordar entrega', 'B1'],
  ["I'm working from home today", 'Hoy trabajo desde casa', 'work', 'Al informar modalidad', 'B1'],
  ['Can I have a day off?', '¿Me puedo tomar un día libre?', 'work', 'Al pedir permiso', 'B1'],
  ['We need to discuss this', 'Tenemos que hablar de esto', 'work', 'Al iniciar conversación seria', 'B1'],
  ['Great job on the presentation!', '¡Buen trabajo en la presentación!', 'work', 'Al felicitar a un colega', 'B1'],
  ['I have a deadline coming up', 'Se me viene una fecha límite', 'work', 'Al hablar de presión laboral', 'B1'],
  ["Let's schedule a call", 'Coordinemos una llamada', 'work', 'Al proponer reunión virtual', 'B1'],
  ['Can you cover for me?', '¿Me podés cubrir?', 'work', 'Al pedir reemplazo', 'B1'],
  ["I'll be in a meeting all afternoon", 'Voy a estar en reunión toda la tarde', 'work', 'Al informar disponibilidad', 'B1'],
  ['Please review this document', 'Por favor revisá este documento', 'work', 'Al pedir revisión', 'B1'],
  ['I need an extension on this', 'Necesito una extensión para esto', 'work', 'Al pedir más tiempo', 'B1'],
  ['The client is waiting for our response', 'El cliente está esperando nuestra respuesta', 'work', 'Al priorizar tarea', 'B1'],
  ['Could you clarify what you mean?', '¿Podrías aclarar a qué te referís?', 'work', 'Al pedir claridad', 'B1'],
  ["Let's touch base tomorrow", 'Charlemos mañana para ver cómo va', 'work', 'Al proponer seguimiento', 'B2'],
  ['I need to run this by my manager', 'Tengo que consultarlo con mi jefe', 'work', 'Al necesitar aprobación', 'B2'],
  ['Do you have a moment to talk?', '¿Tenés un momento para hablar?', 'work', 'Al pedir reunión breve', 'A2'],
  ["I'm on a tight schedule", 'Tengo una agenda ajustada', 'work', 'Al explicar limitación de tiempo', 'B1'],
  ['Can we move the meeting to 2pm?', '¿Podemos mover la reunión a las 2?', 'work', 'Al cambiar horario', 'B1'],
  ['Please CC me on that email', 'Por favor poneme en copia en ese correo', 'work', 'Al pedir ser incluido en comunicaciones', 'B1'],
  ["I'll take care of it", 'Yo me encargo', 'work', 'Al asumir responsabilidad', 'B1'],
  ['The project is on track', 'El proyecto va bien encaminado', 'work', 'Al reportar estado', 'B1'],
  ["Let's circle back to that later", 'Volvamos a eso más tarde', 'work', 'Al posponer discusión', 'B2'],
  ['We have a tight deadline', 'Tenemos una fecha límite ajustada', 'work', 'Al hablar de presión', 'B1'],
  ["I'll send you the minutes", 'Te envío las notas de la reunión', 'work', 'Al comprometerse a enviar resumen', 'B1'],
  ['I need to prepare for the presentation', 'Necesito preparar la presentación', 'work', 'Al planificar trabajo', 'B1'],

  // ── health (30) ─────────────────────────
  ["I don't feel well", 'No me siento bien', 'health', 'Al sentirte mal', 'A2'],
  ['I have a headache', 'Tengo dolor de cabeza', 'health', 'Al describir síntoma', 'A2'],
  ['I need to see a doctor', 'Necesito ver a un médico', 'health', 'Al buscar atención médica', 'A2'],
  ['Where is the nearest hospital?', '¿Dónde está el hospital más cercano?', 'health', 'En emergencia', 'A2'],
  ['I have a stomachache', 'Me duele el estómago', 'health', 'Al describir dolor', 'A2'],
  ['I feel dizzy', 'Me siento mareado', 'health', 'Al describir síntoma', 'B1'],
  ['I twisted my ankle', 'Me torcí el tobillo', 'health', 'Al describir lesión', 'B1'],
  ['Can you call an ambulance?', '¿Podés llamar a una ambulancia?', 'health', 'En emergencia grave', 'B1'],
  ['I need a prescription', 'Necesito una receta', 'health', 'Al pedir medicación', 'B1'],
  ['Are you allergic to any medication?', '¿Sos alérgico a algún medicamento?', 'health', 'Pregunta médica', 'B1'],
  ['I have a fever', 'Tengo fiebre', 'health', 'Al describir síntoma', 'A2'],
  ['My throat hurts', 'Me duele la garganta', 'health', 'Al describir dolor', 'A2'],
  ['I have a runny nose', 'Tengo la nariz que me gotea', 'health', 'Al describir síntoma de resfrío', 'B1'],
  ['I feel nauseous', 'Siento náuseas', 'health', 'Al describir malestar', 'B1'],
  ['How long have you had these symptoms?', '¿Hace cuánto tenés estos síntomas?', 'health', 'Pregunta médica', 'B1'],
  ['I need to make an appointment', 'Necesito hacer una cita', 'health', 'Al pedir turno médico', 'B1'],
  ['Do you have insurance?', '¿Tenés seguro médico?', 'health', 'Pregunta administrativa', 'B1'],
  ['Take this medicine twice a day', 'Tomá esta medicina dos veces al día', 'health', 'Instrucción médica', 'B1'],
  ['I have a sore throat', 'Tengo dolor de garganta', 'health', 'Al describir síntoma', 'A2'],
  ['I need some painkillers', 'Necesito analgésicos', 'health', 'Al pedir medicina', 'B1'],
  ['My back hurts', 'Me duele la espalda', 'health', 'Al describir dolor', 'A2'],
  ['I feel much better now', 'Me siento mucho mejor ahora', 'health', 'Al reportar mejoría', 'A2'],
  ['You should get some rest', 'Deberías descansar', 'health', 'Al dar consejo', 'A2'],
  ['I have a toothache', 'Tengo dolor de muelas', 'health', 'Al describir dolor dental', 'B1'],
  ['I need to see a dentist', 'Necesito ver a un dentista', 'health', 'Al buscar atención dental', 'B1'],
  ['Stay hydrated', 'Mantenete hidratado', 'health', 'Consejo médico', 'B1'],
  ['I have a cough', 'Tengo tos', 'health', 'Al describir síntoma', 'A2'],
  ['Do I need stitches?', '¿Necesito puntos?', 'health', 'Al evaluar herida', 'B2'],
  ['Get some fresh air', 'Tomá un poco de aire fresco', 'health', 'Consejo para sentirse mejor', 'B1'],
  ['I have a cold', 'Estoy resfriado', 'health', 'Al describir enfermedad', 'A2'],

  // ── directions (30) ─────────────────────
  ['Turn left', 'Girá a la izquierda', 'directions', 'Al dar indicaciones', 'A2'],
  ['Go straight', 'Seguí derecho', 'directions', 'Al dar indicaciones', 'A2'],
  ['It\'s on the right', 'Está a la derecha', 'directions', 'Al ubicar algo', 'A2'],
  ['How far is it?', '¿Qué tan lejos está?', 'directions', 'Al preguntar distancia', 'A2'],
  ['Turn right at the corner', 'Girá a la derecha en la esquina', 'directions', 'Al dar indicaciones', 'A2'],
  ["It's on the left", 'Está a la izquierda', 'directions', 'Al ubicar algo', 'A2'],
  ['Go straight ahead', 'Seguí derecho', 'directions', 'Al dar indicaciones', 'A2'],
  ['Take the first left', 'Tomá la primera a la izquierda', 'directions', 'Al dar indicaciones', 'B1'],
  ['Is it within walking distance?', '¿Se puede ir caminando?', 'directions', 'Al preguntar distancia', 'B1'],
  ['It\'s around the corner', 'Está a la vuelta de la esquina', 'directions', 'Al ubicar algo cercano', 'B1'],
  ['Go past the bank', 'Pasá el banco', 'directions', 'Al dar indicaciones', 'B1'],
  ['Cross the street', 'Cruzá la calle', 'directions', 'Al dar indicaciones', 'A2'],
  ["It's at the end of the street", 'Está al final de la calle', 'directions', 'Al ubicar algo', 'B1'],
  ['Take the second right', 'Tomá la segunda a la derecha', 'directions', 'Al dar indicaciones', 'B1'],
  ['Go down this street', 'Bajá por esta calle', 'directions', 'Al dar indicaciones', 'A2'],
  ['You can\'t miss it', 'No te lo podés perder', 'directions', 'Al asegurar que es fácil de encontrar', 'B1'],
  ['It\'s next to the pharmacy', 'Está al lado de la farmacia', 'directions', 'Al ubicar por referencia', 'A2'],
  ['Turn around', 'Date la vuelta', 'directions', 'Al indicar cambio de sentido', 'A2'],
  ["It's across from the park", 'Está enfrente del parque', 'directions', 'Al ubicar por referencia', 'B1'],
  ['I am lost', 'Estoy perdido', 'directions', 'Al pedir ayuda', 'A2'],
  ['Can you show me on the map?', '¿Me podés mostrar en el mapa?', 'directions', 'Al pedir orientación', 'A2'],
  ["It's two blocks away", 'Está a dos cuadras', 'directions', 'Al dar distancia', 'A2'],
  ['Go up the stairs', 'Subí las escaleras', 'directions', 'Al dar indicaciones en edificio', 'A2'],
  ['Take the elevator', 'Tomá el ascensor', 'directions', 'Al dar indicaciones en edificio', 'A2'],
  ["It's on the second floor", 'Está en el segundo piso', 'directions', 'Al ubicar en edificio', 'A2'],
  ['Follow this road', 'Seguí este camino', 'directions', 'Al dar indicaciones', 'B1'],
  ['Keep going until you see...', 'Seguí hasta que veas...', 'directions', 'Al dar indicaciones', 'B1'],
  ["It's behind the supermarket", 'Está detrás del supermercado', 'directions', 'Al ubicar por referencia', 'B1'],
  ['Head north', 'Andá hacia el norte', 'directions', 'Al dar orientación cardinal', 'B1'],
  ['Is this the right way?', '¿Voy bien por acá?', 'directions', 'Al confirmar dirección', 'A2'],

  // ── phone (25) ───────────────────────────
  ['Can I call you later?', '¿Te puedo llamar después?', 'phone', 'Al terminar una llamada', 'A2'],
  ['Could you speak more slowly?', '¿Podrías hablar más despacio?', 'phone', 'Al pedir claridad', 'A2'],
  ["I'll text you", 'Te mando un mensaje', 'phone', 'Al prometer contacto escrito', 'A2'],
  ['My phone is about to die', 'Mi teléfono está por apagarse', 'phone', 'Al avisar batería baja', 'B1'],
  ['I have bad reception here', 'Tengo mala señal acá', 'phone', 'Al explicar problemas de comunicación', 'B1'],
  ['Can you hear me?', '¿Me escuchás?', 'phone', 'Al verificar audio', 'A2'],
  ['Let me call you back', 'Dejame que te llamo de vuelta', 'phone', 'Al posponer llamada', 'B1'],
  ['What is your phone number?', '¿Cuál es tu número de teléfono?', 'phone', 'Al pedir contacto', 'A1'],
  ['I missed your call', 'Perdí tu llamada', 'phone', 'Al revisar llamadas', 'A2'],
  ['Leave a message after the beep', 'Dejá un mensaje después del tono', 'phone', 'Buzón de voz', 'B1'],
  ['I need to charge my phone', 'Necesito cargar mi teléfono', 'phone', 'Al quedarse sin batería', 'A2'],
  ['Can I use your charger?', '¿Puedo usar tu cargador?', 'phone', 'Al pedir prestado', 'A2'],
  ['The line is busy', 'La línea está ocupada', 'phone', 'Al intentar llamar', 'B1'],
  ['I will give you a call', 'Te voy a hacer una llamada', 'phone', 'Al prometer llamar', 'A2'],
  ['Can you send me a text?', '¿Me podés mandar un mensaje?', 'phone', 'Al pedir texto', 'A2'],
  ['I lost your number', 'Perdí tu número', 'phone', 'Al perder contacto', 'A2'],
  ['Can I have your number?', '¿Me podés dar tu número?', 'phone', 'Al pedir contacto', 'A2'],
  ['I need to make a phone call', 'Necesito hacer una llamada', 'phone', 'Al buscar teléfono', 'A2'],
  ['Hold on, someone is calling me', 'Esperá, me están llamando', 'phone', 'Al recibir otra llamada', 'B1'],
  ['My signal keeps dropping', 'Se me corta la señal', 'phone', 'Al explicar mala conexión', 'B1'],
  ['Can you put me on speaker?', '¿Me ponés en altavoz?', 'phone', 'Al pedir manos libres', 'B1'],
  ['Let me check my messages', 'Dejame revisar mis mensajes', 'phone', 'Al ver notificaciones', 'A2'],
  ['Did you get my text?', '¿Recibiste mi mensaje?', 'phone', 'Al verificar comunicación', 'A2'],
  ["I'll send you the address", 'Te mando la dirección', 'phone', 'Al prometer enviar datos', 'A2'],
  ['My phone is on silent', 'Tengo el teléfono en silencio', 'phone', 'Al explicar que no se escucha', 'B1'],

  // ── emotions (30) ────────────────────────
  ["I'm very happy", 'Estoy muy feliz', 'emotions', 'Al expresar alegría', 'A2'],
  ["I'm a little tired", 'Estoy un poco cansado', 'emotions', 'Al expresar cansancio', 'A2'],
  ["That's amazing!", '¡Eso es increíble!', 'emotions', 'Al expresar asombro', 'A2'],
  ["I'm not sure", 'No estoy seguro', 'emotions', 'Al expresar duda', 'A2'],
  ["I'm so excited!", '¡Estoy tan emocionado!', 'emotions', 'Al expresar entusiasmo', 'A2'],
  ["I'm worried about you", 'Estoy preocupado por vos', 'emotions', 'Al expresar preocupación', 'B1'],
  ["I'm feeling nervous", 'Me siento nervioso', 'emotions', 'Al expresar ansiedad', 'B1'],
  ["That's so funny!", '¡Qué gracioso!', 'emotions', 'Al reaccionar a algo cómico', 'A2'],
  ["I'm disappointed", 'Estoy decepcionado', 'emotions', 'Al expresar desilusión', 'B1'],
  ["I'm so proud of you!", '¡Estoy tan orgulloso de vos!', 'emotions', 'Al expresar orgullo', 'B1'],
  ["I'm really stressed out", 'Estoy muy estresado', 'emotions', 'Al expresar estrés', 'B1'],
  ["That's so sweet of you!", '¡Qué dulce de tu parte!', 'emotions', 'Al agradecer gesto amable', 'B1'],
  ["I'm confused", 'Estoy confundido', 'emotions', 'Al expresar confusión', 'A2'],
  ["I feel lonely", 'Me siento solo', 'emotions', 'Al expresar soledad', 'B1'],
  ["You scared me!", '¡Me asustaste!', 'emotions', 'Al reaccionar a un susto', 'A2'],
  ["I'm grateful for your help", 'Estoy agradecido por tu ayuda', 'emotions', 'Al expresar gratitud', 'B1'],
  ["I'm shocked!", '¡Estoy en shock!', 'emotions', 'Al expresar impacto', 'B1'],
  ["That's so annoying", 'Qué molesto', 'emotions', 'Al expresar fastidio', 'B1'],
  ["I'm over the moon!", '¡Estoy en la luna!', 'emotions', 'Al expresar felicidad extrema', 'B2'],
  ["I'm heartbroken", 'Tengo el corazón roto', 'emotions', 'Al expresar tristeza profunda', 'B2'],
  ["You made my day!", '¡Me alegraste el día!', 'emotions', 'Al agradecer gesto', 'B1'],
  ["I'm fed up", 'Estoy harto', 'emotions', 'Al expresar frustración', 'B2'],
  ["That's a relief!", '¡Qué alivio!', 'emotions', 'Al sentir alivio', 'B1'],
  ["I'm jealous", 'Estoy celoso / Tengo envidia', 'emotions', 'Al expresar celos', 'B1'],
  ["I can't believe it!", '¡No lo puedo creer!', 'emotions', 'Al expresar incredulidad', 'A2'],
  ["I'm furious!", '¡Estoy furioso!', 'emotions', 'Al expresar enojo extremo', 'B1'],
  ["Take it easy", 'Tomalo con calma', 'emotions', 'Al calmar a alguien', 'A2'],
  ["Don't worry about it", 'No te preocupes por eso', 'emotions', 'Al tranquilizar', 'A2'],
  ["Cheer up!", '¡Animate!', 'emotions', 'Al animar a alguien triste', 'A2'],
  ["Calm down", 'Tranquilizate', 'emotions', 'Al calmar a alguien alterado', 'A2'],

  // ── time (35) ────────────────────────────
  ['What time is it?', '¿Qué hora es?', 'time', 'Al preguntar la hora', 'A1'],
  ["I'm running late", 'Estoy llegando tarde', 'time', 'Al avisar demora', 'A2'],
  ["Let's meet at noon", 'Encontrémonos al mediodía', 'time', 'Al coordinar encuentro', 'A2'],
  ['I will be there at 5pm', 'Voy a estar ahí a las 5 de la tarde', 'time', 'Al confirmar horario', 'A2'],
  ['It takes about an hour', 'Toma más o menos una hora', 'time', 'Al estimar duración', 'A2'],
  ['I wake up at 7 every morning', 'Me despierto a las 7 todas las mañanas', 'time', 'Al hablar de rutina', 'A2'],
  ['The meeting starts at 3', 'La reunión empieza a las 3', 'time', 'Al informar horario', 'A2'],
  ['Hurry up!', '¡Apurate!', 'time', 'Al pedir rapidez', 'A2'],
  ['Take your time', 'Tomate tu tiempo', 'time', 'Al dar permiso de demora', 'A2'],
  ['I have plenty of time', 'Tengo mucho tiempo', 'time', 'Al expresar disponibilidad', 'A2'],
  ["We're out of time", 'Se nos acabó el tiempo', 'time', 'Al finalizar plazo', 'B1'],
  ['It is 3 o\'clock', 'Son las 3 en punto', 'time', 'Al decir la hora', 'A1'],
  ['It is half past two', 'Son las dos y media', 'time', 'Al decir la hora', 'A2'],
  ['It is quarter to four', 'Son las cuatro menos cuarto', 'time', 'Al decir la hora', 'A2'],
  ['I will see you in an hour', 'Te veo en una hora', 'time', 'Al coordinar', 'A2'],
  ['The movie starts at 7:30', 'La película empieza a las 7:30', 'time', 'Al informar horario', 'A2'],
  ['Can we meet earlier?', '¿Podemos juntarnos más temprano?', 'time', 'Al cambiar horario', 'B1'],
  ['I was up all night', 'Estuve despierto toda la noche', 'time', 'Al explicar trasnoche', 'B1'],
  ["Time flies!", '¡El tiempo vuela!', 'time', 'Al notar que pasó rápido', 'B1'],
  ["I'll be back in five minutes", 'Vuelvo en cinco minutos', 'time', 'Al avisar regreso breve', 'A2'],
  ['The store closes at 9', 'La tienda cierra a las 9', 'time', 'Al informar horario', 'A2'],
  ['What day is it today?', '¿Qué día es hoy?', 'time', 'Al preguntar el día', 'A1'],
  ['It is Monday', 'Es lunes', 'time', 'Al decir el día', 'A1'],
  ['My birthday is in June', 'Mi cumpleaños es en junio', 'time', 'Al hablar de fecha', 'A2'],
  ['The concert is next Saturday', 'El concierto es el próximo sábado', 'time', 'Al hablar de evento futuro', 'A2'],
  ['We have to leave now', 'Tenemos que irnos ahora', 'time', 'Al indicar urgencia', 'A2'],
  ['I will be done soon', 'Voy a terminar pronto', 'time', 'Al avisar finalización', 'A2'],
  ['Wait a moment', 'Esperá un momento', 'time', 'Al pedir espera breve', 'A2'],
  ['Just a second', 'Un segundo', 'time', 'Al pedir espera mínima', 'A2'],
  ['I arrived early', 'Llegué temprano', 'time', 'Al indicar puntualidad', 'A2'],
  ['I was there on time', 'Llegué a tiempo', 'time', 'Al indicar puntualidad', 'A2'],
  ['She is always late', 'Ella siempre llega tarde', 'time', 'Al comentar hábito', 'A2'],
  ['The bus is delayed', 'El colectivo está demorado', 'time', 'Al informar demora', 'B1'],
  ['I need more time', 'Necesito más tiempo', 'time', 'Al pedir plazo', 'A2'],
  ['What time do you open?', '¿A qué hora abren?', 'time', 'Al preguntar horario', 'A2'],

  // ── weather (35) ─────────────────────────
  ["It's very hot today", 'Hace mucho calor hoy', 'weather', 'Al comentar el clima', 'A2'],
  ['It looks like rain', 'Parece que va a llover', 'weather', 'Al observar el cielo', 'A2'],
  ["What's the weather forecast?", '¿Cuál es el pronóstico del tiempo?', 'weather', 'Al preguntar pronóstico', 'B1'],
  ['It is sunny today', 'Hoy está soleado', 'weather', 'Al describir el clima', 'A1'],
  ['It is raining', 'Está lloviendo', 'weather', 'Al describir el clima', 'A1'],
  ['It is snowing', 'Está nevando', 'weather', 'Al describir el clima', 'A2'],
  ['The temperature is dropping', 'La temperatura está bajando', 'weather', 'Al comentar cambio', 'B1'],
  ["It's a beautiful day!", '¡Es un día hermoso!', 'weather', 'Al apreciar buen clima', 'A2'],
  ['It is windy outside', 'Está ventoso afuera', 'weather', 'Al describir el clima', 'A2'],
  ['Do I need a jacket?', '¿Necesito una campera?', 'weather', 'Al decidir qué ponerse', 'A2'],
  ["It's freezing out there!", '¡Está helado afuera!', 'weather', 'Al expresar frío extremo', 'B1'],
  ['The sun is shining', 'El sol está brillando', 'weather', 'Al describir día soleado', 'A2'],
  ['It is cloudy', 'Está nublado', 'weather', 'Al describir el cielo', 'A2'],
  ['There is a storm coming', 'Se viene una tormenta', 'weather', 'Al advertir sobre el clima', 'B1'],
  ["I hope it doesn't rain", 'Espero que no llueva', 'weather', 'Al expresar deseo', 'A2'],
  ['What is the temperature?', '¿Qué temperatura hace?', 'weather', 'Al preguntar temperatura', 'B1'],
  ["It's going to be hot tomorrow", 'Va a hacer calor mañana', 'weather', 'Al anticipar clima', 'A2'],
  ['We need an umbrella', 'Necesitamos un paraguas', 'weather', 'Al prepararse para lluvia', 'A2'],
  ['The weather is perfect', 'El clima está perfecto', 'weather', 'Al expresar satisfacción', 'A2'],
  ['Is it cold outside?', '¿Hace frío afuera?', 'weather', 'Al preguntar temperatura', 'A2'],
  ['It is foggy this morning', 'Está con neblina esta mañana', 'weather', 'Al describir visibilidad', 'B1'],
  ['The roads are icy', 'Las calles están con hielo', 'weather', 'Al advertir condición', 'B2'],
  ['It hailed last night', 'Cayó granizo anoche', 'weather', 'Al contar evento climático', 'B2'],
  ['Dress warmly, it is cold', 'Abrigate, hace frío', 'weather', 'Al dar consejo', 'A2'],
  ["It's a bit chilly", 'Está un poco fresco', 'weather', 'Al describir frío leve', 'B1'],
  ['There is a heat wave', 'Hay una ola de calor', 'weather', 'Al comentar fenómeno', 'B1'],
  ['The humidity is really high', 'La humedad está muy alta', 'weather', 'Al describir sensación', 'B1'],
  ["It's pouring outside!", '¡Está lloviendo a cántaros!', 'weather', 'Al describir lluvia intensa', 'B1'],
  ['There might be a thunderstorm', 'Puede haber tormenta eléctrica', 'weather', 'Al anticipar clima severo', 'B1'],
  ['It should clear up later', 'Debería despejarse más tarde', 'weather', 'Al anticipar mejora', 'B1'],
  ['We had a lot of rain last week', 'Tuvimos mucha lluvia la semana pasada', 'weather', 'Al comentar clima pasado', 'B1'],
  ['The sky is clear', 'El cielo está despejado', 'weather', 'Al describir cielo', 'B1'],
  ['What a gorgeous sunset!', '¡Qué atardecer hermoso!', 'weather', 'Al admirar el paisaje', 'B1'],
  ['It feels like 40 degrees!', '¡Se siente como 40 grados!', 'weather', 'Al comentar sensación térmica', 'B1'],
  ["The weather has been crazy lately", 'El clima estuvo loco últimamente', 'weather', 'Al comentar cambios climáticos', 'B1'],

  // ── family (30) ──────────────────────────
  ['I have two brothers', 'Tengo dos hermanos', 'family', 'Al hablar de tu familia', 'A1'],
  ['My parents live in...', 'Mis padres viven en...', 'family', 'Al hablar de tus padres', 'A2'],
  ['We are a big family', 'Somos una familia grande', 'family', 'Al describir tu familia', 'A2'],
  ['Do you have any siblings?', '¿Tenés hermanos?', 'family', 'Al preguntar sobre familia', 'A2'],
  ['I am the oldest', 'Soy el/la mayor', 'family', 'Al hablar de orden', 'A2'],
  ['Family comes first', 'La familia es primero', 'family', 'Al expresar valor', 'B1'],
  ['My sister is a doctor', 'Mi hermana es doctora', 'family', 'Al hablar de profesión familiar', 'A2'],
  ['We have dinner together every Sunday', 'Cenamos juntos todos los domingos', 'family', 'Al contar tradición', 'B1'],
  ['I have three children', 'Tengo tres hijos', 'family', 'Al hablar de tus hijos', 'A2'],
  ['My grandparents are from Italy', 'Mis abuelos son de Italia', 'family', 'Al hablar de origen', 'B1'],
  ['She looks just like her mother', 'Es igualita a su mamá', 'family', 'Al comentar parecido', 'B1'],
  ['We got married last year', 'Nos casamos el año pasado', 'family', 'Al contar evento', 'A2'],
  ['My cousin lives in New York', 'Mi primo vive en Nueva York', 'family', 'Al hablar de parientes', 'B1'],
  ['How is your family?', '¿Cómo está tu familia?', 'family', 'Al preguntar por la familia', 'A2'],
  ['I miss my family', 'Extraño a mi familia', 'family', 'Al expresar nostalgia', 'A2'],
  ['My brother and I are very close', 'Mi hermano y yo somos muy cercanos', 'family', 'Al describir relación', 'B1'],
  ['She is the youngest in the family', 'Ella es la menor de la familia', 'family', 'Al hablar de orden', 'B1'],
  ['My uncle is visiting us', 'Mi tío nos está visitando', 'family', 'Al contar visita', 'A2'],
  ['We have a family reunion every year', 'Tenemos una reunión familiar cada año', 'family', 'Al contar tradición', 'B1'],
  ['My daughter just started school', 'Mi hija acaba de empezar la escuela', 'family', 'Al contar novedad', 'B1'],
  ['He takes after his father', 'Salió al padre', 'family', 'Al comentar parecido', 'B1'],
  ['My mother is a great cook', 'Mi mamá es una gran cocinera', 'family', 'Al halagar a un familiar', 'B1'],
  ['We are expecting a baby', 'Estamos esperando un bebé', 'family', 'Al anunciar embarazo', 'B1'],
  ['I grew up in a small town', 'Crecí en un pueblo chico', 'family', 'Al contar infancia', 'B1'],
  ['My father taught me how to drive', 'Mi papá me enseñó a manejar', 'family', 'Al contar aprendizaje', 'B1'],
  ['She is a single mother', 'Ella es madre soltera', 'family', 'Al describir situación', 'B1'],
  ['We adopted a child', 'Adoptamos un hijo', 'family', 'Al contar evento familiar', 'B2'],
  ['My siblings and I get along well', 'Mis hermanos y yo nos llevamos bien', 'family', 'Al describir relación', 'B1'],
  ['Family is everything to me', 'La familia lo es todo para mí', 'family', 'Al expresar valor', 'B1'],
  ['My parents are divorced', 'Mis padres están divorciados', 'family', 'Al hablar de situación', 'B1'],
];

const CATEGORY_IMAGES = {
  greetings: 'https://images.unsplash.com/photo-1573166364524-d9dbfd8bbf83?w=400',
  courtesy: 'https://images.unsplash.com/photo-1573166364524-d9dbfd8bbf83?w=400',
  questions: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400',
  introductions: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  shopping: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400',
  restaurant: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
  travel: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400',
  work: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=400',
  health: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
  directions: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400',
  phone: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
  emotions: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  time: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=400',
  weather: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400',
  family: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
};

// Expand compact data into full phrase objects
export const PHRASES_SEED = PHRASE_DATA.map((row, index) => ({
  phrase_en: row[0],
  phrase_es: row[1],
  category: row[2],
  context: row[3],
  difficulty: row[4],
  image_url: CATEGORY_IMAGES[row[2]] || null,
  audio_url: null,
}));
