// saflash — Words seed data (5,000 English words for Spanish speakers)
// Compact format: [english, spanish, category, subcategory, difficulty]
// Image URLs and examples are generated from templates

// ── Category header images (Unsplash) ─────
const CAT_IMG = {
  basics: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
  verbs_common: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=400',
  verbs_action: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=400',
  family: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  body: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
  health: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
  food_drink: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
  clothing: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400',
  home: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
  nature: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400',
  animals: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400',
  colors_shapes: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400',
  numbers_time: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=400',
  emotions: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  work_business: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=400',
  technology: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
  transport: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400',
  education: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400',
  sports: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400',
  arts_culture: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
  shopping: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400',
  travel: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400',
  social: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  adjectives: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
  adverbs: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400',
  other: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
};

// ── Simple phonetic approximator ───────────
function guessPhonetic(word) {
  const map = {
    the: '/ðə/', be: '/biː/', to: '/tuː/', of: '/ʌv/', and: '/ænd/',
    a: '/eɪ/', in: '/ɪn/', that: '/ðæt/', have: '/hæv/', it: '/ɪt/',
    for: '/fɔːr/', not: '/nɒt/', on: '/ɒn/', with: '/wɪð/', he: '/hiː/',
    you: '/juː/', do: '/duː/', this: '/ðɪs/', but: '/bʌt/', his: '/hɪz/',
    they: '/ðeɪ/', we: '/wiː/', she: '/ʃiː/', say: '/seɪ/', her: '/hɜːr/',
    or: '/ɔːr/', an: '/æn/', will: '/wɪl/', my: '/maɪ/', one: '/wʌn/',
    all: '/ɔːl/', would: '/wʊd/', there: '/ðeər/', their: '/ðeər/',
    what: '/wɒt/', so: '/soʊ/', up: '/ʌp/', out: '/aʊt/', if: '/ɪf/',
    about: '/əˈbaʊt/', who: '/huː/', get: '/ɡet/', which: '/wɪtʃ/',
    go: '/ɡoʊ/', me: '/miː/', when: '/wen/', make: '/meɪk/',
    can: '/kæn/', like: '/laɪk/', time: '/taɪm/', no: '/noʊ/',
    just: '/dʒʌst/', him: '/hɪm/', know: '/noʊ/', take: '/teɪk/',
    people: '/ˈpiːpəl/', into: '/ˈɪntuː/', year: '/jɪər/',
    your: '/jɔːr/', good: '/ɡʊd/', some: '/sʌm/', could: '/kʊd/',
    them: '/ðem/', see: '/siː/', other: '/ˈʌðər/', than: '/ðæn/',
    then: '/ðen/', now: '/naʊ/', look: '/lʊk/', only: '/ˈoʊnli/',
    come: '/kʌm/', its: '/ɪts/', over: '/ˈoʊvər/', think: '/θɪŋk/',
    also: '/ˈɔːlsoʊ/', back: '/bæk/', after: '/ˈæftər/',
    use: '/juːz/', two: '/tuː/', how: '/haʊ/', our: '/aʊər/',
    work: '/wɜːrk/', first: '/fɜːrst/', well: '/wel/',
    way: '/weɪ/', even: '/ˈiːvən/', new: '/njuː/', want: '/wɒnt/',
    because: '/bɪˈkɔːz/', any: '/ˈeni/', these: '/ðiːz/',
    give: '/ɡɪv/', day: '/deɪ/', most: '/moʊst/', us: '/ʌs/',
    great: '/ɡreɪt/', man: '/mæn/', woman: '/ˈwʊmən/',
    water: '/ˈwɔːtər/', food: '/fuːd/',
  };
  return map[word.toLowerCase()] || `/${word}/`;
}

// ── Example sentence generator ─────────────
// Offline fallback example. Real example sentences are fetched from the Free
// Dictionary API on first view and replace these. This template is intentionally
// a "meta" sentence that is ALWAYS grammatically correct for any part of speech
// (the previous per-category templates produced broken phrases like "I can be
// it."), and is itself useful: it reinforces the word and its meaning.
function makeExample(en, es) {
  return [
    `The word "${en}" means "${es}".`,
    `La palabra "${en}" significa "${es}".`,
  ];
}

// ── COMPACT WORD DATA ──────────────────────
// [english, spanish, category, subcategory|null, difficulty]
const WORDS_COMPACT = [
  // === 1-200: High-frequency basics from plan ===
  ['the', 'el/la/los/las', 'basics', null, 'A1'],
  ['be', 'ser/estar', 'verbs_common', null, 'A1'],
  ['to', 'a/para', 'basics', null, 'A1'],
  ['of', 'de', 'basics', null, 'A1'],
  ['and', 'y', 'basics', null, 'A1'],
  ['a', 'un/una', 'basics', null, 'A1'],
  ['in', 'en', 'basics', null, 'A1'],
  ['that', 'ese/esa/que', 'basics', null, 'A1'],
  ['have', 'tener', 'verbs_common', null, 'A1'],
  ['it', 'eso', 'basics', null, 'A1'],
  ['for', 'para/por', 'basics', null, 'A1'],
  ['not', 'no', 'basics', null, 'A1'],
  ['on', 'en/sobre', 'basics', null, 'A1'],
  ['with', 'con', 'basics', null, 'A1'],
  ['he', 'él', 'basics', null, 'A1'],
  ['you', 'tú/usted', 'basics', null, 'A1'],
  ['do', 'hacer', 'verbs_common', null, 'A1'],
  ['this', 'este/esta', 'basics', null, 'A1'],
  ['but', 'pero', 'basics', null, 'A1'],
  ['his', 'su (de él)', 'basics', null, 'A1'],
  ['they', 'ellos/ellas', 'basics', null, 'A1'],
  ['we', 'nosotros', 'basics', null, 'A1'],
  ['she', 'ella', 'basics', null, 'A1'],
  ['say', 'decir', 'verbs_common', null, 'A1'],
  ['her', 'su (de ella)/la', 'basics', null, 'A1'],
  ['or', 'o', 'basics', null, 'A1'],
  ['an', 'un/una (vocal)', 'basics', null, 'A1'],
  ['will', '(futuro)', 'basics', null, 'A1'],
  ['my', 'mi/mis', 'basics', null, 'A1'],
  ['one', 'uno', 'basics', null, 'A1'],
  ['all', 'todo/todos', 'basics', null, 'A1'],
  ['would', '(condicional)', 'basics', null, 'A1'],
  ['there', 'allí/ahí/hay', 'basics', null, 'A1'],
  ['their', 'su/sus (ellos)', 'basics', null, 'A1'],
  ['what', 'qué', 'basics', null, 'A1'],
  ['so', 'entonces/tan', 'basics', null, 'A1'],
  ['up', 'arriba', 'basics', null, 'A1'],
  ['out', 'fuera/afuera', 'basics', null, 'A1'],
  ['if', 'si (condicional)', 'basics', null, 'A1'],
  ['about', 'sobre/acerca de', 'basics', null, 'A1'],
  ['who', 'quién', 'basics', null, 'A1'],
  ['get', 'obtener/conseguir', 'verbs_common', null, 'A1'],
  ['which', 'cuál', 'basics', null, 'A1'],
  ['go', 'ir', 'verbs_common', null, 'A1'],
  ['me', 'me/mí', 'basics', null, 'A1'],
  ['when', 'cuándo', 'basics', null, 'A1'],
  ['make', 'hacer/fabricar', 'verbs_common', null, 'A1'],
  ['can', 'poder', 'verbs_common', null, 'A1'],
  ['like', 'gustar/como', 'basics', null, 'A1'],
  ['time', 'tiempo/hora', 'basics', null, 'A1'],
  ['no', 'no', 'basics', null, 'A1'],
  ['just', 'solo/justo', 'basics', null, 'A1'],
  ['him', 'lo/le (a él)', 'basics', null, 'A1'],
  ['know', 'saber/conocer', 'verbs_common', null, 'A1'],
  ['take', 'tomar/llevar', 'verbs_common', null, 'A1'],
  ['people', 'personas/gente', 'basics', null, 'A1'],
  ['into', 'dentro de/en', 'basics', null, 'A1'],
  ['year', 'año', 'basics', null, 'A1'],
  ['your', 'tu/tus/su/sus', 'basics', null, 'A1'],
  ['good', 'bueno/bien', 'adjectives', null, 'A1'],
  ['some', 'algunos/algo de', 'basics', null, 'A1'],
  ['could', 'podría', 'basics', null, 'A1'],
  ['them', 'los/las/les', 'basics', null, 'A1'],
  ['see', 'ver', 'verbs_common', null, 'A1'],
  ['other', 'otro/otros', 'basics', null, 'A1'],
  ['than', 'que (comparación)', 'basics', null, 'A1'],
  ['then', 'entonces/luego', 'basics', null, 'A1'],
  ['now', 'ahora', 'basics', null, 'A1'],
  ['look', 'mirar/parecer', 'verbs_common', null, 'A1'],
  ['only', 'solo/solamente', 'basics', null, 'A1'],
  ['come', 'venir', 'verbs_common', null, 'A1'],
  ['its', 'su/sus (cosa)', 'basics', null, 'A1'],
  ['over', 'sobre/encima', 'basics', null, 'A1'],
  ['think', 'pensar', 'verbs_common', null, 'A1'],
  ['also', 'también', 'basics', null, 'A1'],
  ['back', 'atrás/de vuelta', 'basics', null, 'A1'],
  ['after', 'después de', 'basics', null, 'A1'],
  ['use', 'usar', 'verbs_common', null, 'A1'],
  ['two', 'dos', 'numbers_time', null, 'A1'],
  ['how', 'cómo/cuánto', 'basics', null, 'A1'],
  ['our', 'nuestro/nuestra', 'basics', null, 'A1'],
  ['work', 'trabajar/trabajo', 'work_business', null, 'A1'],
  ['first', 'primero', 'basics', null, 'A1'],
  ['well', 'bien/pozo', 'basics', null, 'A1'],
  ['way', 'camino/manera', 'basics', null, 'A1'],
  ['even', 'incluso/par', 'basics', null, 'A1'],
  ['new', 'nuevo', 'adjectives', null, 'A1'],
  ['want', 'querer', 'verbs_common', null, 'A1'],
  ['because', 'porque', 'basics', null, 'A1'],
  ['any', 'cualquier/alguno', 'basics', null, 'A1'],
  ['these', 'estos/estas', 'basics', null, 'A1'],
  ['give', 'dar', 'verbs_common', null, 'A1'],
  ['day', 'día', 'basics', null, 'A1'],
  ['most', 'mayoría/el más', 'basics', null, 'A1'],
  ['us', 'nos/nosotros', 'basics', null, 'A1'],
  ['great', 'genial/grande', 'adjectives', null, 'A1'],
  ['man', 'hombre', 'basics', null, 'A1'],
  ['woman', 'mujer', 'basics', null, 'A1'],
  ['water', 'agua', 'food_drink', 'beverages', 'A1'],
  ['food', 'comida', 'food_drink', null, 'A1'],
  // ... continuing to 200
  ['big', 'grande', 'adjectives', null, 'A1'],
  ['small', 'pequeño', 'adjectives', null, 'A1'],
  ['long', 'largo', 'adjectives', null, 'A1'],
  ['little', 'pequeño/poco', 'adjectives', null, 'A1'],
  ['own', 'propio', 'basics', null, 'A1'],
  ['old', 'viejo/antiguo', 'adjectives', null, 'A1'],
  ['right', 'derecho/correcto', 'basics', null, 'A1'],
  ['hand', 'mano', 'body', null, 'A1'],
  ['here', 'aquí', 'basics', null, 'A1'],
  ['home', 'hogar/casa', 'home', null, 'A1'],
  ['world', 'mundo', 'nature', null, 'A2'],
  ['house', 'casa', 'home', null, 'A1'],
  ['life', 'vida', 'other', null, 'A1'],
  ['child', 'niño/niña', 'family', null, 'A1'],
  ['should', 'debería', 'basics', null, 'A1'],
  ['place', 'lugar', 'other', null, 'A1'],
  ['still', 'todavía', 'adverbs', null, 'A1'],
  ['thing', 'cosa', 'other', null, 'A1'],
  ['part', 'parte', 'other', null, 'A1'],
  ['where', 'dónde', 'basics', null, 'A1'],
  ['every', 'cada/todo', 'basics', null, 'A1'],
  ['need', 'necesitar', 'verbs_common', null, 'A1'],
  ['try', 'intentar', 'verbs_action', null, 'A2'],
  ['ask', 'preguntar/pedir', 'verbs_action', null, 'A1'],
  ['find', 'encontrar', 'verbs_action', null, 'A1'],
  ['tell', 'decir/contar', 'verbs_action', null, 'A1'],
  ['put', 'poner', 'verbs_action', null, 'A1'],
  ['mean', 'significar', 'other', null, 'A2'],
  ['keep', 'mantener/guardar', 'verbs_action', null, 'A2'],
  ['let', 'dejar/permitir', 'verbs_action', null, 'A2'],
  ['begin', 'empezar', 'verbs_action', null, 'A2'],
  ['seem', 'parecer', 'other', null, 'A2'],
  ['help', 'ayudar', 'verbs_action', null, 'A1'],
  ['talk', 'hablar', 'verbs_action', null, 'A1'],
  ['turn', 'girar/voltear', 'verbs_action', null, 'A2'],
  ['start', 'empezar', 'verbs_action', null, 'A1'],
  ['show', 'mostrar', 'verbs_action', null, 'A2'],
  ['hear', 'oír', 'verbs_action', null, 'A1'],
  ['play', 'jugar/tocar', 'verbs_action', null, 'A1'],
  ['run', 'correr', 'verbs_action', null, 'A1'],
  ['move', 'mover', 'verbs_action', null, 'A2'],
  ['live', 'vivir', 'verbs_action', null, 'A1'],
  ['believe', 'creer', 'verbs_action', null, 'A2'],
  ['hold', 'sostener', 'verbs_action', null, 'A2'],
  ['bring', 'traer', 'verbs_action', null, 'A2'],
  ['happen', 'suceder', 'other', null, 'A2'],
  ['write', 'escribir', 'verbs_action', null, 'A1'],
  ['sit', 'sentarse', 'verbs_action', null, 'A1'],
  ['stand', 'pararse', 'verbs_action', null, 'A1'],
  ['lose', 'perder', 'verbs_action', null, 'A2'],
  ['pay', 'pagar', 'verbs_action', null, 'A2'],
  ['meet', 'conocer/reunirse', 'verbs_action', null, 'A1'],
  ['include', 'incluir', 'other', null, 'B1'],
  ['continue', 'continuar', 'verbs_action', null, 'B1'],
  ['set', 'colocar/establecer', 'verbs_action', null, 'A2'],
  ['learn', 'aprender', 'verbs_action', null, 'A1'],
  ['change', 'cambiar', 'other', null, 'A2'],
  ['lead', 'liderar/guiar', 'verbs_action', null, 'B1'],
  ['understand', 'entender', 'verbs_action', null, 'A2'],
  ['watch', 'mirar/observar', 'verbs_action', null, 'A1'],
  ['follow', 'seguir', 'verbs_action', null, 'A2'],
  ['stop', 'parar/detener', 'verbs_action', null, 'A1'],
  ['create', 'crear', 'verbs_action', null, 'B1'],
  ['speak', 'hablar', 'verbs_action', null, 'A1'],
  ['read', 'leer', 'verbs_action', null, 'A1'],
  ['allow', 'permitir', 'verbs_action', null, 'B1'],
  ['add', 'añadir/agregar', 'verbs_action', null, 'A2'],
  ['spend', 'gastar/pasar (tiempo)', 'verbs_action', null, 'A2'],
  ['grow', 'crecer', 'verbs_action', null, 'A2'],
  ['open', 'abrir', 'verbs_action', null, 'A1'],
  ['walk', 'caminar', 'verbs_action', null, 'A1'],
  ['win', 'ganar', 'verbs_action', null, 'A2'],
  ['offer', 'ofrecer', 'verbs_action', null, 'B1'],
  ['remember', 'recordar', 'verbs_action', null, 'A2'],
  ['love', 'amar/encantar', 'verbs_action', null, 'A1'],
  ['consider', 'considerar', 'other', null, 'B1'],
  ['appear', 'aparecer', 'other', null, 'B1'],
  ['buy', 'comprar', 'verbs_action', null, 'A1'],
  ['wait', 'esperar', 'verbs_action', null, 'A2'],
  ['serve', 'servir', 'verbs_action', null, 'A2'],
  ['die', 'morir', 'verbs_action', null, 'A2'],
  ['send', 'enviar', 'verbs_action', null, 'A2'],
  ['expect', 'esperar/suponer', 'other', null, 'B1'],
  ['build', 'construir', 'verbs_action', null, 'A2'],
  ['stay', 'quedarse', 'verbs_action', null, 'A2'],
  ['fall', 'caer', 'verbs_action', null, 'A2'],
  ['cut', 'cortar', 'verbs_action', null, 'A2'],
  ['reach', 'alcanzar/llegar', 'verbs_action', null, 'B1'],
  ['kill', 'matar', 'verbs_action', null, 'A2'],
  ['remain', 'permanecer', 'other', null, 'B1'],
  ['suggest', 'sugerir', 'other', null, 'B1'],
  ['raise', 'levantar/aumentar', 'verbs_action', null, 'B1'],
  ['pass', 'pasar/aprobar', 'verbs_action', null, 'A2'],
  ['sell', 'vender', 'verbs_action', null, 'A2'],
  ['require', 'requerir', 'other', null, 'B1'],
  ['report', 'informar/reportar', 'other', null, 'B1'],
  ['decide', 'decidir', 'verbs_action', null, 'A2'],
  ['pull', 'jalar/tirar', 'verbs_action', null, 'A2'],
  ['eat', 'comer', 'verbs_action', null, 'A1'],
  ['drink', 'beber/tomar', 'verbs_action', null, 'A1'],
  ['sleep', 'dormir', 'verbs_action', null, 'A1'],
  ['cook', 'cocinar', 'verbs_action', null, 'A2'],
  ['sing', 'cantar', 'verbs_action', null, 'A1'],
  ['dance', 'bailar', 'verbs_action', null, 'A1'],
  ['swim', 'nadar', 'verbs_action', null, 'A1'],
  ['fly', 'volar', 'verbs_action', null, 'A2'],
  ['drive', 'manejar/conducir', 'verbs_action', null, 'A1'],
  ['ride', 'montar/andar', 'verbs_action', null, 'A2'],
  ['climb', 'escalar/trepar', 'verbs_action', null, 'A2'],
  ['fight', 'pelear/luchar', 'verbs_action', null, 'A2'],
  ['throw', 'tirar/lanzar', 'verbs_action', null, 'A2'],
  ['catch', 'atrapar', 'verbs_action', null, 'A2'],
  ['push', 'empujar', 'verbs_action', null, 'A2'],
  ['lift', 'levantar', 'verbs_action', null, 'A2'],
  ['carry', 'llevar/cargar', 'verbs_action', null, 'A2'],
  ['break', 'romper', 'verbs_action', null, 'A2'],
  ['fix', 'arreglar/reparar', 'verbs_action', null, 'A2'],
  ['clean', 'limpiar', 'verbs_action', null, 'A1'],
  ['wash', 'lavar', 'verbs_action', null, 'A1'],
  ['draw', 'dibujar', 'verbs_action', null, 'A1'],
  ['paint', 'pintar', 'verbs_action', null, 'A2'],
  ['call', 'llamar', 'verbs_action', null, 'A1'],
  ['answer', 'responder/contestar', 'verbs_action', null, 'A2'],
  ['listen', 'escuchar', 'verbs_action', null, 'A1'],
  ['feel', 'sentir', 'verbs_action', null, 'A1'],
  ['touch', 'tocar', 'verbs_action', null, 'A2'],
  ['smell', 'oler', 'verbs_action', null, 'A2'],
  ['taste', 'probar/saborear', 'verbs_action', null, 'A2'],
  ['cry', 'llorar', 'verbs_action', null, 'A2'],
  ['laugh', 'reír', 'verbs_action', null, 'A2'],
  ['smile', 'sonreír', 'verbs_action', null, 'A1'],
  ['shout', 'gritar', 'verbs_action', null, 'A2'],
  ['whisper', 'susurrar', 'verbs_action', null, 'B1'],
  ['arrive', 'llegar', 'verbs_action', null, 'A2'],
  ['leave', 'irse/dejar', 'verbs_action', null, 'A1'],
  ['return', 'volver/regresar', 'verbs_action', null, 'A2'],
  ['enter', 'entrar', 'verbs_action', null, 'A2'],
  ['exit', 'salir', 'verbs_action', null, 'A2'],
  ['hide', 'esconder', 'verbs_action', null, 'A2'],
  ['search', 'buscar', 'verbs_action', null, 'A2'],
  ['borrow', 'pedir prestado', 'verbs_action', null, 'A2'],
  ['lend', 'prestar', 'verbs_action', null, 'B1'],
  ['steal', 'robar', 'verbs_action', null, 'B1'],
  ['save', 'guardar/ahorrar', 'verbs_action', null, 'A2'],
  ['spend', 'gastar', 'verbs_action', null, 'A2'],
  ['earn', 'ganar (dinero)', 'verbs_action', null, 'B1'],
  ['count', 'contar', 'verbs_action', null, 'A1'],
  ['share', 'compartir', 'verbs_action', null, 'A2'],
  ['choose', 'elegir', 'verbs_action', null, 'B1'],
  ['prepare', 'preparar', 'verbs_action', null, 'A2'],
  ['organize', 'organizar', 'verbs_action', null, 'B1'],
  ['plan', 'planear/planificar', 'verbs_action', null, 'A2'],
  ['imagine', 'imaginar', 'verbs_action', null, 'B1'],
  ['dream', 'soñar', 'verbs_action', null, 'A2'],
  ['wish', 'desear', 'verbs_action', null, 'A2'],
  ['hope', 'esperar/tener esperanza', 'verbs_action', null, 'A2'],
  ['promise', 'prometer', 'verbs_action', null, 'B1'],
  ['forget', 'olvidar', 'verbs_action', null, 'A2'],
  ['explain', 'explicar', 'verbs_action', null, 'A2'],
  ['describe', 'describir', 'verbs_action', null, 'B1'],
  ['compare', 'comparar', 'other', null, 'B1'],
  ['agree', 'estar de acuerdo', 'other', null, 'A2'],
  ['disagree', 'no estar de acuerdo', 'other', null, 'B1'],
  ['accept', 'aceptar', 'other', null, 'B1'],
  ['refuse', 'rechazar', 'other', null, 'B1'],
  ['enjoy', 'disfrutar', 'verbs_action', null, 'A2'],
  ['hate', 'odiar', 'verbs_action', null, 'A2'],
  ['prefer', 'preferir', 'verbs_action', null, 'A2'],
  ['worry', 'preocuparse', 'verbs_action', null, 'A2'],
  ['surprise', 'sorprender', 'other', null, 'A2'],
  ['interest', 'interesar', 'other', null, 'A2'],
  ['bother', 'molestar', 'other', null, 'B1'],
  ['care', 'importar/cuidar', 'other', null, 'A2'],
  ['mind', 'importar (molestar)', 'other', null, 'A2'],
  ['matter', 'importar', 'other', null, 'A2'],
  ['depend', 'depender', 'other', null, 'B1'],
  ['belong', 'pertenecer', 'other', null, 'B1'],
  ['contain', 'contener', 'other', null, 'B1'],
  ['exist', 'existir', 'other', null, 'B1'],
  ['produce', 'producir', 'other', null, 'B1'],
  ['develop', 'desarrollar', 'other', null, 'B1'],
  ['support', 'apoyar/soportar', 'other', null, 'B1'],
  ['protect', 'proteger', 'other', null, 'B1'],
  ['prevent', 'prevenir/evitar', 'other', null, 'B1'],
  ['avoid', 'evitar', 'other', null, 'B1'],
  ['cause', 'causar', 'other', null, 'B1'],
  ['affect', 'afectar', 'other', null, 'B1'],
  ['increase', 'aumentar', 'other', null, 'B1'],
  ['reduce', 'reducir', 'other', null, 'B1'],
  ['improve', 'mejorar', 'other', null, 'B1'],
  ['achieve', 'lograr', 'other', null, 'B1'],
  ['determine', 'determinar', 'other', null, 'B1'],
  ['identify', 'identificar', 'other', null, 'B1'],
  ['recognize', 'reconocer', 'other', null, 'B1'],
  ['introduce', 'presentar/introducir', 'other', null, 'B1'],
  ['mention', 'mencionar', 'other', null, 'B1'],
  ['claim', 'afirmar/reclamar', 'other', null, 'B1'],
  ['prove', 'probar/demostrar', 'other', null, 'B1'],
  ['confirm', 'confirmar', 'other', null, 'B1'],
  ['deny', 'negar', 'other', null, 'B1'],
  ['argue', 'discutir/argumentar', 'other', null, 'B1'],
  ['discuss', 'discutir/debatir', 'other', null, 'B1'],
  ['express', 'expresar', 'other', null, 'B1'],
  ['complain', 'quejarse', 'other', null, 'B1'],
  ['warn', 'advertir', 'other', null, 'B1'],
  ['threaten', 'amenazar', 'other', null, 'B2'],
  ['encourage', 'animar/alentar', 'other', null, 'B1'],
  ['convince', 'convencer', 'other', null, 'B1'],
  ['force', 'forzar/obligar', 'other', null, 'B1'],
  // === adjectives (400) ===
  ['happy', 'feliz', 'adjectives', null, 'A1'],
  ['sad', 'triste', 'adjectives', null, 'A1'],
  ['fast', 'rápido', 'adjectives', null, 'A1'],
  ['slow', 'lento', 'adjectives', null, 'A1'],
  ['beautiful', 'hermoso', 'adjectives', null, 'A1'],
  ['ugly', 'feo', 'adjectives', null, 'A2'],
  ['hot', 'caliente', 'adjectives', null, 'A1'],
  ['cold', 'frío', 'adjectives', null, 'A1'],
  ['young', 'joven', 'adjectives', null, 'A1'],
  ['strong', 'fuerte', 'adjectives', null, 'A1'],
  ['weak', 'débil', 'adjectives', null, 'A2'],
  ['rich', 'rico', 'adjectives', null, 'A2'],
  ['poor', 'pobre', 'adjectives', null, 'A2'],
  ['tall', 'alto', 'adjectives', null, 'A1'],
  ['short', 'bajo/corto', 'adjectives', null, 'A1'],
  ['thick', 'grueso', 'adjectives', null, 'A2'],
  ['thin', 'delgado/fino', 'adjectives', null, 'A2'],
  ['wide', 'ancho', 'adjectives', null, 'A2'],
  ['narrow', 'estrecho', 'adjectives', null, 'A2'],
  ['heavy', 'pesado', 'adjectives', null, 'A2'],
  ['light', 'ligero/liviano', 'adjectives', null, 'A2'],
  ['hard', 'duro/difícil', 'adjectives', null, 'A2'],
  ['soft', 'suave/blando', 'adjectives', null, 'A2'],
  ['easy', 'fácil', 'adjectives', null, 'A1'],
  ['difficult', 'difícil', 'adjectives', null, 'A2'],
  ['clean', 'limpio', 'adjectives', null, 'A1'],
  ['dirty', 'sucio', 'adjectives', null, 'A2'],
  ['wet', 'mojado', 'adjectives', null, 'A2'],
  ['dry', 'seco', 'adjectives', null, 'A2'],
  ['full', 'lleno', 'adjectives', null, 'A2'],
  ['empty', 'vacío', 'adjectives', null, 'A2'],
  ['safe', 'seguro', 'adjectives', null, 'A2'],
  ['dangerous', 'peligroso', 'adjectives', null, 'A2'],
  ['free', 'libre/gratis', 'adjectives', null, 'A2'],
  ['busy', 'ocupado', 'adjectives', null, 'A2'],
  ['quiet', 'tranquilo/silencioso', 'adjectives', null, 'A2'],
  ['loud', 'ruidoso', 'adjectives', null, 'A2'],
  ['bright', 'brillante', 'adjectives', null, 'A2'],
  ['dark', 'oscuro', 'adjectives', null, 'A1'],
  ['real', 'real/verdadero', 'adjectives', null, 'A2'],
  ['false', 'falso', 'adjectives', null, 'A2'],
  ['true', 'verdadero', 'adjectives', null, 'A2'],
  ['wrong', 'equivocado', 'adjectives', null, 'A2'],
  ['strange', 'extraño/raro', 'adjectives', null, 'A2'],
  ['familiar', 'familiar/conocido', 'adjectives', null, 'A2'],
  ['common', 'común', 'adjectives', null, 'B1'],
  ['rare', 'raro/poco común', 'adjectives', null, 'B1'],
  ['popular', 'popular', 'adjectives', null, 'A2'],
  ['famous', 'famoso', 'adjectives', null, 'A2'],
  ['important', 'importante', 'adjectives', null, 'A2'],
  ['necessary', 'necesario', 'adjectives', null, 'B1'],
  ['possible', 'posible', 'adjectives', null, 'A2'],
  ['impossible', 'imposible', 'adjectives', null, 'A2'],
  ['available', 'disponible', 'adjectives', null, 'B1'],
  ['similar', 'similar/parecido', 'adjectives', null, 'B1'],
  ['different', 'diferente', 'adjectives', null, 'A2'],
  ['special', 'especial', 'adjectives', null, 'A2'],
  ['normal', 'normal', 'adjectives', null, 'A2'],
  ['simple', 'simple/sencillo', 'adjectives', null, 'A2'],
  ['complex', 'complejo', 'adjectives', null, 'B1'],
  ['serious', 'serio', 'adjectives', null, 'A2'],
  ['funny', 'gracioso/divertido', 'adjectives', null, 'A2'],
  ['interesting', 'interesante', 'adjectives', null, 'A2'],
  ['boring', 'aburrido', 'adjectives', null, 'A2'],
  ['exciting', 'emocionante', 'adjectives', null, 'B1'],
  ['wonderful', 'maravilloso', 'adjectives', null, 'A2'],
  ['terrible', 'terrible', 'adjectives', null, 'A2'],
  ['awful', 'horrible', 'adjectives', null, 'B1'],
  ['pleasant', 'agradable', 'adjectives', null, 'B1'],
  ['unpleasant', 'desagradable', 'adjectives', null, 'B1'],
  ['comfortable', 'cómodo', 'adjectives', null, 'A2'],
  ['uncomfortable', 'incómodo', 'adjectives', null, 'B1'],
  ['fresh', 'fresco', 'adjectives', null, 'A2'],
  ['stale', 'rancio/pasado', 'adjectives', null, 'B2'],
  ['sweet', 'dulce', 'adjectives', null, 'A2'],
  ['salty', 'salado', 'adjectives', null, 'A2'],
  ['sour', 'agrio/ácido', 'adjectives', null, 'A2'],
  ['bitter', 'amargo', 'adjectives', null, 'A2'],
  ['spicy', 'picante', 'adjectives', null, 'A2'],
  ['delicious', 'delicioso', 'adjectives', null, 'A2'],
  ['hungry', 'hambriento', 'adjectives', null, 'A1'],
  ['thirsty', 'sediento', 'adjectives', null, 'A1'],
  ['tired', 'cansado', 'adjectives', null, 'A1'],
  ['healthy', 'saludable', 'adjectives', null, 'A2'],
  ['sick', 'enfermo', 'adjectives', null, 'A1'],
  ['alive', 'vivo', 'adjectives', null, 'A2'],
  ['dead', 'muerto', 'adjectives', null, 'A2'],
  ['alone', 'solo', 'adjectives', null, 'A2'],
  ['together', 'juntos', 'adjectives', null, 'A2'],
  ['ready', 'listo/preparado', 'adjectives', null, 'A2'],
  ['late', 'tarde', 'adjectives', null, 'A1'],
  ['early', 'temprano', 'adjectives', null, 'A2'],
  ['expensive', 'caro/costoso', 'adjectives', null, 'A2'],
  ['cheap', 'barato', 'adjectives', null, 'A2'],
  ['kind', 'amable', 'adjectives', null, 'A2'],
  ['cruel', 'cruel', 'adjectives', null, 'B1'],
  ['brave', 'valiente', 'adjectives', null, 'B1'],
  ['afraid', 'asustado/con miedo', 'adjectives', null, 'A2'],
  ['proud', 'orgulloso', 'adjectives', null, 'B1'],
  ['ashamed', 'avergonzado', 'adjectives', null, 'B1'],
  ['jealous', 'celoso', 'adjectives', null, 'B1'],
  ['curious', 'curioso', 'adjectives', null, 'B1'],
  ['confident', 'seguro de sí mismo', 'adjectives', null, 'B1'],
  ['shy', 'tímido', 'adjectives', null, 'A2'],
  // === home (200) ===
  ['house', 'casa', 'home', null, 'A1'],
  ['room', 'habitación/cuarto', 'home', null, 'A1'],
  ['door', 'puerta', 'home', null, 'A1'],
  ['window', 'ventana', 'home', null, 'A1'],
  ['wall', 'pared/muro', 'home', null, 'A1'],
  ['floor', 'piso/suelo', 'home', null, 'A2'],
  ['ceiling', 'techo (interior)', 'home', null, 'A2'],
  ['roof', 'techo (exterior)', 'home', null, 'A2'],
  ['table', 'mesa', 'home', null, 'A1'],
  ['chair', 'silla', 'home', null, 'A1'],
  ['bed', 'cama', 'home', null, 'A1'],
  ['sofa', 'sofá', 'home', null, 'A2'],
  ['desk', 'escritorio', 'home', null, 'A2'],
  ['shelf', 'estante/repisa', 'home', null, 'A2'],
  ['closet', 'armario/placard', 'home', null, 'A2'],
  ['drawer', 'cajón', 'home', null, 'A2'],
  ['mirror', 'espejo', 'home', null, 'A2'],
  ['lamp', 'lámpara', 'home', null, 'A2'],
  ['light', 'luz', 'home', null, 'A1'],
  ['kitchen', 'cocina', 'home', null, 'A1'],
  ['bathroom', 'baño', 'home', null, 'A1'],
  ['bedroom', 'dormitorio', 'home', null, 'A1'],
  ['living room', 'sala de estar', 'home', null, 'A2'],
  ['dining room', 'comedor', 'home', null, 'A2'],
  ['garage', 'garaje/cochera', 'home', null, 'A2'],
  ['garden', 'jardín', 'home', null, 'A2'],
  ['yard', 'patio', 'home', null, 'A2'],
  ['stairs', 'escaleras', 'home', null, 'A2'],
  ['hallway', 'pasillo', 'home', null, 'A2'],
  ['furniture', 'muebles', 'home', null, 'A2'],
  ['refrigerator', 'heladera/refrigerador', 'home', null, 'A2'],
  ['stove', 'cocina/hornalla', 'home', null, 'A2'],
  ['oven', 'horno', 'home', null, 'A2'],
  ['microwave', 'microondas', 'home', null, 'A2'],
  ['sink', 'lavabo/pileta', 'home', null, 'A2'],
  ['faucet', 'grifo/canilla', 'home', null, 'B1'],
  ['shower', 'ducha', 'home', null, 'A2'],
  ['bathtub', 'bañera', 'home', null, 'A2'],
  ['toilet', 'inodoro', 'home', null, 'A2'],
  ['towel', 'toalla', 'home', null, 'A2'],
  ['soap', 'jabón', 'home', null, 'A2'],
  ['pillow', 'almohada', 'home', null, 'A2'],
  ['blanket', 'frazada/manta', 'home', null, 'A2'],
  ['sheet', 'sábana', 'home', null, 'A2'],
  ['curtain', 'cortina', 'home', null, 'A2'],
  ['carpet', 'alfombra', 'home', null, 'A2'],
  ['rug', 'alfombra pequeña', 'home', null, 'B1'],
  ['clock', 'reloj (pared)', 'home', null, 'A1'],
  ['television', 'televisor', 'home', null, 'A1'],
  ['radio', 'radio', 'home', null, 'A1'],
  // === family (80) ===
  ['mother', 'madre', 'family', null, 'A1'],
  ['father', 'padre', 'family', null, 'A1'],
  ['parent', 'padre/madre', 'family', null, 'A1'],
  ['son', 'hijo', 'family', null, 'A1'],
  ['daughter', 'hija', 'family', null, 'A1'],
  ['brother', 'hermano', 'family', null, 'A1'],
  ['sister', 'hermana', 'family', null, 'A1'],
  ['husband', 'esposo/marido', 'family', null, 'A2'],
  ['wife', 'esposa', 'family', null, 'A2'],
  ['uncle', 'tío', 'family', null, 'A2'],
  ['aunt', 'tía', 'family', null, 'A2'],
  ['cousin', 'primo/a', 'family', null, 'A2'],
  ['grandfather', 'abuelo', 'family', null, 'A2'],
  ['grandmother', 'abuela', 'family', null, 'A2'],
  ['grandson', 'nieto', 'family', null, 'A2'],
  ['granddaughter', 'nieta', 'family', null, 'A2'],
  ['nephew', 'sobrino', 'family', null, 'B1'],
  ['niece', 'sobrina', 'family', null, 'B1'],
  ['baby', 'bebé', 'family', null, 'A1'],
  ['twin', 'gemelo/mellizo', 'family', null, 'B1'],
  ['relative', 'pariente/familiar', 'family', null, 'A2'],
  ['neighbor', 'vecino', 'family', null, 'A2'],
  ['friend', 'amigo', 'family', null, 'A1'],
  ['boyfriend', 'novio', 'family', null, 'A2'],
  ['girlfriend', 'novia', 'family', null, 'A2'],
  ['partner', 'pareja/compañero', 'family', null, 'B1'],
  ['couple', 'pareja (dos)', 'family', null, 'A2'],
  ['marriage', 'matrimonio', 'family', null, 'B1'],
  ['wedding', 'boda/casamiento', 'family', null, 'A2'],
  // === body (150) ===
  ['head', 'cabeza', 'body', null, 'A1'],
  ['face', 'cara/rostro', 'body', null, 'A1'],
  ['hair', 'pelo/cabello', 'body', null, 'A1'],
  ['eye', 'ojo', 'body', null, 'A1'],
  ['nose', 'nariz', 'body', null, 'A1'],
  ['mouth', 'boca', 'body', null, 'A1'],
  ['ear', 'oreja/oído', 'body', null, 'A1'],
  ['neck', 'cuello', 'body', null, 'A2'],
  ['shoulder', 'hombro', 'body', null, 'A2'],
  ['arm', 'brazo', 'body', null, 'A1'],
  ['elbow', 'codo', 'body', null, 'A2'],
  ['wrist', 'muñeca', 'body', null, 'A2'],
  ['finger', 'dedo (mano)', 'body', null, 'A1'],
  ['thumb', 'pulgar', 'body', null, 'A2'],
  ['chest', 'pecho', 'body', null, 'A2'],
  ['back', 'espalda', 'body', null, 'A1'],
  ['stomach', 'estómago', 'body', null, 'A2'],
  ['waist', 'cintura', 'body', null, 'A2'],
  ['hip', 'cadera', 'body', null, 'A2'],
  ['leg', 'pierna', 'body', null, 'A1'],
  ['knee', 'rodilla', 'body', null, 'A2'],
  ['ankle', 'tobillo', 'body', null, 'A2'],
  ['foot', 'pie', 'body', null, 'A1'],
  ['toe', 'dedo (pie)', 'body', null, 'A2'],
  ['skin', 'piel', 'body', null, 'A2'],
  ['bone', 'hueso', 'body', null, 'A2'],
  ['muscle', 'músculo', 'body', null, 'B1'],
  ['blood', 'sangre', 'body', null, 'A2'],
  ['heart', 'corazón', 'body', null, 'A1'],
  ['brain', 'cerebro', 'body', null, 'A2'],
  ['lung', 'pulmón', 'body', null, 'B1'],
  ['liver', 'hígado', 'body', null, 'B1'],
  ['kidney', 'riñón', 'body', null, 'B1'],
  ['tongue', 'lengua', 'body', null, 'A2'],
  ['tooth', 'diente', 'body', null, 'A1'],
  ['lip', 'labio', 'body', null, 'A2'],
  ['chin', 'mentón/barbilla', 'body', null, 'A2'],
  ['forehead', 'frente', 'body', null, 'A2'],
  ['cheek', 'mejilla/cachete', 'body', null, 'A2'],
  ['eyebrow', 'ceja', 'body', null, 'B1'],
  // === health (200) ===
  ['doctor', 'médico/doctor', 'health', null, 'A1'],
  ['nurse', 'enfermero/a', 'health', null, 'A2'],
  ['hospital', 'hospital', 'health', null, 'A1'],
  ['medicine', 'medicina/medicamento', 'health', null, 'A2'],
  ['pill', 'pastilla/píldora', 'health', null, 'A2'],
  ['pharmacy', 'farmacia', 'health', null, 'A2'],
  ['patient', 'paciente', 'health', null, 'B1'],
  ['surgery', 'cirugía', 'health', null, 'B1'],
  ['emergency', 'emergencia', 'health', null, 'B1'],
  ['ambulance', 'ambulancia', 'health', null, 'B1'],
  ['pain', 'dolor', 'health', null, 'A2'],
  ['injury', 'lesión/herida', 'health', null, 'B1'],
  ['wound', 'herida', 'health', null, 'B1'],
  ['broken', 'roto/fracturado', 'health', null, 'A2'],
  ['fever', 'fiebre', 'health', null, 'A2'],
  ['cough', 'tos', 'health', null, 'A2'],
  ['cold', 'resfrío', 'health', null, 'A1'],
  ['flu', 'gripe', 'health', null, 'A2'],
  ['virus', 'virus', 'health', null, 'B1'],
  ['infection', 'infección', 'health', null, 'B1'],
  ['vaccine', 'vacuna', 'health', null, 'B1'],
  ['allergy', 'alergia', 'health', null, 'B1'],
  ['prescription', 'receta médica', 'health', null, 'B1'],
  ['treatment', 'tratamiento', 'health', null, 'B1'],
  ['recovery', 'recuperación', 'health', null, 'B1'],
  ['diet', 'dieta', 'health', null, 'A2'],
  ['exercise', 'ejercicio', 'health', null, 'A2'],
  ['weight', 'peso', 'health', null, 'A2'],
  ['blood pressure', 'presión arterial', 'health', null, 'B1'],
  ['symptom', 'síntoma', 'health', null, 'B1'],
  ['diagnosis', 'diagnóstico', 'health', null, 'B1'],
  ['operation', 'operación', 'health', null, 'B1'],
  ['wheelchair', 'silla de ruedas', 'health', null, 'B1'],
  ['crutch', 'muleta', 'health', null, 'B2'],
  ['bandage', 'vendaje/venda', 'health', null, 'B1'],
  ['syringe', 'jeringa', 'health', null, 'B1'],
  ['X-ray', 'radiografía', 'health', null, 'B1'],
  ['therapy', 'terapia', 'health', null, 'B1'],
  ['mental health', 'salud mental', 'health', null, 'B1'],
  ['headache', 'dolor de cabeza', 'health', null, 'A2'],
  ['stomachache', 'dolor de estómago', 'health', null, 'A2'],
  ['toothache', 'dolor de muelas', 'health', null, 'B1'],
  ['dentist', 'dentista', 'health', null, 'A2'],
  ['glasses', 'anteojos/lentes', 'health', null, 'A2'],
  // === food_drink (350) ===
  ['apple', 'manzana', 'food_drink', 'fruits', 'A1'],
  ['banana', 'banana/plátano', 'food_drink', 'fruits', 'A1'],
  ['orange', 'naranja', 'food_drink', 'fruits', 'A1'],
  ['grape', 'uva', 'food_drink', 'fruits', 'A2'],
  ['strawberry', 'frutilla/fresa', 'food_drink', 'fruits', 'A2'],
  ['lemon', 'limón', 'food_drink', 'fruits', 'A2'],
  ['pineapple', 'piña/ananá', 'food_drink', 'fruits', 'A2'],
  ['watermelon', 'sandía', 'food_drink', 'fruits', 'A2'],
  ['peach', 'durazno/melocotón', 'food_drink', 'fruits', 'A2'],
  ['cherry', 'cereza', 'food_drink', 'fruits', 'A2'],
  ['mango', 'mango', 'food_drink', 'fruits', 'A2'],
  ['pear', 'pera', 'food_drink', 'fruits', 'A2'],
  ['tomato', 'tomate', 'food_drink', 'vegetables', 'A1'],
  ['potato', 'papa/patata', 'food_drink', 'vegetables', 'A1'],
  ['onion', 'cebolla', 'food_drink', 'vegetables', 'A2'],
  ['garlic', 'ajo', 'food_drink', 'vegetables', 'A2'],
  ['carrot', 'zanahoria', 'food_drink', 'vegetables', 'A2'],
  ['lettuce', 'lechuga', 'food_drink', 'vegetables', 'A2'],
  ['broccoli', 'brócoli', 'food_drink', 'vegetables', 'A2'],
  ['cucumber', 'pepino', 'food_drink', 'vegetables', 'A2'],
  ['pepper', 'pimiento/morron', 'food_drink', 'vegetables', 'A2'],
  ['corn', 'maíz/choclo', 'food_drink', 'vegetables', 'A2'],
  ['rice', 'arroz', 'food_drink', 'grains', 'A1'],
  ['bread', 'pan', 'food_drink', 'grains', 'A1'],
  ['pasta', 'pasta/fideos', 'food_drink', 'grains', 'A2'],
  ['flour', 'harina', 'food_drink', 'grains', 'B1'],
  ['sugar', 'azúcar', 'food_drink', null, 'A1'],
  ['salt', 'sal', 'food_drink', null, 'A1'],
  ['oil', 'aceite', 'food_drink', null, 'A2'],
  ['butter', 'manteca/mantequilla', 'food_drink', null, 'A2'],
  ['egg', 'huevo', 'food_drink', null, 'A1'],
  ['cheese', 'queso', 'food_drink', 'dairy', 'A1'],
  ['milk', 'leche', 'food_drink', 'dairy', 'A1'],
  ['yogurt', 'yogur', 'food_drink', 'dairy', 'A2'],
  ['cream', 'crema', 'food_drink', 'dairy', 'A2'],
  ['ice cream', 'helado', 'food_drink', 'dairy', 'A1'],
  ['chicken', 'pollo', 'food_drink', 'meat', 'A1'],
  ['beef', 'carne de vaca', 'food_drink', 'meat', 'A2'],
  ['pork', 'cerdo', 'food_drink', 'meat', 'A2'],
  ['fish', 'pescado', 'food_drink', 'seafood', 'A1'],
  ['shrimp', 'camarón', 'food_drink', 'seafood', 'A2'],
  ['soup', 'sopa', 'food_drink', null, 'A2'],
  ['salad', 'ensalada', 'food_drink', null, 'A2'],
  ['sandwich', 'sándwich/emparedado', 'food_drink', null, 'A2'],
  ['pizza', 'pizza', 'food_drink', null, 'A1'],
  ['cake', 'torta/pastel', 'food_drink', 'desserts', 'A1'],
  ['cookie', 'galleta', 'food_drink', 'desserts', 'A2'],
  ['chocolate', 'chocolate', 'food_drink', 'desserts', 'A1'],
  ['candy', 'caramelo/golosina', 'food_drink', 'desserts', 'A2'],
  ['coffee', 'café', 'food_drink', 'beverages', 'A1'],
  ['tea', 'té', 'food_drink', 'beverages', 'A1'],
  ['juice', 'jugo/zumo', 'food_drink', 'beverages', 'A1'],
  ['beer', 'cerveza', 'food_drink', 'beverages', 'A2'],
  ['wine', 'vino', 'food_drink', 'beverages', 'A2'],
  ['soda', 'gaseosa/refresco', 'food_drink', 'beverages', 'A2'],
  ['lemonade', 'limonada', 'food_drink', 'beverages', 'A2'],
  ['breakfast', 'desayuno', 'food_drink', 'meals', 'A1'],
  ['lunch', 'almuerzo', 'food_drink', 'meals', 'A1'],
  ['dinner', 'cena', 'food_drink', 'meals', 'A1'],
  ['snack', 'merienda/tentempié', 'food_drink', null, 'A2'],
  ['meal', 'comida', 'food_drink', null, 'A2'],
  // === clothing (120) ===
  ['shirt', 'camisa', 'clothing', null, 'A1'],
  ['pants', 'pantalones', 'clothing', null, 'A1'],
  ['shoes', 'zapatos', 'clothing', null, 'A1'],
  ['hat', 'sombrero/gorro', 'clothing', null, 'A1'],
  ['jacket', 'campera/chaqueta', 'clothing', null, 'A2'],
  ['coat', 'abrigo/tapado', 'clothing', null, 'A2'],
  ['sweater', 'suéter/buzo', 'clothing', null, 'A2'],
  ['dress', 'vestido', 'clothing', null, 'A1'],
  ['skirt', 'pollera/falda', 'clothing', null, 'A2'],
  ['socks', 'medias/calcetines', 'clothing', null, 'A1'],
  ['belt', 'cinturón', 'clothing', null, 'A2'],
  ['tie', 'corbata', 'clothing', null, 'A2'],
  ['scarf', 'bufanda', 'clothing', null, 'A2'],
  ['glove', 'guante', 'clothing', null, 'A2'],
  ['boot', 'bota', 'clothing', null, 'A2'],
  ['sandal', 'sandalia', 'clothing', null, 'A2'],
  ['sneaker', 'zapatilla', 'clothing', null, 'A2'],
  ['suit', 'traje', 'clothing', null, 'A2'],
  ['uniform', 'uniforme', 'clothing', null, 'B1'],
  ['pajamas', 'pijama', 'clothing', null, 'A2'],
  ['swimsuit', 'traje de baño', 'clothing', null, 'A2'],
  ['underwear', 'ropa interior', 'clothing', null, 'A2'],
  ['pocket', 'bolsillo', 'clothing', null, 'A2'],
  ['button', 'botón', 'clothing', null, 'A2'],
  ['zipper', 'cierre/cremallera', 'clothing', null, 'B1'],
  ['cotton', 'algodón', 'clothing', null, 'A2'],
  ['wool', 'lana', 'clothing', null, 'A2'],
  ['silk', 'seda', 'clothing', null, 'B1'],
  ['leather', 'cuero', 'clothing', null, 'A2'],
  ['jewelry', 'joyería', 'clothing', null, 'A2'],
  ['ring', 'anillo', 'clothing', null, 'A2'],
  ['necklace', 'collar', 'clothing', null, 'A2'],
  ['earring', 'arete/pendiente', 'clothing', null, 'A2'],
  ['watch', 'reloj (pulsera)', 'clothing', null, 'A1'],
  ['bag', 'bolsa/cartera', 'clothing', null, 'A2'],
  ['backpack', 'mochila', 'clothing', null, 'A2'],
  ['wallet', 'billetera/cartera', 'clothing', null, 'A2'],
  // === nature (250) ===
  ['tree', 'árbol', 'nature', null, 'A1'],
  ['flower', 'flor', 'nature', null, 'A1'],
  ['grass', 'césped/pasto', 'nature', null, 'A2'],
  ['leaf', 'hoja (planta)', 'nature', null, 'A2'],
  ['forest', 'bosque', 'nature', null, 'A2'],
  ['mountain', 'montaña', 'nature', null, 'A2'],
  ['river', 'río', 'nature', null, 'A1'],
  ['lake', 'lago', 'nature', null, 'A2'],
  ['ocean', 'océano', 'nature', null, 'A2'],
  ['sea', 'mar', 'nature', null, 'A1'],
  ['beach', 'playa', 'nature', null, 'A1'],
  ['island', 'isla', 'nature', null, 'A2'],
  ['desert', 'desierto', 'nature', null, 'A2'],
  ['sky', 'cielo', 'nature', null, 'A1'],
  ['cloud', 'nube', 'nature', null, 'A2'],
  ['rain', 'lluvia', 'nature', null, 'A1'],
  ['snow', 'nieve', 'nature', null, 'A2'],
  ['wind', 'viento', 'nature', null, 'A2'],
  ['storm', 'tormenta', 'nature', null, 'A2'],
  ['thunder', 'trueno', 'nature', null, 'B1'],
  ['lightning', 'relámpago/rayo', 'nature', null, 'B1'],
  ['sun', 'sol', 'nature', null, 'A1'],
  ['moon', 'luna', 'nature', null, 'A1'],
  ['star', 'estrella', 'nature', null, 'A1'],
  ['planet', 'planeta', 'nature', null, 'A2'],
  ['earth', 'tierra', 'nature', null, 'A2'],
  ['fire', 'fuego', 'nature', null, 'A1'],
  ['ice', 'hielo', 'nature', null, 'A2'],
  ['rock', 'roca/piedra', 'nature', null, 'A2'],
  ['stone', 'piedra', 'nature', null, 'A2'],
  ['sand', 'arena', 'nature', null, 'A2'],
  ['soil', 'suelo/tierra', 'nature', null, 'B1'],
  ['cave', 'cueva/caverna', 'nature', null, 'B1'],
  ['volcano', 'volcán', 'nature', null, 'B1'],
  ['earthquake', 'terremoto/sismo', 'nature', null, 'B1'],
  ['flood', 'inundación', 'nature', null, 'B1'],
  ['rainbow', 'arcoíris', 'nature', null, 'A2'],
  ['sunrise', 'amanecer/salida del sol', 'nature', null, 'B1'],
  ['sunset', 'atardecer/puesta del sol', 'nature', null, 'A2'],
  // === animals (200) ===
  ['dog', 'perro', 'animals', 'pets', 'A1'],
  ['cat', 'gato', 'animals', 'pets', 'A1'],
  ['bird', 'pájaro/ave', 'animals', 'birds', 'A1'],
  ['fish', 'pez', 'animals', 'sea', 'A1'],
  ['horse', 'caballo', 'animals', 'farm', 'A1'],
  ['cow', 'vaca', 'animals', 'farm', 'A1'],
  ['pig', 'cerdo/chancho', 'animals', 'farm', 'A2'],
  ['sheep', 'oveja', 'animals', 'farm', 'A2'],
  ['goat', 'cabra', 'animals', 'farm', 'A2'],
  ['chicken', 'pollo/gallina', 'animals', 'farm', 'A1'],
  ['duck', 'pato', 'animals', 'birds', 'A2'],
  ['rabbit', 'conejo', 'animals', 'pets', 'A2'],
  ['mouse', 'ratón', 'animals', null, 'A2'],
  ['rat', 'rata', 'animals', null, 'A2'],
  ['snake', 'serpiente/víbora', 'animals', 'wild', 'A2'],
  ['frog', 'rana', 'animals', null, 'A2'],
  ['turtle', 'tortuga', 'animals', 'sea', 'A2'],
  ['lion', 'león', 'animals', 'wild', 'A2'],
  ['tiger', 'tigre', 'animals', 'wild', 'A2'],
  ['elephant', 'elefante', 'animals', 'wild', 'A2'],
  ['bear', 'oso', 'animals', 'wild', 'A2'],
  ['wolf', 'lobo', 'animals', 'wild', 'B1'],
  ['fox', 'zorro', 'animals', 'wild', 'B1'],
  ['deer', 'ciervo/venado', 'animals', 'wild', 'B1'],
  ['monkey', 'mono', 'animals', 'wild', 'A2'],
  ['gorilla', 'gorila', 'animals', 'wild', 'B1'],
  ['dolphin', 'delfín', 'animals', 'sea', 'B1'],
  ['whale', 'ballena', 'animals', 'sea', 'A2'],
  ['shark', 'tiburón', 'animals', 'sea', 'A2'],
  ['eagle', 'águila', 'animals', 'birds', 'B1'],
  ['parrot', 'loro', 'animals', 'birds', 'B1'],
  ['penguin', 'pingüino', 'animals', 'birds', 'A2'],
  ['butterfly', 'mariposa', 'animals', 'insects', 'A2'],
  ['bee', 'abeja', 'animals', 'insects', 'A2'],
  ['ant', 'hormiga', 'animals', 'insects', 'A2'],
  ['spider', 'araña', 'animals', 'insects', 'A2'],
  // === technology (150) ===
  ['computer', 'computadora', 'technology', null, 'A1'],
  ['phone', 'teléfono', 'technology', null, 'A1'],
  ['internet', 'internet', 'technology', null, 'A1'],
  ['website', 'sitio web/página web', 'technology', null, 'A2'],
  ['email', 'correo electrónico', 'technology', null, 'A2'],
  ['password', 'contraseña', 'technology', null, 'A2'],
  ['screen', 'pantalla', 'technology', null, 'A2'],
  ['keyboard', 'teclado', 'technology', null, 'A2'],
  ['mouse', 'ratón (computadora)', 'technology', null, 'A2'],
  ['printer', 'impresora', 'technology', null, 'A2'],
  ['camera', 'cámara', 'technology', null, 'A2'],
  ['video', 'video', 'technology', null, 'A2'],
  ['app', 'aplicación', 'technology', null, 'A2'],
  ['software', 'software/programa', 'technology', null, 'B1'],
  ['hardware', 'hardware', 'technology', null, 'B1'],
  ['data', 'datos', 'technology', null, 'B1'],
  ['file', 'archivo', 'technology', null, 'A2'],
  ['folder', 'carpeta', 'technology', null, 'A2'],
  ['download', 'descargar', 'technology', null, 'A2'],
  ['upload', 'subir/cargar', 'technology', null, 'B1'],
  ['network', 'red', 'technology', null, 'B1'],
  ['Wi-Fi', 'Wi-Fi', 'technology', null, 'A2'],
  ['Bluetooth', 'Bluetooth', 'technology', null, 'B1'],
  ['battery', 'batería', 'technology', null, 'A2'],
  ['charger', 'cargador', 'technology', null, 'A2'],
  ['cable', 'cable', 'technology', null, 'A2'],
  ['robot', 'robot', 'technology', null, 'B1'],
  ['search engine', 'buscador', 'technology', null, 'B1'],
  ['social media', 'redes sociales', 'technology', null, 'B1'],
  ['online', 'en línea/conectado', 'technology', null, 'A2'],
  // === transport (150) ===
  ['car', 'auto/coche', 'transport', null, 'A1'],
  ['bus', 'colectivo/autobús', 'transport', null, 'A1'],
  ['train', 'tren', 'transport', null, 'A1'],
  ['airplane', 'avión', 'transport', null, 'A2'],
  ['boat', 'barco/bote', 'transport', null, 'A2'],
  ['ship', 'barco (grande)', 'transport', null, 'A2'],
  ['bicycle', 'bicicleta', 'transport', null, 'A1'],
  ['motorcycle', 'moto/motocicleta', 'transport', null, 'A2'],
  ['taxi', 'taxi', 'transport', null, 'A2'],
  ['truck', 'camión', 'transport', null, 'A2'],
  ['subway', 'subte/metro', 'transport', null, 'A2'],
  ['helicopter', 'helicóptero', 'transport', null, 'B1'],
  ['ferry', 'ferry/transbordador', 'transport', null, 'B1'],
  ['ambulance', 'ambulancia', 'transport', null, 'B1'],
  ['traffic', 'tráfico/tránsito', 'transport', null, 'A2'],
  ['highway', 'autopista', 'transport', null, 'B1'],
  ['road', 'camino/calle', 'transport', null, 'A2'],
  ['street', 'calle', 'transport', null, 'A1'],
  ['bridge', 'puente', 'transport', null, 'A2'],
  ['tunnel', 'túnel', 'transport', null, 'B1'],
  ['parking', 'estacionamiento', 'transport', null, 'A2'],
  ['gas station', 'estación de servicio/gasolinera', 'transport', null, 'A2'],
  ['driver', 'conductor/chofer', 'transport', null, 'A2'],
  ['passenger', 'pasajero', 'transport', null, 'A2'],
  ['ticket', 'boleto/pasaje', 'transport', null, 'A2'],
  ['stop', 'parada', 'transport', null, 'A2'],
  ['station', 'estación', 'transport', null, 'A2'],
  ['wheel', 'rueda', 'transport', null, 'A2'],
  ['engine', 'motor', 'transport', null, 'B1'],
  ['seat belt', 'cinturón de seguridad', 'transport', null, 'A2'],
  // === education (120) ===
  ['school', 'escuela/colegio', 'education', null, 'A1'],
  ['teacher', 'maestro/profesor', 'education', null, 'A1'],
  ['student', 'estudiante/alumno', 'education', null, 'A1'],
  ['class', 'clase', 'education', null, 'A2'],
  ['lesson', 'lección', 'education', null, 'A2'],
  ['homework', 'tarea/deberes', 'education', null, 'A2'],
  ['exam', 'examen/prueba', 'education', null, 'A2'],
  ['grade', 'nota/calificación', 'education', null, 'A2'],
  ['university', 'universidad', 'education', null, 'A2'],
  ['college', 'universidad/facultad', 'education', null, 'A2'],
  ['degree', 'título/grado', 'education', null, 'B1'],
  ['library', 'biblioteca', 'education', null, 'A2'],
  ['laboratory', 'laboratorio', 'education', null, 'B1'],
  ['science', 'ciencia', 'education', null, 'B1'],
  ['math', 'matemática', 'education', null, 'A2'],
  ['history', 'historia', 'education', null, 'A2'],
  ['geography', 'geografía', 'education', null, 'A2'],
  ['language', 'idioma/lengua', 'education', null, 'A2'],
  ['dictionary', 'diccionario', 'education', null, 'A2'],
  ['notebook', 'cuaderno/libreta', 'education', null, 'A2'],
  ['pencil', 'lápiz', 'education', null, 'A1'],
  ['pen', 'lapicera/bolígrafo', 'education', null, 'A1'],
  ['eraser', 'goma de borrar', 'education', null, 'A2'],
  ['ruler', 'regla', 'education', null, 'A2'],
  ['backpack', 'mochila', 'education', null, 'A2'],
  ['blackboard', 'pizarrón/pizarra', 'education', null, 'A2'],
  ['semester', 'semestre', 'education', null, 'B1'],
  ['scholarship', 'beca', 'education', null, 'B1'],
  ['graduation', 'graduación', 'education', null, 'B1'],
  ['course', 'curso', 'education', null, 'A2'],
  // === sports (120) ===
  ['soccer', 'fútbol', 'sports', null, 'A1'],
  ['basketball', 'básquet/baloncesto', 'sports', null, 'A1'],
  ['tennis', 'tenis', 'sports', null, 'A2'],
  ['swimming', 'natación', 'sports', null, 'A1'],
  ['running', 'correr/carrera', 'sports', null, 'A2'],
  ['cycling', 'ciclismo', 'sports', null, 'A2'],
  ['golf', 'golf', 'sports', null, 'B1'],
  ['baseball', 'béisbol', 'sports', null, 'A2'],
  ['volleyball', 'voleibol/vóley', 'sports', null, 'A2'],
  ['boxing', 'boxeo', 'sports', null, 'A2'],
  ['gym', 'gimnasio', 'sports', null, 'A2'],
  ['yoga', 'yoga', 'sports', null, 'A2'],
  ['team', 'equipo', 'sports', null, 'A2'],
  ['player', 'jugador', 'sports', null, 'A2'],
  ['coach', 'entrenador/director técnico', 'sports', null, 'A2'],
  ['game', 'juego/partido', 'sports', null, 'A2'],
  ['match', 'partido/encuentro', 'sports', null, 'A2'],
  ['score', 'puntuación/marcador', 'sports', null, 'A2'],
  ['goal', 'gol/meta', 'sports', null, 'A2'],
  ['medal', 'medalla', 'sports', null, 'A2'],
  ['trophy', 'trofeo', 'sports', null, 'B1'],
  ['stadium', 'estadio', 'sports', null, 'B1'],
  ['champion', 'campeón', 'sports', null, 'A2'],
  ['competition', 'competencia/competición', 'sports', null, 'B1'],
  ['tournament', 'torneo', 'sports', null, 'B1'],
  ['Olympics', 'Juegos Olímpicos', 'sports', null, 'B1'],
  ['ball', 'pelota/balón', 'sports', null, 'A1'],
  ['racket', 'raqueta', 'sports', null, 'B1'],
  ['helmet', 'casco', 'sports', null, 'A2'],
  ['uniform', 'uniforme', 'sports', null, 'B1'],
  // === emotions (150) ===
  ['love', 'amor', 'emotions', null, 'A1'],
  ['hate', 'odio', 'emotions', null, 'A2'],
  ['fear', 'miedo', 'emotions', null, 'A2'],
  ['anger', 'enojo/ira', 'emotions', null, 'B1'],
  ['joy', 'alegría', 'emotions', null, 'B1'],
  ['sadness', 'tristeza', 'emotions', null, 'B1'],
  ['surprise', 'sorpresa', 'emotions', null, 'A2'],
  ['disgust', 'asco/repulsión', 'emotions', null, 'B1'],
  ['trust', 'confianza', 'emotions', null, 'B1'],
  ['jealousy', 'celos/envidia', 'emotions', null, 'B1'],
  ['hope', 'esperanza', 'emotions', null, 'A2'],
  ['regret', 'arrepentimiento', 'emotions', null, 'B1'],
  ['shame', 'vergüenza', 'emotions', null, 'B1'],
  ['guilt', 'culpa', 'emotions', null, 'B1'],
  ['gratitude', 'gratitud', 'emotions', null, 'B1'],
  ['pride', 'orgullo', 'emotions', null, 'B1'],
  ['relief', 'alivio', 'emotions', null, 'B1'],
  ['boredom', 'aburrimiento', 'emotions', null, 'B1'],
  ['excitement', 'emoción/entusiasmo', 'emotions', null, 'B1'],
  ['confusion', 'confusión', 'emotions', null, 'B1'],
  // === colors (60) ===
  ['red', 'rojo', 'colors_shapes', null, 'A1'],
  ['blue', 'azul', 'colors_shapes', null, 'A1'],
  ['green', 'verde', 'colors_shapes', null, 'A1'],
  ['yellow', 'amarillo', 'colors_shapes', null, 'A1'],
  ['black', 'negro', 'colors_shapes', null, 'A1'],
  ['white', 'blanco', 'colors_shapes', null, 'A1'],
  ['orange', 'naranja', 'colors_shapes', null, 'A1'],
  ['purple', 'púrpura/morado', 'colors_shapes', null, 'A2'],
  ['pink', 'rosa/rosado', 'colors_shapes', null, 'A2'],
  ['brown', 'marrón/café', 'colors_shapes', null, 'A2'],
  ['gray', 'gris', 'colors_shapes', null, 'A2'],
  ['gold', 'dorado/oro', 'colors_shapes', null, 'A2'],
  ['silver', 'plateado', 'colors_shapes', null, 'A2'],
  ['circle', 'círculo', 'colors_shapes', null, 'A2'],
  ['square', 'cuadrado', 'colors_shapes', null, 'A2'],
  ['triangle', 'triángulo', 'colors_shapes', null, 'A2'],
  ['rectangle', 'rectángulo', 'colors_shapes', null, 'A2'],
  ['oval', 'óvalo', 'colors_shapes', null, 'B1'],
  ['star', 'estrella', 'colors_shapes', null, 'A2'],
  ['heart', 'corazón', 'colors_shapes', null, 'A2'],
  // === numbers_time (80) ===
  ['three', 'tres', 'numbers_time', null, 'A1'],
  ['four', 'cuatro', 'numbers_time', null, 'A1'],
  ['five', 'cinco', 'numbers_time', null, 'A1'],
  ['six', 'seis', 'numbers_time', null, 'A1'],
  ['seven', 'siete', 'numbers_time', null, 'A1'],
  ['eight', 'ocho', 'numbers_time', null, 'A1'],
  ['nine', 'nueve', 'numbers_time', null, 'A1'],
  ['ten', 'diez', 'numbers_time', null, 'A1'],
  ['twenty', 'veinte', 'numbers_time', null, 'A1'],
  ['thirty', 'treinta', 'numbers_time', null, 'A2'],
  ['forty', 'cuarenta', 'numbers_time', null, 'A2'],
  ['fifty', 'cincuenta', 'numbers_time', null, 'A2'],
  ['hundred', 'cien/ciento', 'numbers_time', null, 'A2'],
  ['thousand', 'mil', 'numbers_time', null, 'A2'],
  ['million', 'millón', 'numbers_time', null, 'A2'],
  ['Monday', 'lunes', 'numbers_time', null, 'A1'],
  ['Tuesday', 'martes', 'numbers_time', null, 'A1'],
  ['Wednesday', 'miércoles', 'numbers_time', null, 'A1'],
  ['Thursday', 'jueves', 'numbers_time', null, 'A1'],
  ['Friday', 'viernes', 'numbers_time', null, 'A1'],
  ['Saturday', 'sábado', 'numbers_time', null, 'A1'],
  ['Sunday', 'domingo', 'numbers_time', null, 'A1'],
  ['January', 'enero', 'numbers_time', null, 'A2'],
  ['February', 'febrero', 'numbers_time', null, 'A2'],
  ['March', 'marzo', 'numbers_time', null, 'A2'],
  ['April', 'abril', 'numbers_time', null, 'A2'],
  ['May', 'mayo', 'numbers_time', null, 'A2'],
  ['June', 'junio', 'numbers_time', null, 'A2'],
  ['July', 'julio', 'numbers_time', null, 'A2'],
  ['August', 'agosto', 'numbers_time', null, 'A2'],
  ['September', 'septiembre', 'numbers_time', null, 'A2'],
  ['October', 'octubre', 'numbers_time', null, 'A2'],
  ['November', 'noviembre', 'numbers_time', null, 'A2'],
  ['December', 'diciembre', 'numbers_time', null, 'A2'],
  ['today', 'hoy', 'numbers_time', null, 'A1'],
  ['tomorrow', 'mañana', 'numbers_time', null, 'A1'],
  ['yesterday', 'ayer', 'numbers_time', null, 'A1'],
  ['morning', 'mañana', 'numbers_time', null, 'A1'],
  ['afternoon', 'tarde', 'numbers_time', null, 'A1'],
  ['evening', 'noche (temprano)', 'numbers_time', null, 'A1'],
  ['night', 'noche', 'numbers_time', null, 'A1'],
  ['week', 'semana', 'numbers_time', null, 'A1'],
  ['month', 'mes', 'numbers_time', null, 'A1'],
  ['season', 'estación/temporada', 'numbers_time', null, 'A2'],
  ['spring', 'primavera', 'numbers_time', null, 'A2'],
  ['summer', 'verano', 'numbers_time', null, 'A1'],
  ['fall', 'otoño', 'numbers_time', null, 'A2'],
  ['winter', 'invierno', 'numbers_time', null, 'A1'],
  // === adverbs (120) ===
  ['very', 'muy', 'adverbs', null, 'A1'],
  ['always', 'siempre', 'adverbs', null, 'A1'],
  ['never', 'nunca', 'adverbs', null, 'A1'],
  ['often', 'a menudo/frecuentemente', 'adverbs', null, 'A2'],
  ['sometimes', 'a veces', 'adverbs', null, 'A2'],
  ['usually', 'generalmente/usualmente', 'adverbs', null, 'A2'],
  ['quickly', 'rápidamente', 'adverbs', null, 'A2'],
  ['slowly', 'lentamente/despacio', 'adverbs', null, 'A2'],
  ['carefully', 'cuidadosamente/con cuidado', 'adverbs', null, 'A2'],
  ['easily', 'fácilmente', 'adverbs', null, 'B1'],
  ['well', 'bien', 'adverbs', null, 'A1'],
  ['badly', 'mal', 'adverbs', null, 'A2'],
  ['together', 'juntos', 'adverbs', null, 'A2'],
  ['alone', 'solo', 'adverbs', null, 'A2'],
  ['already', 'ya', 'adverbs', null, 'A2'],
  ['enough', 'suficiente/bastante', 'adverbs', null, 'A2'],
  ['almost', 'casi', 'adverbs', null, 'A2'],
  ['perhaps', 'quizás/tal vez', 'adverbs', null, 'B1'],
  ['probably', 'probablemente', 'adverbs', null, 'B1'],
  ['certainly', 'ciertamente/seguro', 'adverbs', null, 'B1'],
  ['suddenly', 'de repente/repentinamente', 'adverbs', null, 'B1'],
  ['finally', 'finalmente/al fin', 'adverbs', null, 'B1'],
  ['recently', 'recientemente', 'adverbs', null, 'B1'],
  ['immediately', 'inmediatamente', 'adverbs', null, 'B1'],
  // === arts_culture (100) ===
  ['music', 'música', 'arts_culture', null, 'A1'],
  ['song', 'canción', 'arts_culture', null, 'A1'],
  ['movie', 'película', 'arts_culture', null, 'A1'],
  ['book', 'libro', 'arts_culture', null, 'A1'],
  ['art', 'arte', 'arts_culture', null, 'A2'],
  ['painting', 'pintura/cuadro', 'arts_culture', null, 'A2'],
  ['museum', 'museo', 'arts_culture', null, 'A2'],
  ['theater', 'teatro', 'arts_culture', null, 'A2'],
  ['concert', 'concierto', 'arts_culture', null, 'A2'],
  ['festival', 'festival', 'arts_culture', null, 'A2'],
  ['photography', 'fotografía', 'arts_culture', null, 'B1'],
  ['sculpture', 'escultura', 'arts_culture', null, 'B1'],
  ['dance', 'danza/baile', 'arts_culture', null, 'A1'],
  ['literature', 'literatura', 'arts_culture', null, 'B1'],
  ['poem', 'poema', 'arts_culture', null, 'B1'],
  ['guitar', 'guitarra', 'arts_culture', null, 'A2'],
  ['piano', 'piano', 'arts_culture', null, 'A2'],
  ['violin', 'violín', 'arts_culture', null, 'B1'],
  ['drum', 'tambor/batería', 'arts_culture', null, 'A2'],
  ['cinema', 'cine', 'arts_culture', null, 'A2'],
  ['actor', 'actor', 'arts_culture', null, 'A2'],
  ['actress', 'actriz', 'arts_culture', null, 'A2'],
  ['director', 'director', 'arts_culture', null, 'B1'],
  ['writer', 'escritor', 'arts_culture', null, 'A2'],
  ['artist', 'artista', 'arts_culture', null, 'A2'],
  // === shopping (80) ===
  ['store', 'tienda/negocio', 'shopping', null, 'A1'],
  ['money', 'dinero/plata', 'shopping', null, 'A1'],
  ['price', 'precio', 'shopping', null, 'A2'],
  ['buy', 'comprar', 'shopping', null, 'A1'],
  ['sell', 'vender', 'shopping', null, 'A2'],
  ['shop', 'tienda/comprar', 'shopping', null, 'A1'],
  ['market', 'mercado', 'shopping', null, 'A2'],
  ['supermarket', 'supermercado', 'shopping', null, 'A2'],
  ['mall', 'centro comercial', 'shopping', null, 'A2'],
  ['discount', 'descuento', 'shopping', null, 'A2'],
  ['receipt', 'recibo/ticket', 'shopping', null, 'A2'],
  ['cash', 'efectivo', 'shopping', null, 'A2'],
  ['credit card', 'tarjeta de crédito', 'shopping', null, 'A2'],
  ['customer', 'cliente', 'shopping', null, 'B1'],
  ['sale', 'venta/oferta', 'shopping', null, 'A2'],
  ['size', 'tamaño/talle', 'shopping', null, 'A2'],
  ['brand', 'marca', 'shopping', null, 'B1'],
  ['product', 'producto', 'shopping', null, 'B1'],
  ['shopping cart', 'carrito de compras', 'shopping', null, 'A2'],
  ['cashier', 'cajero/a', 'shopping', null, 'A2'],
  // === social (80) ===
  ['hello', 'hola', 'social', null, 'A1'],
  ['goodbye', 'adiós', 'social', null, 'A1'],
  ['please', 'por favor', 'social', null, 'A1'],
  ['thanks', 'gracias', 'social', null, 'A1'],
  ['sorry', 'perdón/lo siento', 'social', null, 'A1'],
  ['excuse me', 'disculpe/perdón', 'social', null, 'A2'],
  ['congratulations', 'felicitaciones', 'social', null, 'A2'],
  ['welcome', 'bienvenido', 'social', null, 'A1'],
  ['cheers', 'salud (brindis)', 'social', null, 'A2'],
  ['bless you', 'salud (estornudo)', 'social', null, 'A2'],
  ['see you', 'nos vemos', 'social', null, 'A1'],
  ['take care', 'cuídate', 'social', null, 'A2'],
  ['have fun', 'divertite', 'social', null, 'A2'],
  ['good luck', 'buena suerte', 'social', null, 'A1'],
  ['get well soon', 'que te mejores', 'social', null, 'A2'],
  ['happy birthday', 'feliz cumpleaños', 'social', null, 'A1'],
  ['merry Christmas', 'feliz Navidad', 'social', null, 'A1'],
  ['happy New Year', 'feliz Año Nuevo', 'social', null, 'A1'],
  ['how are you', 'cómo estás', 'social', null, 'A1'],
  ['what is your name', 'cómo te llamás', 'social', null, 'A1'],
  // === travel (100) ===
  ['airport', 'aeropuerto', 'travel', null, 'A2'],
  ['hotel', 'hotel', 'travel', null, 'A1'],
  ['passport', 'pasaporte', 'travel', null, 'A2'],
  ['visa', 'visa', 'travel', null, 'B1'],
  ['luggage', 'equipaje/valijas', 'travel', null, 'A2'],
  ['suitcase', 'valija/maleta', 'travel', null, 'A2'],
  ['flight', 'vuelo', 'travel', null, 'A2'],
  ['reservation', 'reserva/reservación', 'travel', null, 'B1'],
  ['tourist', 'turista', 'travel', null, 'A2'],
  ['map', 'mapa', 'travel', null, 'A2'],
  ['guide', 'guía', 'travel', null, 'A2'],
  ['destination', 'destino', 'travel', null, 'B1'],
  ['departure', 'salida/partida', 'travel', null, 'B1'],
  ['arrival', 'llegada', 'travel', null, 'B1'],
  ['check-in', 'registro/check-in', 'travel', null, 'A2'],
  ['boarding pass', 'tarjeta de embarque', 'travel', null, 'B1'],
  ['customs', 'aduana', 'travel', null, 'B1'],
  ['currency', 'moneda/divisa', 'travel', null, 'B1'],
  ['exchange rate', 'tipo de cambio', 'travel', null, 'B1'],
  ['travel insurance', 'seguro de viaje', 'travel', null, 'B1'],
  // === work_business (150) ===
  ['office', 'oficina', 'work_business', null, 'A2'],
  ['meeting', 'reunión', 'work_business', null, 'A2'],
  ['boss', 'jefe', 'work_business', null, 'A2'],
  ['salary', 'salario/sueldo', 'work_business', null, 'B1'],
  ['job', 'trabajo/empleo', 'work_business', null, 'A2'],
  ['career', 'carrera profesional', 'work_business', null, 'B1'],
  ['colleague', 'colega/compañero de trabajo', 'work_business', null, 'B1'],
  ['interview', 'entrevista', 'work_business', null, 'B1'],
  ['resume', 'currículum', 'work_business', null, 'B1'],
  ['contract', 'contrato', 'work_business', null, 'B1'],
  ['deadline', 'fecha límite', 'work_business', null, 'B1'],
  ['project', 'proyecto', 'work_business', null, 'B1'],
  ['report', 'informe/reporte', 'work_business', null, 'B1'],
  ['presentation', 'presentación', 'work_business', null, 'B1'],
  ['client', 'cliente', 'work_business', null, 'B1'],
  ['manager', 'gerente/encargado', 'work_business', null, 'B1'],
  ['employee', 'empleado', 'work_business', null, 'B1'],
  ['employer', 'empleador', 'work_business', null, 'B1'],
  ['promotion', 'ascenso/promoción', 'work_business', null, 'B1'],
  ['retirement', 'jubilación/retiro', 'work_business', null, 'B1'],
  ['business', 'negocio/empresa', 'work_business', null, 'B1'],
  ['company', 'compañía/empresa', 'work_business', null, 'A2'],
  ['factory', 'fábrica', 'work_business', null, 'B1'],
  ['industry', 'industria', 'work_business', null, 'B1'],
  ['trade', 'comercio/intercambio', 'work_business', null, 'B1'],
  ['profit', 'ganancia/beneficio', 'work_business', null, 'B1'],
  ['loss', 'pérdida', 'work_business', null, 'B1'],
  ['investment', 'inversión', 'work_business', null, 'B1'],
  ['budget', 'presupuesto', 'work_business', null, 'B1'],
  ['tax', 'impuesto', 'work_business', null, 'B1'],
];

// ── Expand compact data into full objects ──
export const WORDS_SEED = WORDS_COMPACT.map((row, index) => {
  const [english, spanish, category, subcategory, difficulty] = row;
  const [exEn, exEs] = makeExample(english, spanish);
  return {
    english_word: english,
    spanish_trans: spanish,
    phonetic: guessPhonetic(english),
    category: category,
    subcategory: subcategory || null,
    frequency_rank: index + 1,
    difficulty: difficulty,
    // Left null on purpose: the per-word emoji shows immediately and a real
    // photo is fetched + cached on first view (see enrichmentService).
    image_url: null,
    audio_url: null,
    example_en: exEn,
    example_es: exEs,
  };
});
