// saflash — A1 phrases. Row format: [phrase_en, phrase_es, category, context|null]

export const A1_PHRASES = [
  ["Hello!","¡Hola!","greetings","When greeting someone"],
  ["Hi!","¡Hola!","greetings","Informal greeting"],
  ["Good morning!","¡Buenos días!","greetings","Morning greeting"],
  ["Good afternoon!","¡Buenas tardes!","greetings","Afternoon greeting"],
  ["Good evening!","¡Buenas noches!","greetings","Evening greeting (on arrival)"],
  ["Good night!","¡Buenas noches!","greetings","When saying goodbye at night"],
  ["How are you?","¿Cómo estás?","greetings","When greeting someone you know"],
  ["How's it going?","¿Cómo va todo?","greetings","Informal greeting between friends"],
  ["How are you doing?","¿Cómo te va?","greetings","Casual greeting"],
  ["Nice to meet you!","¡Mucho gusto!","greetings","When meeting someone"],
  ["See you later!","¡Nos vemos luego!","greetings","When saying goodbye"],
  ["See you soon!","¡Nos vemos pronto!","greetings","When saying goodbye expecting to meet again"],
  ["See you tomorrow!","¡Nos vemos mañana!","greetings","When saying goodbye"],
  ["Have a nice day!","¡Que tengas un buen día!","greetings","When saying goodbye"],
  ["Have a good weekend!","¡Buen fin de semana!","greetings","Friday farewell"],
  ["Welcome!","¡Bienvenido!","greetings","When welcoming someone"],
  ["Morning!","¡Buen día!","greetings","Short morning greeting"],
  ["Afternoon!","¡Buenas tardes!","greetings","Short afternoon greeting"],
  ["Evening!","¡Buenas noches!","greetings","Short evening greeting"],
  ["Goodbye!","¡Adiós!","greetings","Formal farewell"],
  ["Bye!","¡Chau! / ¡Adiós!","greetings","Informal farewell"],
  ["Bye bye!","¡Adiós adiós!","greetings","Affectionate farewell"],
  ["Please","Por favor","courtesy","When asking for something"],
  ["Thank you","Gracias","courtesy","When thanking someone"],
  ["Thanks","Gracias","courtesy","Informal thanks"],
  ["Thank you very much","Muchas gracias","courtesy","Emphatic thanks"],
  ["You're welcome","De nada","courtesy","When responding to thanks"],
  ["Excuse me","Disculpe / Permiso","courtesy","When interrupting or asking to pass"],
  ["I'm sorry","Lo siento","courtesy","When apologizing"],
  ["Sorry","Perdón","courtesy","Informal apology"],
  ["Good luck!","¡Buena suerte!","courtesy","When wishing someone success"],
  ["Happy birthday!","¡Feliz cumpleaños!","courtesy","When congratulating someone on their birthday"],
  ["Merry Christmas!","¡Feliz Navidad!","courtesy","Christmas greeting"],
  ["Happy New Year!","¡Feliz Año Nuevo!","courtesy","New Year's greeting"],
  ["What time is it?","¿Qué hora es?","questions","When asking the time"],
  ["Where is the bathroom?","¿Dónde está el baño?","questions","When looking for the bathroom"],
  ["How much does it cost?","¿Cuánto cuesta?","questions","When asking a price"],
  ["What is your name?","¿Cómo te llamás?","questions","When asking someone's name"],
  ["Where are you from?","¿De dónde sos?","questions","When asking where someone's from"],
  ["How old are you?","¿Cuántos años tenés?","questions","When asking someone's age"],
  ["Do you speak English?","¿Hablas inglés?","questions","When asking about languages"],
  ["Can you help me?","¿Me podés ayudar?","questions","When asking for help"],
  ["Where do you live?","¿Dónde vivís?","questions","When asking where someone lives"],
  ["What is this?","¿Qué es esto?","questions","When asking about an object"],
  ["Do you have...?","¿Tenés...?","questions","When asking about availability"],
  ["Who is that?","¿Quién es?","questions","When asking about a person"],
  ["My name is John","Me llamo John","introductions","When introducing yourself"],
  ["I'm from Spain","Soy de España","introductions","When saying where you're from"],
  ["I am a student","Soy estudiante","introductions","When talking about your occupation"],
  ["I am a teacher","Soy profesor/a","introductions","When saying your profession"],
  ["I study English","Estudio inglés","introductions","When talking about your studies"],
  ["I have a dog","Tengo un perro","introductions","When talking about pets"],
  ["How much is this?","¿Cuánto cuesta esto?","shopping","When asking the price in a store"],
  ["What is your phone number?","¿Cuál es tu número de teléfono?","phone","When asking for contact info"],
  ["It is 3 o'clock","Son las 3 en punto","time","When telling the time"],
  ["What day is it today?","¿Qué día es hoy?","time","When asking what day it is"],
  ["It is Monday","Es lunes","time","When saying the day"],
  ["It is sunny today","Hoy está soleado","weather","When describing the weather"],
  ["It is raining","Está lloviendo","weather","When describing the weather"],
  ["I have two brothers","Tengo dos hermanos","family","When talking about your family"],
];
