// saflash — A2 phrases. Row format: [phrase_en, phrase_es, category, context|null]

export const A2_PHRASES = [
  ["What's up?","¿Qué tal?","greetings","Very informal greeting"],
  ["Pleased to meet you!","¡Encantado de conocerte!","greetings","When meeting someone formally"],
  ["Take care!","¡Cuídate!","greetings","When saying goodbye to someone close"],
  ["Welcome back!","¡Bienvenido de vuelta!","greetings","When someone returns"],
  ["How have you been?","¿Cómo has estado?","greetings","When reuniting after a long time"],
  ["What's new?","¿Qué hay de nuevo?","greetings","To start a conversation"],
  ["Good to see you!","¡Qué bueno verte!","greetings","When running into someone"],
  ["Hey there!","¡Eh, hola!","greetings","Very casual greeting"],
  ["How's your day going?","¿Cómo va tu día?","greetings","To ask about someone's day"],
  ["Have a safe trip!","¡Buen viaje!","greetings","When seeing off someone who's traveling"],
  ["Talk to you soon!","¡Hablamos pronto!","greetings","When saying goodbye on the phone"],
  ["Thanks a lot!","¡Muchísimas gracias!","courtesy","Very emphatic thanks"],
  ["No problem","No hay problema","courtesy","Casual response to thanks"],
  ["May I?","¿Puedo?","courtesy","When asking for permission"],
  ["After you","Después de usted","courtesy","When letting someone go first"],
  ["Go ahead","Adelante","courtesy","When giving way or permission"],
  ["Bless you","Salud","courtesy","When someone sneezes"],
  ["Cheers!","¡Salud!","courtesy","When making a toast"],
  ["Congratulations!","¡Felicitaciones!","courtesy","When congratulating an achievement"],
  ["Well done!","¡Bien hecho!","courtesy","When congratulating someone's work"],
  ["Get well soon!","¡Que te mejores pronto!","courtesy","To someone who's sick"],
  ["What do you do?","¿A qué te dedicás?","questions","When asking about someone's job"],
  ["What does that mean?","¿Qué significa eso?","questions","When asking for meaning"],
  ["How do you say... in English?","¿Cómo se dice... en inglés?","questions","When learning vocabulary"],
  ["Could you repeat that?","¿Podrías repetir eso?","questions","When not understanding something"],
  ["Can you speak more slowly?","¿Podés hablar más despacio?","questions","When asking for clarity"],
  ["What happened?","¿Qué pasó?","questions","When asking about an event"],
  ["What's wrong?","¿Qué pasa? / ¿Qué anda mal?","questions","When noticing someone is unwell"],
  ["Are you okay?","¿Estás bien?","questions","When worrying about someone"],
  ["How was your day?","¿Cómo estuvo tu día?","questions","When asking about someone's day"],
  ["What's the weather like?","¿Cómo está el clima?","questions","When asking about the weather"],
  ["Where can I find...?","¿Dónde puedo encontrar...?","questions","When looking for something specific"],
  ["How long does it take?","¿Cuánto tiempo toma?","questions","When asking about duration"],
  ["Is it far from here?","¿Está lejos de aquí?","questions","When asking about distance"],
  ["What do you recommend?","¿Qué recomiendas?","questions","When asking for advice"],
  ["Would you like something to drink?","¿Te gustaría algo para tomar?","questions","When offering a drink"],
  ["Are you free tonight?","¿Estás libre esta noche?","questions","When inviting someone"],
  ["What do you think?","¿Qué pensás?","questions","When asking for an opinion"],
  ["How do you feel?","¿Cómo te sentís?","questions","When asking about someone's mood"],
  ["Where did you go?","¿A dónde fuiste?","questions","When asking about a trip"],
  ["When does it start?","¿Cuándo empieza?","questions","When asking about a schedule"],
  ["Why is that?","¿Por qué es eso?","questions","When asking for a reason"],
  ["Which one is yours?","¿Cuál es el tuyo?","questions","When identifying ownership"],
  ["I live in Madrid","Vivo en Madrid","introductions","When saying where you live"],
  ["I work in a hospital","Trabajo en un hospital","introductions","When talking about your job"],
  ["I'm learning Spanish","Estoy aprendiendo español","introductions","When talking about the language you're learning"],
  ["I have two children","Tengo dos hijos","introductions","When talking about your family"],
  ["I'm married","Estoy casado/a","introductions","When talking about marital status"],
  ["I like reading","Me gusta leer","introductions","When talking about hobbies"],
  ["I enjoy cooking","Disfruto cocinar","introductions","When talking about pastimes"],
  ["I play the guitar","Toco la guitarra","introductions","When talking about skills"],
  ["I love traveling","Me encanta viajar","introductions","When talking about interests"],
  ["I was born in 1990","Nací en 1990","introductions","When saying your birth year"],
  ["I'm here on vacation","Estoy aquí de vacaciones","introductions","When explaining the reason for your visit"],
  ["I'm visiting family","Estoy visitando a mi familia","introductions","When explaining a visit"],
  ["I come here often","Vengo aquí seguido","introductions","When talking about frequency"],
  ["This is my friend Maria","Esta es mi amiga Maria","introductions","When introducing someone"],
  ["We work together","Trabajamos juntos","introductions","When explaining a work relationship"],
  ["Tell me about yourself","Contame sobre vos","introductions","When asking someone to introduce themselves"],
  ["Do you have this in my size?","¿Tenés esto en mi talle?","shopping","When looking for clothes"],
  ["I would like to pay by card","Quisiera pagar con tarjeta","shopping","When paying"],
  ["Can I try this on?","¿Me puedo probar esto?","shopping","When trying on clothes"],
  ["Where is the fitting room?","¿Dónde está el probador?","shopping","When looking for where to try on clothes"],
  ["I'm just looking, thanks","Solo estoy mirando, gracias","shopping","When declining a salesperson's help"],
  ["Do you have a smaller size?","¿Tenés un talle más chico?","shopping","When asking for another size"],
  ["Do you have this in another color?","¿Tenés esto en otro color?","shopping","When looking for variety"],
  ["Where can I pay?","¿Dónde puedo pagar?","shopping","When looking for the checkout"],
  ["Is there a discount?","¿Hay descuento?","shopping","When asking about deals"],
  ["How much is the total?","¿Cuánto es el total?","shopping","When finding out the final price"],
  ["I'll take it","Me lo llevo","shopping","When deciding to buy"],
  ["It's too expensive","Es demasiado caro","shopping","When considering something expensive"],
  ["Is this on sale?","¿Está en oferta?","shopping","When asking if there's a discount"],
  ["Where is the shoe section?","¿Dónde está la sección de zapatos?","shopping","When looking for a specific section"],
  ["What time do you close?","¿A qué hora cierran?","shopping","When asking about a schedule"],
  ["Do you have a bag?","¿Tenés una bolsa?","shopping","When needing a bag"],
  ["It doesn't fit me","No me queda bien","shopping","When trying on clothes that don't fit"],
  ["Where are the fitting rooms?","¿Dónde están los probadores?","shopping","When looking for fitting rooms"],
  ["I need a larger size","Necesito un talle más grande","shopping","When asking for a bigger size"],
  ["This is broken","Esto está roto","shopping","When finding a damaged product"],
  ["I paid in cash","Pagué en efectivo","shopping","When saying how you paid"],
  ["Keep the change","Quedate con el cambio","shopping","When leaving a tip or change"],
  ["Are you open on Sundays?","¿Abren los domingos?","shopping","When asking about hours"],
  ["Do you sell...?","¿Venden...?","shopping","When asking if something is sold"],
  ["I would like a table for two","Quisiera una mesa para dos","restaurant","When arriving at a restaurant"],
  ["The check, please","La cuenta, por favor","restaurant","When asking for the check"],
  ["Can I see the menu?","¿Me podés mostrar el menú?","restaurant","When asking for the menu"],
  ["I'm ready to order","Estoy listo para pedir","restaurant","When ordering"],
  ["Can I have some water please?","¿Me podés dar agua por favor?","restaurant","When asking for water"],
  ["I'll have the same","Voy a pedir lo mismo","restaurant","When ordering the same as someone else"],
  ["This is delicious!","¡Está delicioso!","restaurant","When enjoying the food"],
  ["Could I have a fork please?","¿Me podrías dar un tenedor por favor?","restaurant","When asking for cutlery"],
  ["What do you have for dessert?","¿Qué tienen de postre?","restaurant","When asking about desserts"],
  ["The food is cold","La comida está fría","restaurant","When complaining about the temperature"],
  ["Could I have a napkin?","¿Me podrías dar una servilleta?","restaurant","When asking for a napkin"],
  ["Can I have it to go?","¿Me lo pueden dar para llevar?","restaurant","When asking for food to go"],
  ["A table for four, please","Una mesa para cuatro, por favor","restaurant","When asking for a table"],
  ["Can I have some bread?","¿Me pueden dar pan?","restaurant","When asking for bread"],
  ["Just water for me","Solo agua para mí","restaurant","When asking for just water"],
  ["Can I have some salt?","¿Me podés dar sal?","restaurant","When asking for salt"],
  ["Could we have more napkins?","¿Podrían traernos más servilletas?","restaurant","When asking for more napkins"],
  ["That was excellent, thank you!","Estuvo excelente, ¡gracias!","restaurant","When finishing the meal"],
  ["Can I have the bill please?","¿Me puede dar la cuenta por favor?","restaurant","When asking for the check"],
  ["Where is the nearest hotel?","¿Dónde está el hotel más cercano?","travel","When looking for lodging"],
  ["I need a taxi","Necesito un taxi","travel","When asking for transportation"],
  ["My flight is at 8am","Mi vuelo es a las 8 de la mañana","travel","When talking about a flight schedule"],
  ["Where is the bus station?","¿Dónde está la estación de buses?","travel","When looking for transportation"],
  ["How do I get to the airport?","¿Cómo llego al aeropuerto?","travel","When asking for directions"],
  ["Can I have a map?","¿Me podés dar un mapa?","travel","When asking for directions"],
  ["Is breakfast included?","¿El desayuno está incluido?","travel","When asking at the hotel"],
  ["Can you call a taxi for me?","¿Me podés llamar un taxi?","travel","When asking for help at the hotel"],
  ["How long is the flight?","¿Cuánto dura el vuelo?","travel","When asking about duration"],
  ["Where is the train station?","¿Dónde está la estación de tren?","travel","When looking for a station"],
  ["How much is a ticket to London?","¿Cuánto cuesta un boleto a Londres?","travel","When buying a ticket"],
  ["Is this seat taken?","¿Está ocupado este asiento?","travel","When looking for a seat"],
  ["Do you have a single room?","¿Tenés una habitación individual?","travel","When booking a hotel"],
  ["Can I have an extra towel?","¿Me podés dar una toalla extra?","travel","When asking for something at the hotel"],
  ["Where is the nearest bus stop?","¿Dónde está la parada de bus más cercana?","travel","When looking for public transportation"],
  ["I need to check in","Necesito hacer el check-in","travel","When arriving at the hotel or airport"],
  ["Is there free Wi-Fi?","¿Hay Wi-Fi gratis?","travel","When asking at the hotel"],
  ["How do I get to the city center?","¿Cómo llego al centro?","travel","When getting oriented in a city"],
  ["Can you help me with my bags?","¿Me podés ayudar con las valijas?","travel","When asking for help with luggage"],
  ["I have a meeting at 3pm","Tengo una reunión a las 3 de la tarde","work","When talking about a schedule"],
  ["Can you send me the report?","¿Me podés enviar el informe?","work","When asking for a document"],
  ["I'm on vacation next week","Estoy de vacaciones la semana que viene","work","When reporting an absence"],
  ["What time does the meeting start?","¿A qué hora empieza la reunión?","work","When asking about a schedule"],
  ["Could you help me with this?","¿Me podrías ayudar con esto?","work","When asking for help"],
  ["Do you have a moment to talk?","¿Tenés un momento para hablar?","work","When asking for a brief meeting"],
  ["I don't feel well","No me siento bien","health","When feeling unwell"],
  ["I have a headache","Tengo dolor de cabeza","health","When describing a symptom"],
  ["I need to see a doctor","Necesito ver a un médico","health","When seeking medical care"],
  ["Where is the nearest hospital?","¿Dónde está el hospital más cercano?","health","In an emergency"],
  ["I have a stomachache","Me duele el estómago","health","When describing pain"],
  ["I have a fever","Tengo fiebre","health","When describing a symptom"],
  ["My throat hurts","Me duele la garganta","health","When describing pain"],
  ["I have a sore throat","Tengo dolor de garganta","health","When describing a symptom"],
  ["My back hurts","Me duele la espalda","health","When describing pain"],
  ["I feel much better now","Me siento mucho mejor ahora","health","When reporting improvement"],
  ["You should get some rest","Deberías descansar","health","When giving advice"],
  ["I have a cough","Tengo tos","health","When describing a symptom"],
  ["I have a cold","Estoy resfriado","health","When describing an illness"],
  ["Turn left","Girá a la izquierda","directions","When giving directions"],
  ["Go straight","Seguí derecho","directions","When giving directions"],
  ["It's on the right","Está a la derecha","directions","When locating something"],
  ["How far is it?","¿Qué tan lejos está?","directions","When asking about distance"],
  ["Turn right at the corner","Girá a la derecha en la esquina","directions","When giving directions"],
  ["It's on the left","Está a la izquierda","directions","When locating something"],
  ["Go straight ahead","Seguí derecho","directions","When giving directions"],
  ["Cross the street","Cruzá la calle","directions","When giving directions"],
  ["Go down this street","Bajá por esta calle","directions","When giving directions"],
  ["It's next to the pharmacy","Está al lado de la farmacia","directions","When locating by landmark"],
  ["Turn around","Date la vuelta","directions","When indicating a change of direction"],
  ["I am lost","Estoy perdido","directions","When asking for help"],
  ["Can you show me on the map?","¿Me podés mostrar en el mapa?","directions","When asking for directions"],
  ["It's two blocks away","Está a dos cuadras","directions","When giving a distance"],
  ["Go up the stairs","Subí las escaleras","directions","When giving directions inside a building"],
  ["Take the elevator","Tomá el ascensor","directions","When giving directions inside a building"],
  ["It's on the second floor","Está en el segundo piso","directions","When locating something in a building"],
  ["Is this the right way?","¿Voy bien por acá?","directions","When confirming a direction"],
  ["Can I call you later?","¿Te puedo llamar después?","phone","When ending a call"],
  ["Could you speak more slowly?","¿Podrías hablar más despacio?","phone","When asking for clarity"],
  ["I'll text you","Te mando un mensaje","phone","When promising to stay in touch in writing"],
  ["Can you hear me?","¿Me escuchás?","phone","When checking audio"],
  ["I missed your call","Perdí tu llamada","phone","When checking calls"],
  ["I need to charge my phone","Necesito cargar mi teléfono","phone","When running out of battery"],
  ["Can I use your charger?","¿Puedo usar tu cargador?","phone","When asking to borrow something"],
  ["I will give you a call","Te voy a hacer una llamada","phone","When promising to call"],
  ["Can you send me a text?","¿Me podés mandar un mensaje?","phone","When asking for a text message"],
  ["I lost your number","Perdí tu número","phone","When losing touch"],
  ["Can I have your number?","¿Me podés dar tu número?","phone","When asking for contact info"],
  ["I need to make a phone call","Necesito hacer una llamada","phone","When looking for a phone"],
  ["Let me check my messages","Dejame revisar mis mensajes","phone","When checking notifications"],
  ["Did you get my text?","¿Recibiste mi mensaje?","phone","When verifying communication"],
  ["I'll send you the address","Te mando la dirección","phone","When promising to send details"],
  ["I'm very happy","Estoy muy feliz","emotions","When expressing joy"],
  ["I'm a little tired","Estoy un poco cansado","emotions","When expressing tiredness"],
  ["That's amazing!","¡Eso es increíble!","emotions","When expressing amazement"],
  ["I'm not sure","No estoy seguro","emotions","When expressing doubt"],
  ["I'm so excited!","¡Estoy tan emocionado!","emotions","When expressing enthusiasm"],
  ["That's so funny!","¡Qué gracioso!","emotions","When reacting to something funny"],
  ["I'm confused","Estoy confundido","emotions","When expressing confusion"],
  ["You scared me!","¡Me asustaste!","emotions","When reacting to a scare"],
  ["I can't believe it!","¡No lo puedo creer!","emotions","When expressing disbelief"],
  ["Take it easy","Tomalo con calma","emotions","When calming someone down"],
  ["Don't worry about it","No te preocupes por eso","emotions","When reassuring someone"],
  ["Cheer up!","¡Animate!","emotions","When cheering up someone who's sad"],
  ["Calm down","Tranquilizate","emotions","When calming someone who's upset"],
  ["I'm running late","Estoy llegando tarde","time","When warning about a delay"],
  ["Let's meet at noon","Encontrémonos al mediodía","time","When coordinating a meetup"],
  ["I will be there at 5pm","Voy a estar ahí a las 5 de la tarde","time","When confirming a schedule"],
  ["It takes about an hour","Toma más o menos una hora","time","When estimating duration"],
  ["I wake up at 7 every morning","Me despierto a las 7 todas las mañanas","time","When talking about a routine"],
  ["The meeting starts at 3","La reunión empieza a las 3","time","When announcing a schedule"],
  ["Hurry up!","¡Apurate!","time","When asking someone to hurry"],
  ["Take your time","Tomate tu tiempo","time","When giving permission to take your time"],
  ["I have plenty of time","Tengo mucho tiempo","time","When expressing availability"],
  ["It is half past two","Son las dos y media","time","When telling the time"],
  ["It is quarter to four","Son las cuatro menos cuarto","time","When telling the time"],
  ["I will see you in an hour","Te veo en una hora","time","When coordinating plans"],
  ["The movie starts at 7:30","La película empieza a las 7:30","time","When announcing a schedule"],
  ["I'll be back in five minutes","Vuelvo en cinco minutos","time","When announcing a brief return"],
  ["The store closes at 9","La tienda cierra a las 9","time","When announcing a schedule"],
  ["My birthday is in June","Mi cumpleaños es en junio","time","When talking about a date"],
  ["The concert is next Saturday","El concierto es el próximo sábado","time","When talking about a future event"],
  ["We have to leave now","Tenemos que irnos ahora","time","When indicating urgency"],
  ["I will be done soon","Voy a terminar pronto","time","When announcing completion"],
  ["Wait a moment","Esperá un momento","time","When asking for a brief wait"],
  ["Just a second","Un segundo","time","When asking for a minimal wait"],
  ["I arrived early","Llegué temprano","time","When indicating punctuality"],
  ["I was there on time","Llegué a tiempo","time","When indicating punctuality"],
  ["She is always late","Ella siempre llega tarde","time","When commenting on a habit"],
  ["I need more time","Necesito más tiempo","time","When asking for more time"],
  ["What time do you open?","¿A qué hora abren?","time","When asking about a schedule"],
  ["It's very hot today","Hace mucho calor hoy","weather","When commenting on the weather"],
  ["It looks like rain","Parece que va a llover","weather","When looking at the sky"],
  ["It is snowing","Está nevando","weather","When describing the weather"],
  ["It's a beautiful day!","¡Es un día hermoso!","weather","When appreciating nice weather"],
  ["It is windy outside","Está ventoso afuera","weather","When describing the weather"],
  ["Do I need a jacket?","¿Necesito una campera?","weather","When deciding what to wear"],
  ["The sun is shining","El sol está brillando","weather","When describing a sunny day"],
  ["It is cloudy","Está nublado","weather","When describing the sky"],
  ["I hope it doesn't rain","Espero que no llueva","weather","When expressing a wish"],
  ["It's going to be hot tomorrow","Va a hacer calor mañana","weather","When anticipating the weather"],
  ["We need an umbrella","Necesitamos un paraguas","weather","When preparing for rain"],
  ["The weather is perfect","El clima está perfecto","weather","When expressing satisfaction"],
  ["Is it cold outside?","¿Hace frío afuera?","weather","When asking about the temperature"],
  ["Dress warmly, it is cold","Abrigate, hace frío","weather","When giving advice"],
  ["My parents live in...","Mis padres viven en...","family","When talking about your parents"],
  ["We are a big family","Somos una familia grande","family","When describing your family"],
  ["Do you have any siblings?","¿Tenés hermanos?","family","When asking about family"],
  ["I am the oldest","Soy el/la mayor","family","When talking about birth order"],
  ["My sister is a doctor","Mi hermana es doctora","family","When talking about a family member's profession"],
  ["I have three children","Tengo tres hijos","family","When talking about your children"],
  ["We got married last year","Nos casamos el año pasado","family","When recounting an event"],
  ["How is your family?","¿Cómo está tu familia?","family","When asking about the family"],
  ["I miss my family","Extraño a mi familia","family","When expressing nostalgia"],
  ["My uncle is visiting us","Mi tío nos está visitando","family","When talking about a visit"],
];
