// saflash — B1 phrases. Row format: [phrase_en, phrase_es, category, context|null]

export const B1_PHRASES = [
  ["Long time no see!","¡Cuánto tiempo sin verte!","greetings","When reuniting with someone"],
  ["It's been a while!","¡Ha pasado un tiempo!","greetings","When reuniting"],
  ["Until next time!","¡Hasta la próxima!","greetings","Farewell expecting to meet again"],
  ["Catch you later!","¡Te veo después!","greetings","Very informal farewell"],
  ["Lovely to meet you!","¡Un placer conocerte!","greetings","When meeting someone enthusiastically"],
  ["Greetings!","¡Saludos!","greetings","Formal or written greeting"],
  ["Don't mention it","Ni lo menciones","courtesy","Response to thanks"],
  ["My pleasure","Es un placer","courtesy","Formal response to thanks"],
  ["I apologize","Me disculpo","courtesy","Formal apology"],
  ["Forgive me","Perdóname","courtesy","When asking for forgiveness"],
  ["Pardon me","Perdón / Disculpe","courtesy","When interrupting politely"],
  ["All the best!","¡Todo lo mejor!","courtesy","When saying goodbye with good wishes"],
  ["Best wishes!","¡Mis mejores deseos!","courtesy","When congratulating or saying goodbye in writing"],
  ["My apologies","Mis disculpas","courtesy","Formal apology"],
  ["How many people are coming?","¿Cuántas personas vienen?","questions","When organizing an event"],
  ["I moved here last year","Me mudé aquí el año pasado","introductions","When explaining your arrival"],
  ["I'm an engineer","Soy ingeniero/a","introductions","When saying your profession"],
  ["I work from home","Trabajo desde casa","introductions","When talking about a work arrangement"],
  ["Let me introduce myself","Permitime presentarme","introductions","When starting a formal introduction"],
  ["I would like you to meet...","Me gustaría presentarte a...","introductions","When introducing formally"],
  ["I've heard a lot about you","He escuchado mucho sobre vos","introductions","When meeting someone famous"],
  ["Nice to finally meet you","Qué bueno conocerte por fin","introductions","When meeting someone in person"],
  ["I don't think we've met","Creo que no nos conocemos","introductions","When approaching someone new"],
  ["Can I get a receipt?","¿Me podés dar un recibo?","shopping","When asking for a receipt"],
  ["Do you accept credit cards?","¿Aceptan tarjetas de crédito?","shopping","When asking about payment method"],
  ["Can I return this?","¿Puedo devolver esto?","shopping","When wanting to return a product"],
  ["I'm looking for a gift","Estoy buscando un regalo","shopping","When looking for a gift"],
  ["Can you gift wrap it?","¿Lo pueden envolver para regalo?","shopping","When asking for wrapping"],
  ["Is this the final price?","¿Este es el precio final?","shopping","When confirming a price"],
  ["Can I have a refund?","¿Me pueden hacer un reembolso?","shopping","When asking for a refund"],
  ["Can I exchange this?","¿Puedo cambiar esto?","shopping","When wanting to exchange a product"],
  ["How long is the warranty?","¿Cuánto dura la garantía?","shopping","When asking about a warranty"],
  ["What are today's specials?","¿Cuáles son los especiales del día?","restaurant","When asking about the daily specials"],
  ["I have a reservation","Tengo una reserva","restaurant","When arriving with a reservation"],
  ["Do you have vegetarian options?","¿Tienen opciones vegetarianas?","restaurant","When asking about vegetarian food"],
  ["Is the tip included?","¿La propina está incluida?","restaurant","When asking about the service charge"],
  ["I am allergic to nuts","Soy alérgico a las nueces","restaurant","When reporting an allergy"],
  ["Can we sit by the window?","¿Podemos sentarnos junto a la ventana?","restaurant","When choosing a location"],
  ["Can I get a refill?","¿Me pueden servir más?","restaurant","When asking for a drink refill"],
  ["Can you make it spicy?","¿Lo pueden hacer picante?","restaurant","When asking for spicy food"],
  ["Is this dish gluten-free?","¿Este plato es sin gluten?","restaurant","When asking about dietary restrictions"],
  ["I would like to make a reservation","Quisiera hacer una reserva","restaurant","When booking by phone"],
  ["How long is the wait?","¿Cuánto hay que esperar?","restaurant","When asking about wait time"],
  ["Do you serve breakfast all day?","¿Sirven desayuno todo el día?","restaurant","When asking about hours"],
  ["What kind of dressing do you have?","¿Qué tipo de aderezo tienen?","restaurant","When asking about dressings"],
  ["Is there a kids' menu?","¿Hay menú infantil?","restaurant","When asking about a kids' menu"],
  ["Are you still serving?","¿Todavía están sirviendo?","restaurant","When arriving close to closing time"],
  ["Well done, please","Bien cocido, por favor","restaurant","When asking for the meat's doneness"],
  ["Medium rare, please","Término medio, por favor","restaurant","When asking how well-done the meat should be"],
  ["Do you have any specials tonight?","¿Tienen especiales esta noche?","restaurant","When asking about specials"],
  ["We would like to order now","Quisiéramos ordenar ahora","restaurant","When calling the waiter"],
  ["I lost my passport","Perdí mi pasaporte","travel","In a travel emergency"],
  ["What time is checkout?","¿A qué hora es la salida?","travel","When asking at the hotel"],
  ["I would like a round-trip ticket","Quisiera un boleto de ida y vuelta","travel","When buying tickets"],
  ["Is there a direct flight?","¿Hay vuelo directo?","travel","When looking for flights"],
  ["I missed my flight","Perdí mi vuelo","travel","In a travel emergency"],
  ["Can I change my reservation?","¿Puedo cambiar mi reserva?","travel","When changing plans"],
  ["Where can I exchange money?","¿Dónde puedo cambiar dinero?","travel","When looking to exchange currency"],
  ["Can I see the room?","¿Puedo ver la habitación?","travel","When evaluating lodging"],
  ["The air conditioning doesn't work","El aire acondicionado no funciona","travel","When complaining at the hotel"],
  ["I need a wake-up call","Necesito una llamada de despertador","travel","When requesting hotel service"],
  ["What terminal is my flight?","¿En qué terminal sale mi vuelo?","travel","When getting oriented at the airport"],
  ["Has my flight been delayed?","¿Mi vuelo fue demorado?","travel","When checking status"],
  ["Can I have a window seat?","¿Puedo tener un asiento en ventanilla?","travel","When choosing a seat"],
  ["My luggage is missing","Perdieron mi equipaje","travel","When reporting lost luggage"],
  ["How far is the hotel from the airport?","¿Qué tan lejos está el hotel del aeropuerto?","travel","When planning a transfer"],
  ["I would like to book a tour","Quisiera reservar un tour","travel","When booking an excursion"],
  ["Do I need a visa?","¿Necesito visa?","travel","When planning international travel"],
  ["What is the local currency?","¿Cuál es la moneda local?","travel","When learning about a destination"],
  ["Is it safe to walk at night?","¿Es seguro caminar de noche?","travel","When asking about safety"],
  ["Where can I buy a SIM card?","¿Dónde puedo comprar un chip de teléfono?","travel","When needing a phone"],
  ["I need to finish this by Friday","Necesito terminar esto para el viernes","work","When talking about deadlines"],
  ["Let me check my calendar","Dejame revisar mi calendario","work","When checking availability"],
  ["I'll get back to you","Te respondo después","work","When postponing a response"],
  ["Can we reschedule?","¿Podemos reprogramar?","work","When changing an appointment"],
  ["Please send me the details","Por favor enviame los detalles","work","When asking for information"],
  ["The deadline is Monday","La fecha límite es el lunes","work","When reminding about a deadline"],
  ["I'm working from home today","Hoy trabajo desde casa","work","When reporting a work arrangement"],
  ["Can I have a day off?","¿Me puedo tomar un día libre?","work","When asking for permission"],
  ["We need to discuss this","Tenemos que hablar de esto","work","When starting a serious conversation"],
  ["Great job on the presentation!","¡Buen trabajo en la presentación!","work","When congratulating a coworker"],
  ["I have a deadline coming up","Se me viene una fecha límite","work","When talking about work pressure"],
  ["Let's schedule a call","Coordinemos una llamada","work","When proposing a virtual meeting"],
  ["Can you cover for me?","¿Me podés cubrir?","work","When asking for a replacement"],
  ["I'll be in a meeting all afternoon","Voy a estar en reunión toda la tarde","work","When reporting availability"],
  ["Please review this document","Por favor revisá este documento","work","When asking for a review"],
  ["I need an extension on this","Necesito una extensión para esto","work","When asking for more time"],
  ["The client is waiting for our response","El cliente está esperando nuestra respuesta","work","When prioritizing a task"],
  ["Could you clarify what you mean?","¿Podrías aclarar a qué te referís?","work","When asking for clarity"],
  ["I'm on a tight schedule","Tengo una agenda ajustada","work","When explaining a time constraint"],
  ["Can we move the meeting to 2pm?","¿Podemos mover la reunión a las 2?","work","When changing a schedule"],
  ["Please CC me on that email","Por favor poneme en copia en ese correo","work","When asking to be included in communications"],
  ["I'll take care of it","Yo me encargo","work","When taking responsibility"],
  ["The project is on track","El proyecto va bien encaminado","work","When reporting status"],
  ["We have a tight deadline","Tenemos una fecha límite ajustada","work","When talking about pressure"],
  ["I'll send you the minutes","Te envío las notas de la reunión","work","When promising to send a summary"],
  ["I need to prepare for the presentation","Necesito preparar la presentación","work","When planning work"],
  ["I feel dizzy","Me siento mareado","health","When describing a symptom"],
  ["I twisted my ankle","Me torcí el tobillo","health","When describing an injury"],
  ["Can you call an ambulance?","¿Podés llamar a una ambulancia?","health","In a serious emergency"],
  ["I need a prescription","Necesito una receta","health","When asking for medication"],
  ["Are you allergic to any medication?","¿Sos alérgico a algún medicamento?","health","Medical question"],
  ["I have a runny nose","Tengo la nariz que me gotea","health","When describing a cold symptom"],
  ["I feel nauseous","Siento náuseas","health","When describing discomfort"],
  ["How long have you had these symptoms?","¿Hace cuánto tenés estos síntomas?","health","Medical question"],
  ["I need to make an appointment","Necesito hacer una cita","health","When asking for a doctor's appointment"],
  ["Do you have insurance?","¿Tenés seguro médico?","health","Administrative question"],
  ["Take this medicine twice a day","Tomá esta medicina dos veces al día","health","Medical instruction"],
  ["I need some painkillers","Necesito analgésicos","health","When asking for medicine"],
  ["I have a toothache","Tengo dolor de muelas","health","When describing dental pain"],
  ["I need to see a dentist","Necesito ver a un dentista","health","When seeking dental care"],
  ["Stay hydrated","Mantenete hidratado","health","Medical advice"],
  ["Get some fresh air","Tomá un poco de aire fresco","health","Advice for feeling better"],
  ["Take the first left","Tomá la primera a la izquierda","directions","When giving directions"],
  ["Is it within walking distance?","¿Se puede ir caminando?","directions","When asking about distance"],
  ["It's around the corner","Está a la vuelta de la esquina","directions","When locating something nearby"],
  ["Go past the bank","Pasá el banco","directions","When giving directions"],
  ["It's at the end of the street","Está al final de la calle","directions","When locating something"],
  ["Take the second right","Tomá la segunda a la derecha","directions","When giving directions"],
  ["You can't miss it","No te lo podés perder","directions","When assuring it's easy to find"],
  ["It's across from the park","Está enfrente del parque","directions","When locating by landmark"],
  ["Follow this road","Seguí este camino","directions","When giving directions"],
  ["Keep going until you see...","Seguí hasta que veas...","directions","When giving directions"],
  ["It's behind the supermarket","Está detrás del supermercado","directions","When locating by landmark"],
  ["Head north","Andá hacia el norte","directions","When giving cardinal directions"],
  ["My phone is about to die","Mi teléfono está por apagarse","phone","When warning about low battery"],
  ["I have bad reception here","Tengo mala señal acá","phone","When explaining communication problems"],
  ["Let me call you back","Dejame que te llamo de vuelta","phone","When postponing a call"],
  ["Leave a message after the beep","Dejá un mensaje después del tono","phone","Voicemail"],
  ["The line is busy","La línea está ocupada","phone","When trying to make a call"],
  ["Hold on, someone is calling me","Esperá, me están llamando","phone","When receiving another call"],
  ["My signal keeps dropping","Se me corta la señal","phone","When explaining a bad connection"],
  ["Can you put me on speaker?","¿Me ponés en altavoz?","phone","When asking for hands-free mode"],
  ["My phone is on silent","Tengo el teléfono en silencio","phone","When explaining you can't be heard"],
  ["I'm worried about you","Estoy preocupado por vos","emotions","When expressing worry"],
  ["I'm feeling nervous","Me siento nervioso","emotions","When expressing anxiety"],
  ["I'm disappointed","Estoy decepcionado","emotions","When expressing disappointment"],
  ["I'm so proud of you!","¡Estoy tan orgulloso de vos!","emotions","When expressing pride"],
  ["I'm really stressed out","Estoy muy estresado","emotions","When expressing stress"],
  ["That's so sweet of you!","¡Qué dulce de tu parte!","emotions","When thanking someone for a kind gesture"],
  ["I feel lonely","Me siento solo","emotions","When expressing loneliness"],
  ["I'm grateful for your help","Estoy agradecido por tu ayuda","emotions","When expressing gratitude"],
  ["I'm shocked!","¡Estoy en shock!","emotions","When expressing shock"],
  ["That's so annoying","Qué molesto","emotions","When expressing annoyance"],
  ["You made my day!","¡Me alegraste el día!","emotions","When thanking someone for a gesture"],
  ["That's a relief!","¡Qué alivio!","emotions","When feeling relief"],
  ["I'm jealous","Estoy celoso / Tengo envidia","emotions","When expressing jealousy"],
  ["I'm furious!","¡Estoy furioso!","emotions","When expressing extreme anger"],
  ["We're out of time","Se nos acabó el tiempo","time","When a deadline ends"],
  ["Can we meet earlier?","¿Podemos juntarnos más temprano?","time","When changing a schedule"],
  ["I was up all night","Estuve despierto toda la noche","time","When explaining a sleepless night"],
  ["Time flies!","¡El tiempo vuela!","time","When noticing time passed quickly"],
  ["The bus is delayed","El colectivo está demorado","time","When reporting a delay"],
  ["What's the weather forecast?","¿Cuál es el pronóstico del tiempo?","weather","When asking about the forecast"],
  ["The temperature is dropping","La temperatura está bajando","weather","When commenting on a change"],
  ["It's freezing out there!","¡Está helado afuera!","weather","When expressing extreme cold"],
  ["There is a storm coming","Se viene una tormenta","weather","When warning about the weather"],
  ["What is the temperature?","¿Qué temperatura hace?","weather","When asking about the temperature"],
  ["It is foggy this morning","Está con neblina esta mañana","weather","When describing visibility"],
  ["It's a bit chilly","Está un poco fresco","weather","When describing mild cold"],
  ["There is a heat wave","Hay una ola de calor","weather","When commenting on a weather event"],
  ["The humidity is really high","La humedad está muy alta","weather","When describing a feeling"],
  ["It's pouring outside!","¡Está lloviendo a cántaros!","weather","When describing heavy rain"],
  ["There might be a thunderstorm","Puede haber tormenta eléctrica","weather","When anticipating severe weather"],
  ["It should clear up later","Debería despejarse más tarde","weather","When anticipating improvement"],
  ["We had a lot of rain last week","Tuvimos mucha lluvia la semana pasada","weather","When commenting on past weather"],
  ["The sky is clear","El cielo está despejado","weather","When describing the sky"],
  ["What a gorgeous sunset!","¡Qué atardecer hermoso!","weather","When admiring the scenery"],
  ["It feels like 40 degrees!","¡Se siente como 40 grados!","weather","When commenting on how the temperature feels"],
  ["The weather has been crazy lately","El clima estuvo loco últimamente","weather","When commenting on changes in the weather"],
  ["Family comes first","La familia es primero","family","When expressing a value"],
  ["We have dinner together every Sunday","Cenamos juntos todos los domingos","family","When talking about a tradition"],
  ["My grandparents are from Italy","Mis abuelos son de Italia","family","When talking about origin"],
  ["She looks just like her mother","Es igualita a su mamá","family","When commenting on a resemblance"],
  ["My cousin lives in New York","Mi primo vive en Nueva York","family","When talking about relatives"],
  ["My brother and I are very close","Mi hermano y yo somos muy cercanos","family","When describing a relationship"],
  ["She is the youngest in the family","Ella es la menor de la familia","family","When talking about birth order"],
  ["We have a family reunion every year","Tenemos una reunión familiar cada año","family","When talking about a tradition"],
  ["My daughter just started school","Mi hija acaba de empezar la escuela","family","When sharing news"],
  ["He takes after his father","Salió al padre","family","When commenting on a resemblance"],
  ["My mother is a great cook","Mi mamá es una gran cocinera","family","When complimenting a family member"],
  ["We are expecting a baby","Estamos esperando un bebé","family","When announcing a pregnancy"],
  ["I grew up in a small town","Crecí en un pueblo chico","family","When talking about childhood"],
  ["My father taught me how to drive","Mi papá me enseñó a manejar","family","When talking about something you learned"],
  ["She is a single mother","Ella es madre soltera","family","When describing a situation"],
  ["My siblings and I get along well","Mis hermanos y yo nos llevamos bien","family","When describing a relationship"],
  ["Family is everything to me","La familia lo es todo para mí","family","When expressing a value"],
  ["My parents are divorced","Mis padres están divorciados","family","When talking about a situation"],
];
