// saflash — A1 words. Row format: [english, spanish, category, subcategory|null]

export const A1_WORDS = [
  ["A","vocal A","vowels",null],
  ["E","vocal E","vowels",null],
  ["I","vocal I","vowels",null],
  ["O","vocal O","vowels",null],
  ["U","vocal U","vowels",null],
  ["zero","cero","numbers",null],
  ["one","uno","numbers",null],
  ["two","dos","numbers",null],
  ["three","tres","numbers",null],
  ["four","cuatro","numbers",null],
  ["five","cinco","numbers",null],
  ["six","seis","numbers",null],
  ["seven","siete","numbers",null],
  ["eight","ocho","numbers",null],
  ["nine","nueve","numbers",null],
  ["ten","diez","numbers",null],
  ["eleven","once","numbers",null],
  ["twelve","doce","numbers",null],
  ["twenty","veinte","numbers",null],
  ["the","el/la/los/las","basics",null],
  ["be","ser/estar","verbs_common",null],
  ["to","a/para","basics",null],
  ["of","de","basics",null],
  ["and","y","basics",null],
  ["in","en","basics",null],
  ["that","ese/esa/que","basics",null],
  ["have","tener","verbs_common",null],
  ["it","eso","basics",null],
  ["for","para/por","basics",null],
  ["not","no","basics",null],
  ["on","en/sobre","basics",null],
  ["with","con","basics",null],
  ["he","él","basics",null],
  ["you","tú/usted","basics",null],
  ["do","hacer","verbs_common",null],
  ["this","este/esta","basics",null],
  ["but","pero","basics",null],
  ["his","su (de él)","basics",null],
  ["they","ellos/ellas","basics",null],
  ["we","nosotros","basics",null],
  ["she","ella","basics",null],
  ["say","decir","verbs_common",null],
  ["her","su (de ella)/la","basics",null],
  ["or","o","basics",null],
  ["an","un/una (vocal)","basics",null],
  ["will","(futuro)","basics",null],
  ["my","mi/mis","basics",null],
  ["all","todo/todos","basics",null],
  ["would","(condicional)","basics",null],
  ["there","allí/ahí/hay","basics",null],
  ["their","su/sus (ellos)","basics",null],
  ["what","qué","basics",null],
  ["so","entonces/tan","basics",null],
  ["up","arriba","basics",null],
  ["out","fuera/afuera","basics",null],
  ["if","si (condicional)","basics",null],
  ["about","sobre/acerca de","basics",null],
  ["who","quién","basics",null],
  ["get","obtener/conseguir","verbs_common",null],
  ["which","cuál","basics",null],
  ["go","ir","verbs_common",null],
  ["me","me/mí","basics",null],
  ["when","cuándo","basics",null],
  ["make","hacer/fabricar","verbs_common",null],
  ["can","poder","verbs_common",null],
  ["like","gustar/como","basics",null],
  ["time","tiempo/hora","basics",null],
  ["no","no","basics",null],
  ["just","solo/justo","basics",null],
  ["him","lo/le (a él)","basics",null],
  ["know","saber/conocer","verbs_common",null],
  ["take","tomar/llevar","verbs_common",null],
  ["people","personas/gente","basics",null],
  ["into","dentro de/en","basics",null],
  ["year","año","basics",null],
  ["your","tu/tus/su/sus","basics",null],
  ["good","bueno/bien","adjectives",null],
  ["some","algunos/algo de","basics",null],
  ["could","podría","basics",null],
  ["them","los/las/les","basics",null],
  ["see","ver","verbs_common",null],
  ["other","otro/otros","basics",null],
  ["than","que (comparación)","basics",null],
  ["then","entonces/luego","basics",null],
  ["now","ahora","basics",null],
  ["look","mirar/parecer","verbs_common",null],
  ["only","solo/solamente","basics",null],
  ["come","venir","verbs_common",null],
  ["its","su/sus (cosa)","basics",null],
  ["over","sobre/encima","basics",null],
  ["think","pensar","verbs_common",null],
  ["also","también","basics",null],
  ["back","atrás/de vuelta","basics",null],
  ["after","después de","basics",null],
  ["use","usar","verbs_common",null],
  ["how","cómo/cuánto","basics",null],
  ["our","nuestro/nuestra","basics",null],
  ["work","trabajar/trabajo","work_business",null],
  ["first","primero","basics",null],
  ["well","bien/pozo","basics",null],
  ["way","camino/manera","basics",null],
  ["even","incluso/par","basics",null],
  ["new","nuevo","adjectives",null],
  ["want","querer","verbs_common",null],
  ["because","porque","basics",null],
  ["any","cualquier/alguno","basics",null],
  ["these","estos/estas","basics",null],
  ["give","dar","verbs_common",null],
  ["day","día","basics",null],
  ["most","mayoría/el más","basics",null],
  ["us","nos/nosotros","basics",null],
  ["great","genial/grande","adjectives",null],
  ["man","hombre","basics",null],
  ["woman","mujer","basics",null],
  ["water","agua","food_drink","beverages"],
  ["food","comida","food_drink",null],
  ["big","grande","adjectives",null],
  ["small","pequeño","adjectives",null],
  ["long","largo","adjectives",null],
  ["little","pequeño/poco","adjectives",null],
  ["own","propio","basics",null],
  ["old","viejo/antiguo","adjectives",null],
  ["right","derecho/correcto","basics",null],
  ["hand","mano","body",null],
  ["here","aquí","basics",null],
  ["home","hogar/casa","home",null],
  ["house","casa","home",null],
  ["life","vida","other",null],
  ["child","niño/niña","family",null],
  ["should","debería","basics",null],
  ["place","lugar","other",null],
  ["still","todavía","adverbs",null],
  ["thing","cosa","other",null],
  ["part","parte","other",null],
  ["where","dónde","basics",null],
  ["every","cada/todo","basics",null],
  ["need","necesitar","verbs_common",null],
  ["ask","preguntar/pedir","verbs_action",null],
  ["find","encontrar","verbs_action",null],
  ["tell","decir/contar","verbs_action",null],
  ["put","poner","verbs_action",null],
  ["help","ayudar","verbs_action",null],
  ["talk","hablar","verbs_action",null],
  ["start","empezar","verbs_action",null],
  ["hear","oír","verbs_action",null],
  ["play","jugar/tocar","verbs_action",null],
  ["run","correr","verbs_action",null],
  ["live","vivir","verbs_action",null],
  ["write","escribir","verbs_action",null],
  ["sit","sentarse","verbs_action",null],
  ["stand","pararse","verbs_action",null],
  ["meet","conocer/reunirse","verbs_action",null],
  ["learn","aprender","verbs_action",null],
  ["watch","mirar/observar","verbs_action",null],
  ["stop","parar/detener","verbs_action",null],
  ["speak","hablar","verbs_action",null],
  ["read","leer","verbs_action",null],
  ["open","abrir","verbs_action",null],
  ["walk","caminar","verbs_action",null],
  ["love","amar/encantar","verbs_action",null],
  ["buy","comprar","verbs_action",null],
  ["eat","comer","verbs_action",null],
  ["drink","beber/tomar","verbs_action",null],
  ["sleep","dormir","verbs_action",null],
  ["sing","cantar","verbs_action",null],
  ["dance","bailar","verbs_action",null],
  ["swim","nadar","verbs_action",null],
  ["drive","manejar/conducir","verbs_action",null],
  ["clean","limpiar","verbs_action",null],
  ["wash","lavar","verbs_action",null],
  ["draw","dibujar","verbs_action",null],
  ["call","llamar","verbs_action",null],
  ["listen","escuchar","verbs_action",null],
  ["feel","sentir","verbs_action",null],
  ["smile","sonreír","verbs_action",null],
  ["leave","irse/dejar","verbs_action",null],
  ["count","contar","verbs_action",null],
  ["happy","feliz","adjectives",null],
  ["sad","triste","adjectives",null],
  ["fast","rápido","adjectives",null],
  ["slow","lento","adjectives",null],
  ["beautiful","hermoso","adjectives",null],
  ["hot","caliente","adjectives",null],
  ["cold","frío","adjectives",null],
  ["young","joven","adjectives",null],
  ["strong","fuerte","adjectives",null],
  ["tall","alto","adjectives",null],
  ["short","bajo/corto","adjectives",null],
  ["easy","fácil","adjectives",null],
  ["dark","oscuro","adjectives",null],
  ["hungry","hambriento","adjectives",null],
  ["thirsty","sediento","adjectives",null],
  ["tired","cansado","adjectives",null],
  ["sick","enfermo","adjectives",null],
  ["late","tarde","adjectives",null],
  ["room","habitación/cuarto","home",null],
  ["door","puerta","home",null],
  ["window","ventana","home",null],
  ["wall","pared/muro","home",null],
  ["table","mesa","home",null],
  ["chair","silla","home",null],
  ["bed","cama","home",null],
  ["light","luz","home",null],
  ["kitchen","cocina","home",null],
  ["bathroom","baño","home",null],
  ["bedroom","dormitorio","home",null],
  ["clock","reloj (pared)","home",null],
  ["television","televisor","home",null],
  ["radio","radio","home",null],
  ["mother","madre","family",null],
  ["father","padre","family",null],
  ["parent","padre/madre","family",null],
  ["son","hijo","family",null],
  ["daughter","hija","family",null],
  ["brother","hermano","family",null],
  ["sister","hermana","family",null],
  ["baby","bebé","family",null],
  ["friend","amigo","family",null],
  ["head","cabeza","body",null],
  ["face","cara/rostro","body",null],
  ["hair","pelo/cabello","body",null],
  ["eye","ojo","body",null],
  ["nose","nariz","body",null],
  ["mouth","boca","body",null],
  ["ear","oreja/oído","body",null],
  ["arm","brazo","body",null],
  ["finger","dedo (mano)","body",null],
  ["leg","pierna","body",null],
  ["foot","pie","body",null],
  ["heart","corazón","body",null],
  ["tooth","diente","body",null],
  ["doctor","médico/doctor","health",null],
  ["hospital","hospital","health",null],
  ["apple","manzana","food_drink","fruits"],
  ["banana","banana/plátano","food_drink","fruits"],
  ["orange","naranja","food_drink","fruits"],
  ["tomato","tomate","food_drink","vegetables"],
  ["potato","papa/patata","food_drink","vegetables"],
  ["rice","arroz","food_drink","grains"],
  ["bread","pan","food_drink","grains"],
  ["sugar","azúcar","food_drink",null],
  ["salt","sal","food_drink",null],
  ["egg","huevo","food_drink",null],
  ["cheese","queso","food_drink","dairy"],
  ["milk","leche","food_drink","dairy"],
  ["ice cream","helado","food_drink","dairy"],
  ["chicken","pollo","food_drink","meat"],
  ["fish","pescado","food_drink","seafood"],
  ["pizza","pizza","food_drink",null],
  ["cake","torta/pastel","food_drink","desserts"],
  ["chocolate","chocolate","food_drink","desserts"],
  ["coffee","café","food_drink","beverages"],
  ["tea","té","food_drink","beverages"],
  ["juice","jugo/zumo","food_drink","beverages"],
  ["breakfast","desayuno","food_drink","meals"],
  ["lunch","almuerzo","food_drink","meals"],
  ["dinner","cena","food_drink","meals"],
  ["shirt","camisa","clothing",null],
  ["pants","pantalones","clothing",null],
  ["shoes","zapatos","clothing",null],
  ["hat","sombrero/gorro","clothing",null],
  ["dress","vestido","clothing",null],
  ["socks","medias/calcetines","clothing",null],
  ["tree","árbol","nature",null],
  ["flower","flor","nature",null],
  ["river","río","nature",null],
  ["sea","mar","nature",null],
  ["beach","playa","nature",null],
  ["sky","cielo","nature",null],
  ["rain","lluvia","nature",null],
  ["sun","sol","nature",null],
  ["moon","luna","nature",null],
  ["star","estrella","nature",null],
  ["fire","fuego","nature",null],
  ["dog","perro","animals","pets"],
  ["cat","gato","animals","pets"],
  ["bird","pájaro/ave","animals","birds"],
  ["horse","caballo","animals","farm"],
  ["cow","vaca","animals","farm"],
  ["computer","computadora","technology",null],
  ["phone","teléfono","technology",null],
  ["internet","internet","technology",null],
  ["car","auto/coche","transport",null],
  ["bus","colectivo/autobús","transport",null],
  ["train","tren","transport",null],
  ["bicycle","bicicleta","transport",null],
  ["street","calle","transport",null],
  ["school","escuela/colegio","education",null],
  ["teacher","maestro/profesor","education",null],
  ["student","estudiante/alumno","education",null],
  ["pencil","lápiz","education",null],
  ["pen","lapicera/bolígrafo","education",null],
  ["soccer","fútbol","sports",null],
  ["basketball","básquet/baloncesto","sports",null],
  ["swimming","natación","sports",null],
  ["ball","pelota/balón","sports",null],
  ["red","rojo","colors_shapes",null],
  ["blue","azul","colors_shapes",null],
  ["green","verde","colors_shapes",null],
  ["yellow","amarillo","colors_shapes",null],
  ["black","negro","colors_shapes",null],
  ["white","blanco","colors_shapes",null],
  ["Monday","lunes","numbers_time",null],
  ["Tuesday","martes","numbers_time",null],
  ["Wednesday","miércoles","numbers_time",null],
  ["Thursday","jueves","numbers_time",null],
  ["Friday","viernes","numbers_time",null],
  ["Saturday","sábado","numbers_time",null],
  ["Sunday","domingo","numbers_time",null],
  ["today","hoy","numbers_time",null],
  ["tomorrow","mañana","numbers_time",null],
  ["yesterday","ayer","numbers_time",null],
  ["morning","mañana","numbers_time",null],
  ["afternoon","tarde","numbers_time",null],
  ["evening","noche (temprano)","numbers_time",null],
  ["night","noche","numbers_time",null],
  ["week","semana","numbers_time",null],
  ["month","mes","numbers_time",null],
  ["summer","verano","numbers_time",null],
  ["winter","invierno","numbers_time",null],
  ["very","muy","adverbs",null],
  ["always","siempre","adverbs",null],
  ["never","nunca","adverbs",null],
  ["music","música","arts_culture",null],
  ["song","canción","arts_culture",null],
  ["movie","película","arts_culture",null],
  ["book","libro","arts_culture",null],
  ["store","tienda/negocio","shopping",null],
  ["money","dinero/plata","shopping",null],
  ["shop","tienda/comprar","shopping",null],
  ["hello","hola","social",null],
  ["goodbye","adiós","social",null],
  ["please","por favor","social",null],
  ["thanks","gracias","social",null],
  ["sorry","perdón/lo siento","social",null],
  ["welcome","bienvenido","social",null],
  ["see you","nos vemos","social",null],
  ["good luck","buena suerte","social",null],
  ["happy birthday","feliz cumpleaños","social",null],
  ["merry Christmas","feliz Navidad","social",null],
  ["happy New Year","feliz Año Nuevo","social",null],
  ["how are you","cómo estás","social",null],
  ["what is your name","cómo te llamás","social",null],
  ["hotel","hotel","travel",null],
];
