// saflash — B1 words. Row format: [english, spanish, category, subcategory|null]

export const B1_WORDS = [
  ["include","incluir","other",null],
  ["continue","continuar","verbs_action",null],
  ["lead","liderar/guiar","verbs_action",null],
  ["create","crear","verbs_action",null],
  ["allow","permitir","verbs_action",null],
  ["offer","ofrecer","verbs_action",null],
  ["consider","considerar","other",null],
  ["appear","aparecer","other",null],
  ["expect","esperar/suponer","other",null],
  ["reach","alcanzar/llegar","verbs_action",null],
  ["remain","permanecer","other",null],
  ["suggest","sugerir","other",null],
  ["raise","levantar/aumentar","verbs_action",null],
  ["require","requerir","other",null],
  ["report","informar/reportar","other",null],
  ["whisper","susurrar","verbs_action",null],
  ["lend","prestar","verbs_action",null],
  ["steal","robar","verbs_action",null],
  ["earn","ganar (dinero)","verbs_action",null],
  ["choose","elegir","verbs_action",null],
  ["organize","organizar","verbs_action",null],
  ["imagine","imaginar","verbs_action",null],
  ["promise","prometer","verbs_action",null],
  ["describe","describir","verbs_action",null],
  ["compare","comparar","other",null],
  ["disagree","no estar de acuerdo","other",null],
  ["accept","aceptar","other",null],
  ["refuse","rechazar","other",null],
  ["bother","molestar","other",null],
  ["depend","depender","other",null],
  ["belong","pertenecer","other",null],
  ["contain","contener","other",null],
  ["exist","existir","other",null],
  ["produce","producir","other",null],
  ["develop","desarrollar","other",null],
  ["support","apoyar/soportar","other",null],
  ["protect","proteger","other",null],
  ["prevent","prevenir/evitar","other",null],
  ["avoid","evitar","other",null],
  ["cause","causar","other",null],
  ["affect","afectar","other",null],
  ["increase","aumentar","other",null],
  ["reduce","reducir","other",null],
  ["improve","mejorar","other",null],
  ["achieve","lograr","other",null],
  ["determine","determinar","other",null],
  ["identify","identificar","other",null],
  ["recognize","reconocer","other",null],
  ["introduce","presentar/introducir","other",null],
  ["mention","mencionar","other",null],
  ["claim","afirmar/reclamar","other",null],
  ["prove","probar/demostrar","other",null],
  ["confirm","confirmar","other",null],
  ["deny","negar","other",null],
  ["argue","discutir/argumentar","other",null],
  ["discuss","discutir/debatir","other",null],
  ["express","expresar","other",null],
  ["complain","quejarse","other",null],
  ["warn","advertir","other",null],
  ["encourage","animar/alentar","other",null],
  ["convince","convencer","other",null],
  ["force","forzar/obligar","other",null],
  ["common","común","adjectives",null],
  ["rare","raro/poco común","adjectives",null],
  ["necessary","necesario","adjectives",null],
  ["available","disponible","adjectives",null],
  ["similar","similar/parecido","adjectives",null],
  ["complex","complejo","adjectives",null],
  ["exciting","emocionante","adjectives",null],
  ["awful","horrible","adjectives",null],
  ["pleasant","agradable","adjectives",null],
  ["unpleasant","desagradable","adjectives",null],
  ["uncomfortable","incómodo","adjectives",null],
  ["cruel","cruel","adjectives",null],
  ["brave","valiente","adjectives",null],
  ["proud","orgulloso","adjectives",null],
  ["ashamed","avergonzado","adjectives",null],
  ["jealous","celoso","adjectives",null],
  ["curious","curioso","adjectives",null],
  ["confident","seguro de sí mismo","adjectives",null],
  ["faucet","grifo/canilla","home",null],
  ["rug","alfombra pequeña","home",null],
  ["nephew","sobrino","family",null],
  ["niece","sobrina","family",null],
  ["twin","gemelo/mellizo","family",null],
  ["partner","pareja/compañero","family",null],
  ["marriage","matrimonio","family",null],
  ["muscle","músculo","body",null],
  ["lung","pulmón","body",null],
  ["liver","hígado","body",null],
  ["kidney","riñón","body",null],
  ["eyebrow","ceja","body",null],
  ["patient","paciente","health",null],
  ["surgery","cirugía","health",null],
  ["emergency","emergencia","health",null],
  ["ambulance","ambulancia","health",null],
  ["injury","lesión/herida","health",null],
  ["wound","herida","health",null],
  ["virus","virus","health",null],
  ["infection","infección","health",null],
  ["vaccine","vacuna","health",null],
  ["allergy","alergia","health",null],
  ["prescription","receta médica","health",null],
  ["treatment","tratamiento","health",null],
  ["recovery","recuperación","health",null],
  ["blood pressure","presión arterial","health",null],
  ["symptom","síntoma","health",null],
  ["diagnosis","diagnóstico","health",null],
  ["operation","operación","health",null],
  ["wheelchair","silla de ruedas","health",null],
  ["bandage","vendaje/venda","health",null],
  ["syringe","jeringa","health",null],
  ["X-ray","radiografía","health",null],
  ["therapy","terapia","health",null],
  ["mental health","salud mental","health",null],
  ["toothache","dolor de muelas","health",null],
  ["flour","harina","food_drink","grains"],
  ["uniform","uniforme","clothing",null],
  ["zipper","cierre/cremallera","clothing",null],
  ["silk","seda","clothing",null],
  ["thunder","trueno","nature",null],
  ["lightning","relámpago/rayo","nature",null],
  ["soil","suelo/tierra","nature",null],
  ["cave","cueva/caverna","nature",null],
  ["volcano","volcán","nature",null],
  ["earthquake","terremoto/sismo","nature",null],
  ["flood","inundación","nature",null],
  ["sunrise","amanecer/salida del sol","nature",null],
  ["wolf","lobo","animals","wild"],
  ["fox","zorro","animals","wild"],
  ["deer","ciervo/venado","animals","wild"],
  ["gorilla","gorila","animals","wild"],
  ["dolphin","delfín","animals","sea"],
  ["eagle","águila","animals","birds"],
  ["parrot","loro","animals","birds"],
  ["software","software/programa","technology",null],
  ["hardware","hardware","technology",null],
  ["data","datos","technology",null],
  ["upload","subir/cargar","technology",null],
  ["network","red","technology",null],
  ["Bluetooth","Bluetooth","technology",null],
  ["robot","robot","technology",null],
  ["search engine","buscador","technology",null],
  ["social media","redes sociales","technology",null],
  ["helicopter","helicóptero","transport",null],
  ["ferry","ferry/transbordador","transport",null],
  ["highway","autopista","transport",null],
  ["tunnel","túnel","transport",null],
  ["engine","motor","transport",null],
  ["degree","título/grado","education",null],
  ["laboratory","laboratorio","education",null],
  ["science","ciencia","education",null],
  ["semester","semestre","education",null],
  ["scholarship","beca","education",null],
  ["graduation","graduación","education",null],
  ["golf","golf","sports",null],
  ["trophy","trofeo","sports",null],
  ["stadium","estadio","sports",null],
  ["competition","competencia/competición","sports",null],
  ["tournament","torneo","sports",null],
  ["Olympics","Juegos Olímpicos","sports",null],
  ["racket","raqueta","sports",null],
  ["anger","enojo/ira","emotions",null],
  ["joy","alegría","emotions",null],
  ["sadness","tristeza","emotions",null],
  ["disgust","asco/repulsión","emotions",null],
  ["trust","confianza","emotions",null],
  ["jealousy","celos/envidia","emotions",null],
  ["regret","arrepentimiento","emotions",null],
  ["shame","vergüenza","emotions",null],
  ["guilt","culpa","emotions",null],
  ["gratitude","gratitud","emotions",null],
  ["pride","orgullo","emotions",null],
  ["relief","alivio","emotions",null],
  ["boredom","aburrimiento","emotions",null],
  ["excitement","emoción/entusiasmo","emotions",null],
  ["confusion","confusión","emotions",null],
  ["oval","óvalo","colors_shapes",null],
  ["easily","fácilmente","adverbs",null],
  ["perhaps","quizás/tal vez","adverbs",null],
  ["probably","probablemente","adverbs",null],
  ["certainly","ciertamente/seguro","adverbs",null],
  ["suddenly","de repente/repentinamente","adverbs",null],
  ["finally","finalmente/al fin","adverbs",null],
  ["recently","recientemente","adverbs",null],
  ["immediately","inmediatamente","adverbs",null],
  ["photography","fotografía","arts_culture",null],
  ["sculpture","escultura","arts_culture",null],
  ["literature","literatura","arts_culture",null],
  ["poem","poema","arts_culture",null],
  ["violin","violín","arts_culture",null],
  ["director","director","arts_culture",null],
  ["customer","cliente","shopping",null],
  ["brand","marca","shopping",null],
  ["product","producto","shopping",null],
  ["visa","visa","travel",null],
  ["reservation","reserva/reservación","travel",null],
  ["destination","destino","travel",null],
  ["departure","salida/partida","travel",null],
  ["arrival","llegada","travel",null],
  ["boarding pass","tarjeta de embarque","travel",null],
  ["customs","aduana","travel",null],
  ["currency","moneda/divisa","travel",null],
  ["exchange rate","tipo de cambio","travel",null],
  ["travel insurance","seguro de viaje","travel",null],
  ["salary","salario/sueldo","work_business",null],
  ["career","carrera profesional","work_business",null],
  ["colleague","colega/compañero de trabajo","work_business",null],
  ["interview","entrevista","work_business",null],
  ["resume","currículum","work_business",null],
  ["contract","contrato","work_business",null],
  ["deadline","fecha límite","work_business",null],
  ["project","proyecto","work_business",null],
  ["presentation","presentación","work_business",null],
  ["client","cliente","work_business",null],
  ["manager","gerente/encargado","work_business",null],
  ["employee","empleado","work_business",null],
  ["employer","empleador","work_business",null],
  ["promotion","ascenso/promoción","work_business",null],
  ["retirement","jubilación/retiro","work_business",null],
  ["business","negocio/empresa","work_business",null],
  ["factory","fábrica","work_business",null],
  ["industry","industria","work_business",null],
  ["trade","comercio/intercambio","work_business",null],
  ["profit","ganancia/beneficio","work_business",null],
  ["loss","pérdida","work_business",null],
  ["investment","inversión","work_business",null],
  ["budget","presupuesto","work_business",null],
  ["tax","impuesto","work_business",null],
];
